src/presets/azure-functions.ts

fix: update azure functions preset

---

src/presets/firebase.ts

Similarly to azure, a typo in migration.

fix: update firebase output for package.json

---

README.md
src/rollup/config.ts

The case police is here! 👮‍♂️😜

chore: fix term cases

---

docs/guide/configuration.md

> ### 🔗 Linked issue
> ### ❓ Type of change
> * [x]  📖 Documentation (updates to the documentation or readme)
> * [ ]  🐞 Bug fix (a non-breaking change that fixes an issue)
> * [ ]  👌 Enhancement (improving an existing functionality like performance)
> * [ ]  ✨ New feature (a non-breaking change that adds functionality)
> * [ ]  ⚠️ Breaking change (fix or feature that would cause existing functionality to change)
> 
> ### 📚 Description
> ### 📝 Checklist
> * [ ]  I have linked an issue or discussion.
> * [ ]  I have updated the documentation accordingly.
Removes duplication

docs: remove duplication

---

docs/guide/cache.md

docs: remove `)` typo

---

src/utils/index.ts

std-env has a nice provider database; we can use that here, and specially as we add more zero-config providers.

feat: use `std-env` to detect provider

---

src/prerender.ts

Parse extracted links, remove hash and search params, Prevent generating duplicate pages.

fix(prerender): use pathname from extracted links only

---

src/runtime/config.ts

reverts https://github.com/unjs/nitro/pull/65/commits/686320eb8aff63315c2ec122f2a85b9e55a82bd6
Returning `true` allows for overriding nested variables.

fix: allow overriding nested variables

---

src/rollup/plugins/server-assets.ts

- Fix typo in dev assets base
- For production assets, utilities should return promise

fix(server-assets): assets behavior

---

src/prerender.ts
test/fixture/nitro.config.ts
test/fixture/routes/prerender.ts

Related to https://github.com/nuxt/nuxt3-docs/issues/21
The crawler should only extract the relative link. I don't know where to add a test case, I did test in the nuxt 3 upcoming docs and fixes the isssue.

fix(prerender): only extract relative links

---

docs/.vitepress/config.ts
docs/deploy/node.md
docs/deploy/providers/aws.md
docs/deploy/providers/azure.md
docs/deploy/providers/cloudflare.md
docs/deploy/providers/digitalocean.md
docs/deploy/providers/firebase.md
docs/deploy/providers/heroku.md
docs/deploy/providers/layer0.md
docs/deploy/providers/netlify.md
docs/deploy/providers/render.md
docs/deploy/providers/stormkit.md
docs/deploy/providers/vercel.md
docs/index.md

None.
Some minor typos have been fixed.

docs: fix minor typos

---

docs/deploy/providers/layer0.md

https://github.com/unjs/nitro/issues/56
Add deploy documentation for Layer0 preset

docs: add layer0 preset

---

docs/deploy/providers/aws.md

docs: correct spelling of Lambda

---

src/runtime/config.ts

resolves https://github.com/unjs/nitro/issues/139, closes https://github.com/unjs/nitro/pull/140
This reverts to an earlier version of the override configuration in https://github.com/unjs/nitro/pull/65.

fix: manually merge runtime config with env

---

docs/deploy/node.md

docs: fix spelling of signature

---

src/runtime/cache.ts

This PR replaces `magAge` by `maxAge` in runtime cache

fix(cache): fix maxage typo

---

docs/index.md

Fix typo on the homepage. Goodby should be goodbye.

docs: Fix Typo

---

src/imports.ts

- cachedFunction
- cachedEventHandler
We may need to update the example to `cachedFunction` as well here: https://nitro.unjs.io/guide/cache.html#examples

fix: add cached shortcuts to the imports

---

docs/guide/cache.md

Because shortcuts are sexy, following #162

docs: update `defineCachedFunction` to `cachedFunction`

---

src/prerender.ts

https://github.com/nuxt/framework/issues/4581, resolves #220
Small fix to ensure we don't get 404s when prerendering with custom baseURL.

fix: respect baseURL in prerendering

---

src/presets/nitro-prerender.ts

https://github.com/nuxt/framework/issues/4878, resolves  #218
This adds a preview command for prerendered `.output/public`

feat: add preview command for prerender

---

docs/guide/cache.md

docs: typo

---

docs/guide/routing.md

docs: api route with method

---

src/runtime/entries/stormkit.ts

This change is necessary to make the request more similar to the [http.IncomingMessage](https://nodejs.org/api/http.html#class-httpincomingmessage) class.

fix(stormkit): update request signature

---

src/presets/cloudflare.ts

We do not support wrangler 2 so far:
This PR fixes the deploy command displayed in order to work properly (which is currently displayed when using Nuxt 3 as well).

fix(cloudflare): use `@cloudflare/wrangler` until we support wrangler 2

---

src/dev/server.ts

Stackblitz does not have some of these values set, and so this crashes the dev server.
See https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz

fix: check if socket address/port/family are set

---

docs/config/index.md

The actual config option is "prerender", it's not the same as in the docs.

docs(config): correct `prerenderer` to `prerender`

---

src/presets/vercel.ts

feat(vercel): update to the v3 output api

---

docs/guide/storage.md

This adds details to the Storage Layer guide on how to mount storage drivers and on the `devStorage` configuration key.

docs(storage): details on how to mount drivers

---

docs/deploy/providers/azure.md

Add link to the Azure docs on how to specify environment variables, which one has to do if runtime config is used.

docs(azure): Add pointer to how to add env variables

---

docs/deploy/providers/heroku.md

I suggest you to update the Heroku installation because the default documentation does not provide all the required information to successfully launch an Heroku container.
A StackBlitz is ready for Heroku here: https://stackblitz.com/edit/nuxt-starter-hwweyr?file=app.vue

docs(heroku): add note about necessary `package.json` scripts

---

src/dev/server.ts
src/runtime/error.ts
src/types/handler.ts

https://github.com/unjs/h3/pull/162
We can use the h3-sourced fatal/unhandled flags to tell us when to log errors.

fix: only log unhandled/fatal errors

---

docs/guide/routing.md

`useBody()` requires passing in the event or request
N/A
`useBody()` has a required parameter. The event should be passed in

docs: Fix incorrect api use for `useBody`

---

src/presets/azure.ts

The route name generated by nitro for azure was not correct due to a typo. Instead of erasing the suffix `.html` only the first 5 characters were used.

fix(azure): fix route name

---

src/runtime/entries/aws-lambda.ts

https://github.com/nuxt/framework/issues/5947, possibly https://github.com/nuxt/framework/issues/3803.
Fixes a typo where we are joining cookies with comma rather than semicolon.

fix(aws-lambda): join cookies with semicolon

---

docs/content/1.guide/1.introduction/6.assets.md

docs: fix internal link

---

docs/content/2.deploy/providers/cloudflare.md

Update the Cloudflare Workers docs part, to wrangler 2 usage (it's the defacto official now).

docs(cloudflare): update to use wrangler2

---

src/presets/vercel.ts

fix: allow for non-existent vercel config

---

src/presets/netlify.ts

https://github.com/nuxt/framework/issues/7592, https://github.com/nuxt/framework/issues/5509
Currently nitro emits an invalid manifest for netlify edge. This updates the pattern to match the current netlify edge requirements.
**Note**: Once fixed, there is another issue I'm experiencing with netlify edge and will be investigating that next.

fix(netlify-edge): update manifest pattern and output format

---

docs/content/2.deploy/providers/cleavr.md
src/presets/cleavr.ts

#522 
Add Cleavr.io (https://cleavr.io) preset  for Nitro.
Resolves #522

feat: add cleavr preset

---

src/runtime/static.ts

[#8454](https://github.com/nuxt/framework/issues/8454)
This allows user to override static headers either via a route rule or other middleware.

fix: allow user to override static headers

---

src/runtime/static.ts

> All [1xx (Informational)](https://httpwg.org/specs/rfc9110.html#status.1xx), [204 (No Content)](https://httpwg.org/specs/rfc9110.html#status.204), and [304 (Not Modified)](https://httpwg.org/specs/rfc9110.html#status.304) responses do not include content.
https://httpwg.org/specs/rfc9110.html#status.304

fix: do not write bodies for 304 responses

---

src/options.ts

refactor: fix typo in internal function name

---

src/prerender.ts
src/types/nitro.ts

feat: support `prerender:routes` hook

---

docs/content/2.deploy/providers/netlify.md

Ideally routeRules would be the core way people define redirects as it's compatible across presets.

docs: add mention of routeRules in netlify redirects

---

.github/ISSUE_TEMPLATE/bug-report.yml

No issues related.
I found this typo while I'm creating https://github.com/unjs/template/pull/30.
I just removed a typo.
N/A

fix: GitHub template

---

test/fixture/types.ts

This reverts commit 1d9102a7215414068e30b52c96324ec3553b61c8.
closes https://github.com/unjs/nitro/pull/771

test: re-enable api type tests and fix type assertion

---

src/build.ts
src/utils/tree.ts

This fixes the log of the build FS tree:
From
To

fix(build): correctly formatted fs tree

---

docs/content/2.deploy/providers/render.md

Add another option to deploy to render, called Infrastructure as Code, and add two steps and one sample code to the page.
The advantage is that deployment steps can be set up in one click and error opportunities can be reduced

docs: add new render deployment examples & steps

---

src/options.ts

Fixes a Nuxt related issue: https://github.com/nuxt/framework/issues/9961
I'm not sure this is the best way to fix it but this should at least allow for fully customizing that exclude array.

fix: resolve and include scanDirs within `node_modules` for auto import

---

docs/content/1.guide/1.introduction/3.routing.md

Fixed a typo in the [routing part of the introduction[(https://nitro.unjs.io/guide/introduction/routing). Instead of `readBody` it was `readyBody`.

docs: fix typo in code block

---

package.json

https://github.com/nuxt/nuxt/pull/18431
This adds type support to imports from nitropack in TS Node16 style module resolution.

fix: add node16 compatible type declaration

---

src/rollup/plugins/externals.ts
test/fixture/_/node_modules/nitro-lib/package.json

Co-Authored-By: Daniel Roe <daniel@roe.dev>

fix(externals): improve multi version handling

---

docs/content/2.deploy/providers/digitalocean.md

Current docs are incomplete as they don't specify how to set up a run command after build. This should fix that. Others have this issue as shown here: https://www.youtube.com/watch?v=hANbHC90xug. Thanks to Jahid Anowar for figuring it out.

docs(digitalocean): update deployment guide

---

src/rollup/plugins/externals.ts

fix(externals): use portable symlinks

---

src/prerender.ts

nuxt/nuxt#18560
Resolves nuxt/nuxt#18560
Make request URL like others tools/libs
Ex: 
- original URL: `/archives/ベイスターズ/`
- actual request URL: `/archives/%E3%83%99%E3%82%A4%E3%82%B9%E3%82%BF%E3%83%BC%E3%82%BA/`

fix(prerender): encode urls passed to local fetch

---

docs/content/1.guide/1.introduction/6.assets.md

#914 
Correct the path of server assets

docs: fix path for server assets

---

src/runtime/cache.ts

resolves https://github.com/unjs/nitro/issues/935
resolves https://github.com/nuxt/nuxt/issues/18789

fix: avoid circular imports

---

docs/content/1.guide/1.introduction/5.cache.md

I didn't create an issue for this as it seems unnecessary, but let me know if I should do that first!
I was a bit confused by the promise in these examples without `await`.
My assumption is that these examples are trying to show a long-running event handler via `setTimeout`.

docs: add await keyword to cachedEventHandler examples

---

docs/content/2.deploy/0.index.md

Updates the content / example on deployment overview to be a bit more specific. The first time I came across this, I didn't really get it, tried to copy paste it, but nothing was working. Now it's a complete copy-paste ready codeblock.

docs: make example a bit more clear

---

README.md

| [Before](https://github.com/unjs/nitro/blob/2b92747e3d2f02a4e15c88c55a811f3136c2b7cd/README.md) | [After](https://github.com/unjs/nitro/blob/b857cd370dd47f3b0c3cf8e7941c837e4b7853f4/README.md) |
| --- | --- |
| <img width="888" alt="CleanShot 2023-03-03 at 12 24 05@2x" src="https://user-images.githubusercontent.com/904724/222708240-b6a78d6c-5114-4d70-bafe-c27fd8f4db53.png"> | <img width="891" alt="CleanShot 2023-03-03 at 12 24 16@2x" src="https://user-images.githubusercontent.com/904724/222708261-9584b7eb-4211-4559-bdad-4ea09706e0c2.png"> |

chore(readme): various improvements

---

docs/content/2.deploy/2.workers.md

#1045
Simply swaps letters.
Resolves #1045

docs: fix typo of bundle

---

docs/content/1.guide/7.plugins.md

Fix small typo in plugins documentation.

chore(doc): fix small typo in plugin filename

---

docs/content/1.guide/4.storage.md
docs/content/1.guide/5.cache.md

#1085 
Fixes minor grammatical errors.
Resolves #1085.

docs: fix typos in storage and cache guides

---

docs/content/1.guide/5.cache.md

docs: fix typo in cachedEventHandler options

---

docs/content/3.config.md

docs: use consistent quotes in the routeRules example

---

docs/content/3.config.md

Added an example of the object syntax of `redirect`

docs: update redirect route rule example

---

docs/content/2.deploy/providers/cloudflare.md

docs: update cloudflare-pages preset

---

docs/content/0.index.md
docs/tokens.config.ts

Improved primary color tokens for Docus 2.0. Also fixes landing cards grid layout.

fix(ui): primary color tokens; improve landing cards grid

---

src/runtime/cache.ts

fix(defineCachedFunction): properly infer function type

---

package.json

Adding a prepare script could help user to have generated types right after an installation.

chore(starter): add prepare command to starter

---

.npmrc

In documentation, you speak a lot about using `nitro` with `pnpm`. But when installing deps with `pnpm`, `h3` utils are just any since `h3` is not a first party dep and user must manually install it or add a `.npmrc`. I think that added, by default this file, could help.

chore(starter): add `.npmrc`

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/config.yml
scripts/bump-edge.ts
scripts/release-edge.sh

chore: update references to `nuxt/nuxt`

---

.gitignore
README.md
nitro.config.ts
package.json

This updates the nitro starter with a README and an empty configuration file, similarly to the Nuxt starter.

chore: update starter with readme and `nitro.config`

---

.github/ISSUE_TEMPLATE/bug-report.yml

chore: typo in bug report template

---

package.json
pnpm-lock.yaml
src/runtime/cache.ts

Upgrade to h3 1.8 RC to verify new changes 
https://github.com/unjs/h3/releases/tag/v1.8.0-rc.0

chore: upgrade to `h3@1.8-rc`

---

docs/content/1.guide/6.utils.md

docs: add about utils directory

---

src/presets/firebase.ts

chore(firebase): fix typos in warning message

---

src/presets/firebase.ts

fix(firebase): ignore `fsevent` dependency

---

src/cli/commands/build.ts

feat(cli): support `--preset` and `--minify`/`--no-minify` args for `build`

---

package.json
pnpm-lock.yaml
src/presets/deno-server.ts
test/presets/deno-server.test.ts
test/tests.ts

fix(deno-server): fix injections and enable back tests

---

src/scan.ts

A small typo seems to have crept in here.

fix: correctly mark `middleware: false` for scanned routes

---

src/build.ts

sorry, it's so tiny, but spotted when looking at https://github.com/nuxt/nuxt/issues/19425.

chore: tiny internal typo

---

src/cli/commands/dev.ts
src/runtime/static.ts

The notes seem to have been written backwards.

chore: fix code comments

---

src/cli/index.ts
src/presets/netlify.ts
src/rollup/config.ts
src/runtime/entries/nitro-dev.ts

- Use default export of package.json to make local dev working
- Using numeric port for worker and avoid unix socket path (/cc @paperdave seems a bug in bun for both)

fix: bun dev compatibility

---

docs/content/2.deploy/providers/cloudflare.md

docs(cloudflare): fix wording

---

docs/package.json
docs/pnpm-lock.yaml

docs: update lock file

---

docs/content/3.config.md

N/A
Just a small typo in the configuration documentation

docs: typo in word "legacy" in Configuration docs

---

src/build.ts

fix: watch plugins directory

---

src/runtime/cache.ts

I never know if it's in seconds or in ms so I ask a comment.

chore: add jsdoc for `cache.maxAge`

---

docs/content/2.deploy/10.runtimes/bun.md
docs/content/2.deploy/20.providers/firebase.md

closes https://github.com/unjs/nitro/issues/1901

docs: update edge links to nightly

---

docs/content/2.deploy/10.runtimes/deno.md
docs/content/2.deploy/20.providers/deno-deploy.md
docs/content/2.deploy/20.providers/deno.md

docs(deploy): add deno to runtime list

---

docs/content/2.deploy/20.providers/cloudflare.md

Update the deprecated wrangler repo link

docs(cloudflare): updatge wrangler link

---

docs/content/2.deploy/20.providers/aws-amplify.md

Remove partial region list for Amplify.

docs(aws-amplify): update regions

---

src/presets/aws-amplify.ts

When `static` flag is true (`nuxt generate`) preset should only output public assets.

feat(aws-amplify): support static builds

---

docs/content/2.deploy/20.providers/aws-amplify.md

docs(aws-amplify): add SSR logging step and remove experimental

---

docs/content/2.deploy/20.providers/aws-amplify.md

docs(aws-amplify): remove extra config banner

---

src/prerender.ts
test/fixture/routes/prerender.ts

fix(prerender): filter encoded links starting with `#`

---

build.config.ts

Improve internal nitro's `dist` directory to make debugging easier.

build: better dist chunk names

---

package.json
pnpm-lock.yaml
test/presets/azure.test.ts

Currently 22 fail and 14 pass 
```
TEST_AZURE=1 pnpm vitest test/presets/azure.test.ts
```

test: enable azure tests behind a flag

---

test/tests.ts

previously we write only checking lambda edge cases

test: enable binary response test for all presets

---

docs/content/1.guide/3.routing.md

docs: update the routing page

---

docs/content/1.guide/5.cache.md

docs: update the cache page

---

docs/content/1.guide/5.cache.md

docs: close code-group in cache section

---

docs/content/1.guide/6.fetch.md

docs: fix icon of fetch page

---

docs/content/1.guide/5.cache.md

N/A
Fixes typo with the function name in the example code.

docs: fix typo in defineCachedFunction example

---

docs/content/3.config.md

docs: clarify difference between dir and baseURL

---

docs/1.guide/0.index.md

- [ x] 📖 Documentation (updates to the documentation, readme, or JSdoc annotations)

docs(index): fix utils link

---

docs/1.guide/10.tasks.md
package.json
pnpm-lock.yaml
src/deps.ts
src/nitro.ts
src/rollup/config.ts
src/runtime/entries/bun.ts
src/runtime/entries/cloudflare-module.ts
src/runtime/entries/cloudflare-pages.ts
src/runtime/entries/deno-server.ts
src/runtime/entries/nitro-dev.ts
src/runtime/entries/node-server.ts
src/runtime/entries/node.ts
src/runtime/task.ts
src/runtime/virtual/tasks.ts
src/types/global.ts
src/types/nitro.ts
test/fixture/nitro.config.ts
test/fixture/tasks/test.ts

- fix(tasks): run only once at the same time
- feat: experimental scheduled tasks
#1974

feat: experimental scheduled tasks

---

docs/2.deploy/20.providers/vercel.md

#1770
Monorepo information. If I had this info, I wouldn't have spent hours to get it working. So someone else might benefit from this.
This could close the issue, but repo owner should probably decide.

docs: add monorepo info for Vercel

---

docs/1.guide/1.utils.md

Just fixing typo.
Fix typo in link.

docs: fix link to H3 utils

---

docs/1.guide/5.database.md

docs: fix db config

---

docs/1.guide/3.websocket.md

Hi @pi0,
Up to you just though would be a good place to reference this - always helps to see an example when learning (could save you a few issues 🙈)

docs: add websocket chat demo to websocket api page

---

docs/1.guide/10.tasks.md

docs: fix typo in tasks.md

---

docs/1.guide/5.database.md

docs: typo in 5.database.md

---

test/presets/cloudflare-pages.test.ts

/cc @dario-piotrowicz seems a recent regression with Miniflare or probably just an increased timeout (which is interesting) we need to investigate only pinging to keep you in the loop.

ci: skip `cloudflare-pages` test for windows

---

docs/1.guide/7.fetch.md

docs: fix typo in guide fetch.md

---

docs/2.deploy/0.index.md

Fixing a typo in the file.
Typo fix: wby -> by

docs: Typo fix 0.index.md

---

docs/2.deploy/0.index.md

docs: spelling typo

---

src/types/nitro.ts

docs: update documentation URL for experimental database feature

---

.github/PULL_REQUEST_TEMPLATE.md

chore: improve notes in pr template

---

docs/1.guide/3.websocket.md

docs: fix wording

---

src/rollup/plugins/import-meta.ts
src/rollup/plugins/raw.ts
test/fixture/routes/assets/import.ts
test/fixture/routes/assets/md.ts
test/tests.ts

This PR fixes limitation of importing `raw:` files with relative paths. 
Also adds fix for `_import_meta_url_ is not defined` error related to raw plugin (it requests no replace)

fix(raw): allow importing relative paths

---

src/presets/netlify.ts

fix(netlify-edge): write `_headers` and `_redirects`

---

src/build.ts
src/presets/deno-server.ts

HI :wave: I found out that there's an unused import while debuggin nitro

chore: remove unused import

---

package.json

resolves #2277 also relevant to #2305
a current limitation of mkdist requires src to have explicit .mts and we were wrongly pointing `types` to nonexistent files.

build: fix type exports field for `nitropack/runtime`

---

package.json
runtime.d.ts
src/rollup/config.ts

resolves #2305
also related to #2232
Allows importing nitro utils from `nitropack/runtime`
**Note:** This is not an official solution yet and behavior can change. Use at your own risk!

fix: allow importing utils from `nitropack/runtime`

---

docs/3.config/0.index.md

docs: remove outdated nightly warning

---

package.json
pnpm-lock.yaml
src/presets/cloudflare-pages.ts
src/types/presets/cloudflare.ts
src/types/presets/cloudflare.wrangler.ts
test/fixture/nitro.config.ts
test/fixture/wrangler.toml

Read `wrangler.toml` from user root dir (or custom path defined in `cloudflare.wrangler.`configPath`) and merges it with `cloudflare.wrangler` nitro options (user `wrangler.toml` has higher priority) and write it to `dist/wrangler.toml` for cloudflare pages preset.

feat(cloudflare-pages): generate `wrangler.toml`

---

src/presets/iis.ts

Closes #2350
deep merge use ```defu```

fix(iis): deep merge configs

---

docs/1.guide/6.cache.md

Fixed a few typos & rephrased some sentences for clarity on the caching page.

docs(caching): fix typos and rephrase for clarity

---

docs/1.guide/3.websocket.md

none
I think `api` is superfluous here.

docs(websocket): correct sse url

---

docs/2.deploy/10.runtimes/1.node.md

docs(node): fix `node-listener` example

---

src/presets/netlify/utils.ts

#2426
Fixes 500 error after bundling netlify preset

fix(netlify): added missing quotes in utils

---

docs/3.config/0.index.md

There was a typo (the letter "F" was different).
autoSubFolderIndex → autoSubfolderIndex

docs: fix typo autoSubFolderIndex → autoSubfolderIndex

---

docs/1.guide/9.plugins.md

N/A
Fixes dead link in documentation of runtime hooks

docs: update link to runtime hook source code

---

examples/renderer/api/hello.ts
examples/renderer/nitro.config.ts
examples/renderer/package.json
examples/renderer/renderer.ts
examples/renderer/tsconfig.json
pnpm-lock.yaml
src/presets/_types.gen.ts
src/runtime/internal/renderer.ts

fix(renderer): check full path for `/favicon.ico` placeholder

---

docs/1.guide/98.typescript.md
docs/1.guide/99.nightly.md

docs: tiny typo

---

docs/1.guide/3.websocket.md

Server-Sent Events is written with hyphens (`-`) everywhere. I think `Server-Sent Events` is the right format with hyphens.
https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events
https://en.wikipedia.org/wiki/Server-sent_events

docs: fix tiny typo

---

docs/2.deploy/20.providers/cloudflare.md

docs(cloudflare): add missing `await`

---

docs/1.guide/4.storage.md

I think `in-memory` should be with hyphen(-). 
https://aws.amazon.com/nosql/in-memory/

docs(storage): fix typo

---

docs/2.deploy/20.providers/cloudflare.md

- Fixes incorrect MDC syntax was preventing the following paragraph from displaying.
- Fixes Nitro preset name (`cloudflare` => `cloudflare_module`)
- Fixes formatting on the `Cloudflare` page (see below). 
> [!Note]
> It appears that `undocs` (or something in the docs site config) is not properly transforming ordered lists defined in markdown, so I just switched to a bulleted list. Probably needs to be addressed at the source.
---
---
---

docs: fix mdc component usage and cloudflare preset reference

---

docs/1.guide/3.websocket.md

docs: fix grammar

---

docs/1.guide/2.routing.md

docs(server routes): fix typo

---

docs/1.guide/1.utils.md

I think this is the correct link of the source code for list of available Nitro auto imports.

docs(utils): update github link

---

docs/3.config/0.index.md

the log level url for `consola` is fixed.

docs(config): fix url for log level

---

docs/3.config/0.index.md

docs(config): fix typos

---

src/runtime/internal/utils.ts

This prints the stack trace for errors that occur when prerendering.
Related: https://github.com/nuxt/nuxt/pull/28895

fix(prerender): log error stack traces

---

docs/1.guide/6.cache.md

docs(cache): fix code format

---

src/core/build/prepare.ts

refactor: remove `fs-extra` dependency

---

docs/3.config/0.index.md

Should by `retry` instead of `retries` as per config: https://github.com/unjs/nitro/blob/05aa182e861271fc315a932ae052ace4d344f89d/src/core/config/defaults.ts#L67

docs(config): fix typo prerender retries -> retry

---

docs/3.config/0.index.md

The feature is no longer limited to the nightly channel, as the documentation suggests

docs: `/_nitro/scalar` general availability

---

docs/3.config/0.index.md

Just moved to the nightly channel, and so did the endpoints 😂

docs: notice for OpenAPI paths changing in future versions

---

docs/1.guide/2.routing.md

Resolves a small word ordering issue in docs.

docs(routing): fix grammer

---

docs/1.guide/10.tasks.md

docs(tasks): fix grammar

---

examples/api-routes/api/test.post.ts

chore(examples): provide `event` in `defineEventHandler` function

---

src/runtime/internal/error.ts

https://github.com/unjs/nitro/issues/2447
Added a header for 404 errors

fix(error): add `cache-control: no-cache` for 404 responses

---

docs/1.guide/98.typescript.md

docs(typescript): tiny typos

---

docs/1.guide/2.routing.md

`e.g.` is the correct form for `for example`.

docs(server-routes): typo

---

package.json
pnpm-lock.yaml

#1157
After migrating to `citty`, did not remove the dependency. It is not used anywhere

chore: remove unused `mri` dependency

---

docs/1.guide/9.plugins.md

I think this (https://github.com/unjs/nitro/blob/v2/src/core/index.ts#L75) would be the correct link for nitro runtime hooks in source code.

docs: fix nitro runtime hooks link

---

docs/2.deploy/20.providers/cloudflare.md

With Cloudflare Workers Static Assets, we only need to bind `ASSETS` and don't need to configure `bucket` anymore.Also, a link at Cloudflare Service Workers part has an unnecessary `/`, making the server return 404 to visitor.
This PR resolves these problems.

docs(cloudflare): update `cloudflare-module`

---

docs/2.deploy/20.providers/cloudflare.md

docs(cloudflare): fix typo

---

docs/3.config/0.index.md

docs(config): tiny typos

---

docs/3.config/0.index.md

Update the existing OpenAPI endpoint documentation and provide detailed instructions on how to customize the endpoints using configuration options.
Fix incorrect OpenAPI endpoints.
Please see issue #2867

docs(config): update `openAPI` section

---

docs/1.guide/9.plugins.md

docs(plugins): tiny typo

---

docs/3.config/0.index.md

#2910 
`compatibilityDate` must be configured in Nitro project. However, it isn't configured in a fresh Nitro project by default, and wasn't described in documents.
This PR adds description of `compatibilityDate`.

docs(config): add `compatibilityDate` option

---

docs/3.config/0.index.md

This PR was encouraged in a comment https://github.com/nitrojs/nitro/pull/2570#issuecomment-2544033352
im not sure on the formulation or grammar as im not a english speaker, feel free to correct me

docs(config): document `openAPI.production` option

---

docs/1.guide/7.fetch.md

docs(fetch): provide comma for clarity

---

src/core/dev-server/server.ts

resolves #2881 (reverts #2713)
I have made more generic discussion to followup: #2980 -- I think next step would be splitting dev and prod error pages so we can at least add banner

fix(dev): avoid rewrite with baseURL

---

docs/3.config/0.index.md

docs(config): capitalize text

---

src/core/nitro.ts

fix https://github.com/nitrojs/nitro/issues/3015
Hello :wave: 
This PR fix modules autoimports not being typed.  It just run modules before creating unimport. 
This shouldn't cause any issue as `nitro.unimport` is typed as maybe undefined

fix: run modules before `createUnimport`

---

docs/1.guide/2.routing.md

I fixed a small typo error in the docs.

docs: fix typos

---

docs/1.guide/0.index.md

I only adjusted the grammar in a docs file.

docs: fix grammer

---

src/runtime/internal/utils.env.ts

Reference: https://github.com/nuxt/nuxt/issues/30263
The current Regex for env expansion feature is vulnerable according to [Devina ReDos checker](https://devina.io/redos-checker).
This Enhancement makes the Regex safe with keeping functionality.

refactor: improve env expand regex

---

src/core/config/defaults.ts

feat: enable `strict: true` for typescript defaults

---

.github/workflows/autofix.yml
.github/workflows/ci.yml

https://github.com/nodejs/corepack/pull/614
https://github.com/actions/setup-node/issues/1222

ci: workaround corepack issue with actions

---

examples/graceful-shutdown/plugins/db.ts

chore: fix grammar in comments

---

docs/2.deploy/20.providers/cloudflare.md

remove wrangler.toml cloudflare pages note, cloudflare pages supports wrangler.toml

docs(cloudflare): remove note about pages and `wrangler.toml` support

---

package.json
pnpm-lock.yaml
src/core/config/resolvers/fetch.ts

chore: update unenv v2 to rc8

---

test/fixture/api/storage/dev.dev.ts
test/presets/nitro-dev.test.ts
test/tests.ts

dev test was listing all keys in src dir of test (which at same time could be updated and cause flaky results) (guessing)

test: update dev test

---

src/rollup/config.ts
src/rollup/plugins/externals.ts

Context: Currently if any of nitro internal dependencies like `h3` or `youch` (used for dev server errors) has a different major version hoisted to user project, nitro can fail. Inspection root cause of this issue, it is because externals plugin (which nitro used in both dev and production to trace externals) does always prefers user project root. 
This PR fixes externals plugins to respect importer location first to resolve dependencies (just as a runtime behavior is expected with addition to fallbacks).

fix(externals): respect importer path for resolving

---

docs/2.deploy/20.providers/vercel.md

More on Fluid here: https://vercel.com/blog/introducing-fluid-compute
More on KV -> Marketplace here:

docs(vercel): update docs

---

src/presets/cloudflare/utils.ts

wrangler supports `wrangler.jsonc` as well (used to infer compatibility flags for cloudflare presets)

 fix(cloudflare): support wrangler.jsonc

---

docs/2.deploy/0.index.md

#3051 
Resolves #3051 (if problem still exists 🤔)

docs(deploy): add warning about turborepo and zero config

---

src/core/build/dev.ts

Resolves #3180 
Resolves #3180

refactor: remove extra space in logs

---

docs/2.deploy/20.providers/vercel.md

-----
<a href="https://stackblitz.com/~/github.com/iiio2/nitro/tree/docs(vercel)/typo"><img src="https://developer.stackblitz.com/img/review_pr_small.svg" alt="Review PR in StackBlitz" align="left" width="103" height="20"></a> _Submitted with [StackBlitz](https://stackblitz.com/~/github.com/iiio2/nitro/tree/docs(vercel)/typo)._

docs(vercel): typo

---

docs/1.guide/7.fetch.md

docs(fetch): fix grammar 

---

docs/2.deploy/10.runtimes/deno.md

Add upgrading Deno version and `compatibilityDate` set tip for enabling Node.js compatibility.

docs(deno-server): add `compatibilityDate` note

---

docs/2.deploy/20.providers/netlify.md

Add `compatibilityDate` tip (for enabling Netlify Functions 2.0) for `netlify` preset.

docs(netlify): add `compatibilityDate` note

---

README.md
docs/1.guide/0.index.md
docs/1.guide/00.migration.md

Add initial migration gude docs for v2 => v3

docs: init migration guide

---

src/core/build/types.ts
src/core/config/defaults.ts

2 pr v3 in main didn't come, interestingly.

feat: enable `allowImportingTsExtensions` and `strict` ts flags

---

docs/1.guide/6.cache.md

Just fixing the layout on https://nitro.build/guide/cache

docs: Updated callout on cache page

---

src/runtime/internal/hash.ts

non bug-fix followup to #3225
fixing init order of lhash utils

refactor: update internal hash utils order

---

src/types/_utils.ts
src/types/config.ts

Sometimes the types don't show up, which makes for better type matching. [Nuxt](https://github.com/nuxt/nuxt/blob/0a7602f36d5cd1eb55b8051e667014d63a7cbb21/packages/nuxt/src/app/config.ts#L9) uses similar.

refactor: improve DeepPartial type definition

---

src/runtime/internal/routes/openapi.ts
src/types/handler.ts

This change enables the use of custom attributes, such as `x-tagGroups`, within the OpenAPI `$globals` section. This is particularly useful for tools like [[Scalar](https://github.com/scalar/scalar/discussions/1016)](https://github.com/scalar/scalar/discussions/1016), where `x-tagGroups` allows for better organization of tags into logical groups, improving readability and navigation.

refactor(openapi): allow extensible `x-` properties in `$globals`

---

src/config/resolvers/unenv.ts

https://github.com/nitrojs/nitro/issues/3271
https://github.com/nitrojs/nitro/issues/3271
As discussed, resolves #3271

fix: add unenv aliases for `process/` and `string_decoder/`

---

vitest.config.ts

related https://github.com/nitrojs/nitro/pull/3281
`types` was still included in the coverage aggregate. These are noise and should be excluded.

test: exclude `src/types/**/*.ts` from coverage

---

docs/3.config/0.index.md

docs(config): capitalize acronym

---

docs/1.guide/5.database.md

docs(database): update default db location

---

docs/2.deploy/20.providers/azure.md

The command in the Azure preset doc is missing the `run` part before build.

docs(azure): build command missing `run`

---

src/rollup/plugins/dynamic-require.ts

This updates the regexp used for detecting webpack dynamic imports - example diff below:
```diff
- import("./" + __webpack_require__.u(chunkId)).then
+ import(__webpack_require__.p + "./" + __webpack_require__.u(chunkId)).then
```
this is done in a backwards-compatible way and mirrors [the change made in Nuxt](https://github.com/nuxt/nuxt/commit/62e700daaf6f41571c0357fd054ca32cb2b7a047).

fix(dynamic-require): update regexp for new webpack import pattern

---

src/presets/aws-lambda/runtime/aws-lambda-streaming.ts

#3345 
```ts
return new Response(null, {
status: 302,
headers: {
location: "/",
},
});
```
`null` as the response body leads to `r.body` being `undefined` in the handler
This caused the existing code to never resolve, resulting in a socket hangup when the lambda's timeout lapses.

fix(aws-lambda-streaming): handle undefined response body

---

src/core/nitro.ts

#3289 
Backport [f038b04](https://github.com/nitrojs/nitro/commit/f038b0421aa52219c852e6847834e19e1c87c398) to v2

fix: scan handlers when initialising nitro (#2546)

---

CHANGELOG.md
docs/1.guide/0.index.md
docs/1.guide/1.utils.md
docs/1.guide/2.routing.md
docs/1.guide/3.websocket.md
docs/1.guide/6.cache.md
docs/3.config/0.index.md

chore: move links to h3 new org

---

docs/3.config/0.index.md

Adds a description of the `workspaceDir` config option to the docs, as discussed in https://github.com/nitrojs/nitro/issues/3337. I chose not to add `rootDir`, because there's some discussion about removing it as a config option in https://github.com/nitrojs/nitro/pull/3344.

docs: add `workspaceDir` config option

---

docs/1.guide/5.database.md

Postgresql configuration error in nitro.config.ts

docs(database): fix example

---

src/build/vite/plugin.ts

In [nitrojs/vite-examples](https://github.com/nitrojs/vite-examples), it appears impossible to detect the client environment consumer, resulting in failure to generate the correct `globalThis.__VITE_MANIFEST__`. I'm uncertain whether this is an issue with Vite itself; this is a simple patch solution.

fix(vite): set default consumer to "client" in client environment

---

scripts/gen-presets.ts
src/presets/_types.gen.ts
src/presets/aws-lambda/preset.ts
src/presets/cloudflare/dev.ts
src/presets/cloudflare/preset.ts

resolves nuxt/nuxt#32645
regression from #3389
this PR also updates generated types to be more precise for vendor namespaces.

fix(cloudflare, aws-lambda): optional access to options

---

src/presets/cloudflare/utils.ts

Making sure the auto generated Cloudflare worker name is lowercased

fix(cloudflare): lowercase auto generated worker name

---

src/core/dev-server/vfs.ts

https://github.com/nitrojs/nitro/pull/3527
fix https://github.com/nuxt/cli/issues/1003
This PR tries to fix the access to /_vfs through unix socket. I haven't found better alternatives, aside from `event.node.req.client.server._connectionKey` but this is internal to nodejs

fix: allow accessing vfs through unix socket

---

docs/1.guide/97.configuration.md
docs/2.deploy/20.providers/cloudflare.md
src/config/loader.ts

> [!NOTE]
We add `.env` and `.env.local` as default in case of fallback and only in dev.
Close #3486

feat(dev): support `.env.local`

---

CONTRIBUTING.md
docs/2.deploy/20.providers/deno-deploy.md

chore: fix `GitHub` casing

---

src/build/vite/plugin.ts

https://github.com/nitrojs/nitro/issues/3551
As Vite doesn't support importing a path that starts with "#" from a virtual file when the package.json imports field is set. We should pre the #nitro-internal-virtual handler to avoid Vite's inner plugin (vite:import-analysis) handling that first.
reproduction: https://stackblitz.com/edit/vitejs-vite-ckpgd5rk?file=package.json

fix(vite): enforce hooks as pre
