nitrojs/nitro

src/presets/azure.ts
src/presets/firebase.ts

This is now how we take advantage of the new Node runtimes with Azure SWA: https://docs.microsoft.com/en-us/azure/static-web-apps/configuration#platform

fix: update azure SWA preset and update node versions detection

---

src/presets/nitro-dev.ts
src/presets/nitro-prerender.ts
src/rollup/config.ts

resolves https://github.com/nuxt/framework/issues/4232
The fix applied to dev preset also needs to be applied to prerender preset. It seemed easiest way was to extract from options and add to preset itself. There may be a better way to do this.

fix: normalize `#build` windows path for dev and prerender presets

---

src/runtime/config.ts

Currently it isn't possible to set nested config, which is something needed in frameworks like Nuxt.
See for example https://github.com/nuxt/framework/issues/4126#issuecomment-1094127476 - currently we are not able to override anything but top-level `publicRuntimeConfig`.

feat: allow overriding nested runtime config

---

src/options.ts
src/rollup/config.ts
src/runtime/app.ts
tsconfig.json

Previously it was impossible to override sub-paths (for example, `#nitro/error`) as `#nitro` was added first to the alias object.
~Do not yet merge as there is an error that this reveals in Nuxt that needs to be resolved first:~ resolved in https://github.com/nuxt/framework/pull/4215

fix: allow users to override nitro error

---

src/options.ts
src/rollup/config.ts
src/rollup/plugins/esbuild.ts

We should likely respect `nitro.options.sourceMap` as default value for `esbuild` as well.
Related: https://github.com/nuxt/framework/pull/4509

fix: respect `sourceMap` option

---

src/prerender.ts
src/rollup/config.ts

https://github.com/nuxt/framework/issues/4330
This fixes a bug, when a fresh install of nuxt3 on Windows can not produce a build. It is failing with an error related to files paths. It seems like all dynamic imports should be wrapped with `pathToFileURL` to work properly on Windows.
Also fixed a minor bug with configuration. Cloudflare test failed on Windows.

fix: wrap dynamic import in prerender to fix windows build failure

---

src/runtime/virtual/server-handlers.d.ts
src/scan.ts

https://github.com/nuxt/framework/issues/4609
This adds `patch` to scanning regex, and also uses upstream h3 types for methods (rather than keep in two places).
Related: https://github.com/unjs/h3/pull/88

fix: support patch method auto-scanning

---

src/rollup/config.ts

previous PR: https://github.com/nuxt/framework/pull/3107
https://github.com/nuxt/framework/issues/4547
The following code was being replaced:
```diff
const addRouteMiddleware = (name, middleware, options = {}) => {
const nuxtApp = useNuxtApp();
if (options.global || typeof name === "function") {
-     nuxtApp._middleware.global.push(typeof name === "function" ? name : middleware);
+     nuxtApp._middleware.globalThis.push(typeof name === "function" ? name : middleware);
} else {
nuxtApp._middleware.named[name] = middleware;
}
};
```

fix: replace `global.` in fewer instances

---

src/runtime/entries/aws-lambda.ts
src/runtime/entries/cloudflare.ts
tsconfig.json

https://github.com/nuxt/framework/issues/4744
CF headers were coming in as a Headers object; this normalizes it to the type expected elsewhere in Nitro using [Headers.entries()](https://developer.mozilla.org/en-US/docs/Web/API/Headers/entries).
I also normalise outgoing headers into the type expected by Response (an array of string/string) and tidy up a leftover internal type from `aws-lambda`.

fix(cloudflare): normalize incoming & outgoing headers

---

src/rollup/config.ts
src/rollup/plugins/esbuild.ts
src/types/nitro.ts

https://github.com/nuxt/framework/issues/4771
Context: https://github.com/nuxt/framework/issues/507
This sets esbuild target to currently minimum node version required for project, and removes the additional default set within the plugin.
https://esbuild.github.io/api/#target

refactor: improve `esbuild.target` option handling

---

docs/config/index.md
src/rollup/config.ts
src/types/nitro.ts

- add commonjs field to edit the commonjs plugin
https://github.com/nuxt/framework/pull/4762
https://github.com/nuxt/framework/issues/4661
Add the commonJs key to NitroOptions and assign by destructuring nitro.option.commonJs  when adding the @rollup/plugin-commonjs.
Would improve the linked PR by avoiding replacing the commonJS plugin at build. The commonJS dynamicRequireTargets declaration would be directly into nitro/nuxt config

feat: allow edit of commonJs plugin params

---

src/build.ts

fix #204
the generated tsconfig.json file in .nitro/types is missing "include path" of "../../**/*", causing typescript unable to grab all global types defined in .nitro/types/nitro.d.ts.  adding "../../**/*" to tsConfig.include array in nitro\src\build.ts should fix this issue.

fix: add missing include path `../../**/*` in generate tsconfig.json

---

docs/deploy/providers/digitalocean.md

Fixes a typo in the deployment preset name to avoid confusion. Correct preset name for DigitalOcean appears to be `digital-ocean` as seen in the preset filename (compare https://github.com/unjs/nitro/tree/main/src/presets)

docs: fix typo

---

src/types/fetch.ts

Enhance the $fetch request's type by inferring the server route's string literal (InternalApi interface). supporting auto-complete and showing type hints.
resolves #208
Add a new type `NitroFetchRequest` to Enhance `$fetch`'s request type by inferring the generated server route's string literal (InternalApi interface).
This will provide better DX and prevent typos while $fetch by supporting auto-complete and showing type hints when entering the request. And should still be able to pass other valid request URLs like https://example.com/api or Request object like new Request('/api/test')
This will also provide Nuxt 3's `useFetch` and `useLazyFetch` to also have type hints on request parameters with little type changes. see issue nuxt/framework#4823 and PR nuxt/framework#4825
```ts
// assume …
```

feat: add `NitroFetchRequest` type and enhance $fetch's request type

---

src/prerender.ts
src/types/nitro.ts

Add a new hook `prerender:route` that is called when a single page has been successfully prerendered.
This hook can be used externally to create specific logic tied to route generation, such as editing output of a route.
`generateRoute` now returns `{ contents, route, filePath }` instead of nothing, in order to:
- Access the saved file directly by its `filePath`.
- Read the `contents` that have been generated.
I can see more potential for SSG (fully static).
A quick example usage could be to dynamically download and replace static assets, stored on an API server, that you don't want to use in production (parse HTML content, download image, replace image path with the one downloaded locally).
Please, let me know if this change is not intended for nitro.

feat: add prerender:route hook

---

playground/tsconfig.json

fix #227 
In local dev env, playground's $fetch's `InteralApi` type in `nitropack` is not merge with `InternalApi` in `.nitro/types/nitro.d.ts`, causing API response types and request type `NitroFetchRequest` unable to infer from extracted keys from `InternalApi` interface.
```ts
declare module 'nitropack' {
type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
interface InternalApi {
'/post': Awaited<ReturnType<typeof import('../../routes/post').default>>
}
}
```
This can be fix by adding `paths` config to `tsconifg.json in playground as:
```diff
"extends": "./.nitro/types/tsconfig.json",
+  "compilerOptions": {
+   "paths": {
+     "nitropack": [
+       "../src/index"
+     ],
+     "#internal/nitro": [
+       "../src/runtime/index"
+     ],
+     "#internal/nitro/*": [
+ …
```

fix: add missing `paths` config in `playgound/tsconfig.json`

---

src/types/fetch.ts

fix #225
As mention in [PR comment](https://github.com/nuxt/framework/pull/4825#pullrequestreview-963821946), with the new `NitroFetchRequest` type for request (added in #209), user currently can't do:
```ts
const someDynamicUrl: string = 'https://test.com'
$fetch(someDynamicUrl) // Error: Argument of type 'string' is not assignable to parameter of type 'NitroFetchRequest'
```
This can be fix by adding `string & {}`  to `NitroFetchRequest` in `types.fetch.ts` as:
```ts
type NitroFetchRequest = keyof InternalApi | Exclude<FetchRequest, string> | string & {}
```
the only small downside is losing type hint when quotes are already typed,
```ts
$fetch( /** cursor here */ ) // shows routes hints
$fetch('/** cursor here */') // won't show hints, might have to tap into typescript hints using …
```

fix(types): update `NitroFetchRequest` type to support `string` type

---

src/types/fetch.ts

fix #231
type `NitroFetchRequest` should exclude all `/_*` and `/api/_*` routes as they are for internal use and should not show type hints/auto-complete to end users.

fix: exclude internal `/_*`, `/api/_*` routes from NitroFetchReqeust type

---

package.json
pnpm-lock.yaml
src/options.ts
src/types/nitro.ts

https://github.com/nuxt/framework/pull/5042#issuecomment-1152357425
This fixes the type of autoImport options in nitro and adds scanDirs to autoImport.include.

fix: add scanDirs to auto-import include

---

src/runtime/cache.ts

https://github.com/nuxt/framework/issues/5328
Resolves https://github.com/nuxt/framework/issues/5328
When cache is expired and multiple request come in at the same time, 1st request is pending at the handler, then 2nd request will reuse invalid response from previous expired value and 404 response may be returned.
This pr is fixing the invalid cached response by removing previous response value before handler is called.

fix(cache): invalidate entry before calling resolver

---

src/rollup/config.ts

resolves https://github.com/nuxt/framework/issues/4555, resolves 
When prerendering, we don't want to use the source `dist/server` file, which still references virtual modules and other aliases. Instead, we want to inline it.

fix: don't use file url when building prerenderer

---

src/prerender.ts

resolves https://github.com/nuxt/content/issues/1252
When following links with a baseURL set, we were following them directly, resulting in double-prefix of baseURL.

fix(prerender): avoid adding duplicate baseURL for local fetch

---

src/rollup/plugins/public-assets.ts

Prevent passing assets request into service worker. Service-Worker tries to response requests like `entry.*.css`which is a public asset and generated in build.
These URLs should treat as public assets, They should not handle by service worker.

fix(isPublicAssetURL): assets should treat as public

---

src/runtime/entries/azure.ts

resolves https://github.com/nuxt/content/issues/1299
Pass search parameters to Nitro local call. 
In the current state, Nitro handlers will not receive query parameters in Azure deployment.

fix(azure): pass query params to local call

---

src/types/nitro.ts

There was no way to disable auto-import as we were adding object default.

fix(types): allow `autoImport` option to be false

---

src/build.ts

https://github.com/nuxt/content/pull/1346#issuecomment-1180431720
Likely in `rollup:before` users might want to modify nitro options with effect of changing rollup config. For example:
https://github.com/nuxt/framework/blob/f321a56e63be508e5f478b1de5227a5add2b977f/packages/nuxt/src/core/nitro.ts#L124-L134
This makes that possible.

fix: call `rollup:before` before generating rollup config

---

src/options.ts

Fixes #246
Closes #238 
This enables `dotenv` setup feature from `c12` in development (`nitro dev` only), making `.env` files working out of the box.

fix(config): enable dotenv in development

---

src/options.ts

https://github.com/nuxt/framework/pull/5981, https://github.com/nuxt/bridge/issues/421
This disables processing the build output of the previous step from auto-imports. Credit to @cinob for spotting the issue; this just moves the fix up to Nitro if we think that makes sense.
cc: @antfu

fix(options): exclude `buildDir` for auto-imports

---

src/rollup/plugins/public-assets.ts

https://github.com/nuxt/framework/issues/4977
It's common to need static files served on `.` prefixed paths, e.g. `.well-known`.
Currently we were ignoring them when scanning.

fix: include dotfiles in public assets

---

src/presets/base-worker.ts

iife inlined all dynamic imports but name tag is not preserved so it is not recognized by vue defineAsyncComponent correctly as an esmodule for all dynamic chunks such as pages / layouts.
Enabling the rollup option fixes the issue.
https://github.com/nuxt/framework/issues/5996

fix(worker): preserve esmodule symbol for dynamic imports

---

src/utils/index.ts

resolves https://github.com/unjs/nitro/issues/378, see also https://github.com/unjs/unenv/pull/45
A couple of issues have come up recently about alias ordering. This PR applies a fix to order aliases by specificity (e.g. number of slashes) meaning we should always have more specific alias in front of general (`fs/promises` in front of `fs`).
The upstream PR to unenv resolves it more specifically within the unenv presets but this is still worth merging here as there are other potential aliases involved.

fix: sort aliases to ensure priority is given to more specific aliases

---

src/imports.ts
src/options.ts

Use new `mlly.resolveModuleExportNames` to resolve all available exports from installed h3 package and register them as auto imports.
/cc @antfu Can we add this as a built-in unimport functionality as a preset type for auto resolving a package with filter?

feat: add h3 auto imports preset

---

docs/deploy/providers/vercel.md

docs(vercel): small typo

---

src/presets/netlify.ts

Emit `server.js` CJS wrapper for netlify output to avoid needing a rebuilt from netlify and leverage native ESM.

feat(netlify): emit `server.js` to leverage native esm

---

docs/content/1.guide/1.introduction/4.storage.md

On [this page of the docs](https://nitro.unjs.io/guide/introduction/storage) there is a typo confusing nitro config with nuxt config.

docs: fix typo in storage docs

---

package.json
pnpm-lock.yaml

chore: remove unused `@types/jsdom` from dependencies

---

src/options.ts

resolves #434
moduleSideEffects was getting called both with full path to polyfill (including dist) and without. Without both paths in side effect list, we don't end up including side effects in the prerenderer build

fix: add resolved side-effect for node-fetch-native

---

src/runtime/entries/aws-lambda.ts

resolve #333 
Hi this PR aims to fix the `normalizeIncomingHeaders` function from the aws-lambda preset. Some of us might test the build through aws API Gateway service which don't send any headers by default (null). The changes are just making the `headers` param possibly undefined and send an empty object to `Object.entries` if `headers` is null or undefined

fix(aws-lambda): fix normalizeIncomingHeaders

---

docs/content/3.config/index.md
src/nitro.ts
src/options.ts
src/rollup/config.ts
src/types/nitro.ts
test/fixture/nitro.config.ts

https://github.com/nuxt/framework/pull/6864
See https://github.com/nuxt/framework/pull/6864

refactor!: rename options `autoImport` to `imports`

---

src/runtime/entries/aws-lambda.ts

resolves #245
This PR returns an array of cookies to set from aws-lambda preset rather than keeping them on the headers. More info in [AWS docs](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html#http-api-develop-integrations-lambda.v2).
@brtinney - would be grateful if you could confirm this resolves the issue for you.

fix(aws-lambda): return outgoing cookies on response objects

---

src/runtime/entries/aws-lambda.ts

resolve #396 
This PR aims to add the `multiValueQueryStringParameters` from APIGatewayProxyEvent. Currently the request only retrieve the queries from the `queryStringParameters`, this don't allow us to have an array of query like `/api?test=foo&test=bar&test=hello` (this return only the last query -> `{ test: 'hello' }`.

fix(aws-lambda): add `multiValueQueryStringParameters` to aws preset

---

package.json
pnpm-lock.yaml

Main breaking change of unenv 0.6.x is that body is returned as is without calling `.toString()` (which was probably pointless for h3 responses that are already stringified. only new condition is BodyInit and Buffer types could happen for presets and we need to handle.

fix!: update unenv to 0.6.x

---

docs/content/3.config/index.md
src/options.ts
src/rollup/plugins/public-assets.ts
src/runtime/static.ts
src/types/nitro.ts
test/fixture/nitro.config.ts

#69
This PR enables public (and pre-rendered) assets compression with opt-in flag `compressPublicAssets`.
When this flag is enabled, after copying all public assets and prerendering, public asset plugin creates compressed version of assets using gzip (`.gz`) and brotli (`.br`).
In runtime, the static asset handler checks the incoming request's `accept-encoding` header and if the browser supporting it, tries to search for the compressed assets in the manifest.
Because this feature does compression on build time, it works universally for all presets as long as they allow responding binary data and has zero overhead on runtime performance.

feat: opt-in option to compress public assets using `gzip` and `br`

---

src/rollup/config.ts
src/types/nitro.ts

I'm using nitro in Nuxt 3 and I found that the default options only work when the WASM file is smaller than the default inlining-threshold. Otherwise the Nuxt3 NodeJS server environment (and other server targets I'd imagine) chokes on the wasm plugin using `require()`calls (how dare them use `require` in NodeJS! :D). And even if that would be fixed upstream in the `@rollup/plugin-wasm` package, it's still nice to be able to change the default options here.

feat: allow specifying wasm plugin options

---

src/build.ts

https://github.com/nuxt/framework/issues/7198
In https://github.com/nuxt/framework/issues/7198, the error format is like so:
```js
const error = {
errno: -2,
code: "ENOENT",
syscall: "open",
path: "playground/.nuxt/dist/server/styles.mjs",
watchFiles: [
// ...
],
}
```

fix: include error path property and handle null locations

---

docs/content/3.config/index.md
src/rollup/plugins/public-assets.ts
src/types/nitro.ts

This PR allows specifying the compression algorithm in the `compressPublicAssets` option.
All public assets are no longer compressed, but only selected types are. Since some file types are already internally compressed and double compression is just a waste of time and energy.
The compression level has also been set to maximum quality, which makes compressed files smaller in size and therefore faster to download.

feat: improve  public asset compression

---

src/rollup/plugins/externals.ts

https://stackblitz.com/edit/github-c92aq5
When adding a cjs dependency via `traceInclude` it will have a `?commonjs-entry` query appended, which can't be resolved by vercel/nft. This strips this kind of query from force-included assets.

fix: strip query parameters from commonjs included externals

---

src/options.ts
src/presets/netlify.ts
src/presets/stormkit.ts
src/presets/vercel.ts
src/types/nitro.ts

resolves #149
This is an initial implementation of `workspaceDir` and migrating presets that have 'magic folders' (vercel, netlify + stormkit) to use this.

feat: add `workspaceDir` and use it for presets auto generated dir

---

src/presets/netlify.ts
src/presets/stormkit.ts
src/presets/vercel.ts

https://github.com/nuxt/framework/issues/7410
Confirmed with Vercel team - we need to output vercel build output in _project_ root directory.

fix: use `rootDir` for providers output instead of `workspaceDir`

---

src/runtime/static.ts

#7467
`/` can't be served via assets because it becomes `//index.html`, meaning we were totally skipping static `/` routes. In fact, we probably want to use `joinURL` so that the trailing slash status is not taken into account when joining with `index.html`.

fix: properly serve `/index.html` static asset

---

src/prerender.ts

Otherwise we get `//index.html` as the fileName.

fix(prerender): prevent double slash when joining url to `index.html`

---

.gitignore
src/prerender.ts
src/presets/azure.ts
src/presets/vercel.ts
src/types/nitro.ts
test/presets/vercel.test.ts

Current hybrid vercel deployments will always server-render prerendered HTML (though you can get the static html by adding `/index.html` to the URL). Vercel provides the `overrides` property to allow us to map clean URLs (without `.html` or `index.html` suffix) to static files: https://vercel.com/docs/build-output-api/v3#build-output-configuration/supported-properties/overrides. This PR implements that.
Might also be worth a consistent implementation of accessing which HTML files have been prerendered. (See [this line](https://github.com/unjs/nitropack/blob/ba39ffe9d5fe9516825ccbafd55c18211c78a424/src/presets/azure.ts#L66-L69) for how we were doing it in Azure - I could easily create a shared context that both presets could use - happy to pick this up.)

fix(vercel, azure): serve prerendered routes statically

---

src/presets/vercel.ts

Vercel needs an empty string as an output for the index; my mistake, I swapped `withoutLeadingSlash` instead of the previous regexp.

fix(vercel): always strip leading slash

---

docs/components/global/Ellipsis.vue

resolve https://github.com/unjs/nitro/issues/511, resolves https://github.com/unjs/nitro/issues/484
Hi this just fix the Ellipsis component preventing the users from clicking on the "Get started" and "Star on Github" buttons

docs: add pointer event none to Ellipsis component

---

src/types/fetch.ts

Not good English, sorry
I used $fetch.create when using $fetch of NuxT3, VScode threw me an error. After checking the error, I found that create was not defined in the type, so I added a create attribute to $fetch

fix(types): add `create` method to `$Fetch` interface

---

src/rollup/plugins/externals.ts

https://github.com/unjs/nitro/issues/508
This change adds a `name` and `version` field to the generated package.json for the `aws-lambda` preset.
When building and deploying code with AWS SAM, there's a validation step running on the package.json file, which requires `name` and `version` to be set.
Resolves #508 
Let me know if this requires a documentation update (I don't think so)

fix: add missing name and version fields to `.output/package.json`

---

src/options.ts
src/rollup/plugins/externals.ts
test/fixture/_/.gitignore
test/fixture/_/node_modules/nitro-dep-a/index.mjs
test/fixture/_/node_modules/nitro-dep-a/node_modules/nitro-lib/index.mjs
test/fixture/_/node_modules/nitro-dep-a/node_modules/nitro-lib/package.json
test/fixture/_/node_modules/nitro-dep-a/package.json
test/fixture/_/node_modules/nitro-dep-b/index.mjs
test/fixture/_/node_modules/nitro-dep-b/node_modules/nitro-lib/index.mjs
test/fixture/_/node_modules/nitro-dep-b/node_modules/nitro-lib/package.json
test/fixture/_/node_modules/nitro-dep-b/package.json
test/fixture/_/node_modules/nitro-lib/index.mjs
test/fixture/_/node_modules/nitro-lib/package.json
test/fixture/nitro.config.ts
test/fixture/routes/modules.ts
test/fixture/types.ts
test/tests.ts

resolves #503
resolves #456
resolves #161
Changes for externals handling (node targets):
- Resolve symlinks of traced files to properly dedup for pnpm
- Also show warning for major version changes with leading zero (0.1.0 => 0.2.0 and 0.0.1 => 0.0.2)
- Improve warning formatting and show it once
- Fix: **ignore entire directory of older version packages**
- Revert back windows fix for (#424) as we are now for sure writing files once.
- resolve `nodeModulesDirs` relative to rootDir
- Add tests

fix(externals): avoid overriding packages with version conflict

---

src/build.ts

Currently, generated auto-imports are relative to `#internal/nitro` which means they have no type safety unless `typescript.internalPaths` is set. This PR resolves them so we don't need to expose access to `#internal/nitro`.

fix: fully resolve internal paths for autoimports

---

src/rollup/plugins/externals.ts
src/utils/index.ts
test/unit/utils.test.ts

resolves #536
It seems that when multiple traced files in the same directory are copied on windows, in some circumstances, we have a race condition which causes a 'resource busy or locked' error. It's possible this is very much an edge case, such as when testing. But this change seems safe; it adds a small 2ms timeout and will retry a file up to 3 times, which will hopefully reduce any flakiness. I've [confirmed](https://github.com/nuxt/framework/pull/7927) (with `yarn patch`) that it does resolve the issue in framework repo.
(Another option would be synchronous file copying.)

fix: retry writing traced files if there are conflicts

---

docs/content/2.deploy/0.index.md

Stumbled over a broken link to the cloudflare-pages preset - attached PR fixes that.

docs: fix link to cloudflare-pages preset

---

src/rollup/plugins/externals.ts

Revert #529
Merging files from two completely different packages is not really a good idea!

revert: #529

---

src/options.ts
src/presets/netlify.ts
src/presets/vercel.ts
src/runtime/app.ts
src/runtime/cache.ts
src/runtime/route-options.ts
src/types/nitro.ts
test/presets/netlify.test.ts
test/presets/vercel.test.ts

Context: #538
By normalizing route options, we can support more shortcuts and also avoid duplicate logic per vendor for native support.
This PR normalizes 3 shortcuts:
- cors => converted to headers
- swr / static => converted to (new) cache options (rework of #443)
- [redirect is normalized]
Also fixes some issues with netlify and vercel generated rules

feat: normalize route options and shortcuts

---

src/types/utils.ts
test/fixture/tsconfig.json
test/fixture/types.ts

#518 
1. fix `MatchedRoutes` type in utils.ts for matching catchAll(glob) routes after updating fixture test tsconfig to `"strict":true`.
2. revert strict mode back to `false` for now until we solve other type errors in `src/`.
3. update type check logic for middleware route (`/`) by using `InternalApi` to infer all possible return types instead of manually defining each time after adding new API routes to the test fixture.

fix: api route type errors

---

src/runtime/entries/azure-functions.ts
src/runtime/entries/azure.ts

None
Azure functions with `httpTrigger` automatically JSON-parse the body. This is not explicitly mentioned in the docs (at least I couldn't find it), but in one of [the examples](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook-trigger?tabs=in-process%2Cfunctionsv2&pivots=programming-language-javascript#example) they use `req.body.name` showing that `req.body` is indeed an object. This then leads to problems when used with h3's `useRawBody` method, which actually returns the object instead of the stringy body when deployed to azure.
This is fixed by using `req.rawBody` in the azure handler. It's hard to find documentation on this property, but `rawBody` is used in an official test file:
https://github.com/Azure/azure-functions-host/blob/71ecbb2c30321 …

fix(azure): raw body no longer returns parsed json

---

src/options.ts

resolves https://github.com/unjs/nitro/issues/551
If we can't resolve workspaceDir, we should fallback to rootDir rather than erroring.

fix: default `workspaceDir` to `rootDir`

---

docs/content/3.config/index.md
src/dev/server.ts
src/options.ts
src/types/nitro.ts
test/fixture/nitro.config.ts

#113
Support full-featured development-only proxy using [node-http-proxy](https://github.com/http-party/node-http-proxy)
Proxy configuration for development server.
You can use this option to override development server routes and proxy-pass requests.
```js
{
devProxy: {
'/proxy/test': 'http://localhost:3001',
'/proxy/example': { target: 'https://example.com', changeOrigin: true }
}
}
```
See [https://github.com/http-party/node-http-proxy#options](https://github.com/http-party/node-http-proxy#options) for all available target options.

feat: `devProxy` support

---

src/prerender.ts
src/types/nitro.ts
test/fixture/nitro.config.ts

This PR adds a new `prerender?: boolean` route rule. It does two things:
- Adds any static (without **/*) route rule with `prerender: true` to the list of pre-rendered routes (<=> Almost same functionality as adding to `prerender.routes[]`)
- Skips any route matching a rule with `prerender: false` (<=> Almost same functionality as adding to `prerender.ignore` prefix array)
Prerender is still mainly usable with crawler being enabled. We can later support partial crawling or make a breaking change to only enable crawling for matching rules. Either way this is the starting point.

feat: support `prerender` route rule

---

src/runtime/entries/cloudflare-pages.ts
src/runtime/entries/cloudflare.ts

In cases where it is necessary to read the body of the raw request, the cloudflare deploy was always parsing the body even using `useRawBody`.
Implementations like the stripe's webhook that needs to read the raw body would break.

fix(cloudflare): pass raw body instead of parsing it

---

docs/content/1.guide/1.introduction/2.auto-imports.md

Current Typescript url to `/guide/introduction/typescript`  in [Auto Imports](https://nitro.unjs.io/guide/introduction/auto-imports) guide.

docs: fix url in auto-imports guide

---

docs/content/2.deploy/1.node.md

#719 
fix spelling of cluster [docs/content/deploy/node](https://nitro.unjs.io/deploy/node#cluster-mode)

docs: fix spelling of cluster

---

src/options.ts

https://github.com/nuxt/framework/issues/8461
https://github.com/Baroshem/nuxt-security/issues/42
We need to normalize plugins that are absolute paths (`C:\test\something`) to file URLs on windows before we generate the imports from them in `dev/index.mjs`.

fix: normalize nitro plugin paths to url in development

---

src/options.ts

https://github.com/danielroe/nuxt-turnstile/issues/85
Similar to https://github.com/unjs/nitro/pull/732, we should use file urls in dev mode for absolute auto-import paths. I'll rebase this once that merges, but thought I'd open this first so you're aware.

fix: use file urls for auto-imports in development

---

src/options.ts

apologies - a regression from https://github.com/unjs/nitro/pull/733 -  see https://stackblitz.com/edit/nuxt-starter-basw97 for a reproduction.

fix: initialise imports.imports

---

src/types/fetch.ts
test/fixture/types.ts

This allows passing either `POST` or `post` as an http method.

fix: accept both upper/lower-case methods

---

src/prerender.ts

When prerendering routes, we create a filesystem entry with directory structure corresponding to the route and serve then in production as static files.
Due to filesystem limitations ([see this table for reference](https://en.wikipedia.org/wiki/Comparison_of_file_systems#Limits)) filename (and directory names) can have maximum of 255 characters in most popular filesystem implementations while generally there is less limit (at least documented) limitation for the full path. 
This fixes nitro check to validate each segment length splitted by `/` instead of the whole path against 255 limit. Also adds a visible warning log when skipping routes due to filesystem limits.
APFS, at least also has a limitation on full path as well which is undocumented but causes `ENAMETOOLONG` error when while …

fix(prerender): check each segment length is less than 255 chars and whole path 1024

---

docs/content/3.config/index.md
src/compress.ts

https://github.com/nuxt/framework/discussions/9626
The code for `compressPublicAssets` was double-compressing all image types (including .jpg, .png, .gif, .webp, etc.) when it really should only be compressible static file types that are text-based. I updated the code to use the following list of MIME types, and also added it to the docs for `compressPublicAssets`:
text/html
text/css
text/plain
text/xml
text/x-component
text/javascript
application/x-javascript
application/javascript
application/json
application/manifest+json
application/vnd.api+json
application/xml
application/xhtml+xml
application/rss+xml
application/atom+xml
application/vnd.ms-fontobject
application/x-font-ttf
application/x-font-opentype
application/x-font-truetype
image/svg+xml
image/x-icon
image/vnd.microsoft.icon …

feat: include only compressible mime types

---

src/runtime/route-rules.ts

https://github.com/nuxt/framework/issues/9762
This PR removes baseURL before calculating route rules.

fix: remove base url before calculating route rules

---

src/presets/netlify.ts
src/presets/vercel.ts
test/presets/netlify.test.ts
test/presets/vercel.test.ts

This orders route rules within vercel + netlify presets so that (particularly glob) rules do not shadow rules below them. In addition, if the default vercel route rule is `/**: { static: true }` we don't also need to output a second, SSR rule.
cc: @antfu - if you clone this and checkout commit c7f8f39972b43a8ddb0b06d558b3b9f3b19f0a45, then run `vitest run -u` the test passes and the inline snapshots are not updated. I've also noticed some other weird issues like a different snapshot within a file being updated than the one it corresponds to (e.g. the next snapshot below).

fix(netlify, vercel): order route rules from most specific + avoid double-rendering root

---

docs/content/1.guide/1.introduction/0.getting-started.md
docs/content/1.guide/1.introduction/2.auto-imports.md
docs/content/1.guide/1.introduction/7.typescript.md
docs/content/2.deploy/providers/cloudflare.md
src/cli.ts

feat(cli): `prepare` command

---

src/prerender.ts

Hey, first timer here 🎉.
https://github.com/nuxt/image/pull/701
When using `@nuxt/image-edge` with Nuxt 3 the default image provider is [IPX](https://github.com/unjs/ipx) which allows arbitrary image manipulation through URLs.
When using multiple transformations on an image the different transformations are seperated by a comma like this in the final image URL:
```
/_ipx/q_50,s_10x10/images/nitropack.png
```
`@nuxt/image-edge` appends these URLs to the `X-Nitro-Prerender` header without encoding the URL.
The header will then be split by "," when prerendering the site which leads to the following URLs being prerendered:
- _ipx/q_50
- s_10x10/images/nitropack.png
This results in some images not being properly prerendered and/or missing in the final output build when running `yarn run …

fix(prerender): decode urls to allow comma in the `x-nitro-prerender` header

---

src/prerender.ts

Related to #799 
My bad, a missing parenthesis slipped through :(

chore: add missing parenthesis in header parsing

---

docs/content/1.guide/1.introduction/3.routing.md

docs: fix deprecated function in example on routing page

---

src/build.ts

There is a misalignment across dev and build. In dev, the middleware is registered in the normal order, which mean eailer items in `publicAssets` will have higher priority. While in build, `fes.copy` defaults to overrides the existing files, making the priority in the oppsite direction.

fix(build): do not override publicAssets in build

---

.eslintrc
src/dev/vfs.ts

This could be useful for other integrations to get the data and render it in their own style.

feat(dev): support for `/_vfs.json`

---

src/dev/error.ts
src/dev/server.ts
src/runtime/cache.ts
src/runtime/error.ts
src/runtime/renderer.ts
src/runtime/route-rules.ts
src/runtime/static.ts
src/runtime/timing.ts
src/runtime/utils.ts

This will resolve deprecated use of `event.req|res` to the new way which is `event.node`. To make sure it stays up to date.

refactor: update `event.` to `event.node.`

---

src/presets/netlify.ts
src/presets/vercel.ts
test/presets/netlify.test.ts
test/presets/vercel.test.ts
test/tests.ts

At the moment if you have a default cache rule, you can't override it negatively at a more specific level.
This PR should resolve that.

fix(netlify, vercel): explicit server rendering with disabled cache/swr

---

src/presets/netlify.ts
test/presets/netlify.test.ts

We can now use native ESM in Netlify with this undocumented config option (cc: @ascorbic), see https://github.com/sveltejs/kit/blob/master/packages/adapter-netlify/index.js#L163.

feat(netlify): use esm entrypoint

---

src/prerender.ts

n/a, see description below
If a link contains parts following the pathname, e.g. a query or hash, the file extension would not be found. Links that appear to have no file extension would then NOT be excluded from crawling. Those included links led the crawler to request, e.g. static, files on which `vue-bundle-renderer` (as used in Nuxt) would produce a memory overflow.
I did not investigate the reason for the overflow being an overflow further as the link usage is incorrect in the first place.

fix(prerender): check link's pathname only for extensions

---

docs/content/3.config/index.md
src/nitro.ts
src/runtime/app.ts
src/runtime/timing.ts
test/tests.ts

Fix https://github.com/nuxt/framework/issues/9824
`timing` config is for enabling bundles loading time instead of timing header, this pr is improving the accuracy of description.

fix(rumtime): disable server-timing header via options.timing

---

.gitattributes
.github/workflows/ci.yml
test/tests.ts

There are some significant differences with windows, particularly around file URLs and absolute paths. This is a starting point to test nitro on Windows to catch these issues early.
Here are two key differences noticed so far:
- hash function (for etag) gives different results - this may be okay as I'm not sure we need consistency across OSes
- dependency hoisting appears to be broken - may be resolved with https://github.com/unjs/nitro/pull/782
cc: @pi0

ci: run tests against windows as well

---

src/scan.ts

fix: filter unique scanned handlers

---

docs/content/1.guide/1.introduction/5.cache.md

Adds a description for the cache base option in route rules and an example on how to use a specific storage mountpoint for a group of routes.

docs: add cache base option example & description

---

src/rollup/plugins/public-assets.ts

```ts
import { readAsset } from '#internal/nitro/virtual/public-assets'
// throws error within readAsset
const file = readAsset('my-file')
```
Results in the following error when pre-rendering `undefined is not a promise`

fix(public-assets): mock readAsset promise properly

---

src/dev/server.ts
src/nitro.ts
src/options.ts
src/runtime/static.ts
test/fixture/nitro.config.ts

Allow using `maxAge` for `publicAssets: []` option to provide caching headers:
```js
publicAssets: [
{
baseURL: "dist",
dir: "public/dist",
maxAge: 3600,
},
],
```
Remarks:
- Using route rules in production we can also map caching to native providers
- Default (and unused) 60sec is removed for public dirs allowing opt-in control of this feature
- This feature is auto-disabled for `/` prefix and `fallthrough` paths since another handler might respond
- This feature is only effective on production to reduce chance of misconfiguration and development mode issues
- `immutable` and `public` conditions enabled
- One can directly use routeRules to apply for development or any other custom beahior 
Another fix is also included that allows to modify `nitro.options.routeRules` after init syncing …

feat: support `maxAge` for public assets

---

docs/content/1.guide/1.introduction/5.cache.md
src/runtime/cache.ts

feat: support `staleMaxAge: -1` to always respond stale value

---

src/presets/nitro-prerender.ts

https://github.com/nuxt/nuxt/issues/14454
There is a bug in `serve -s` that renders _all_ responses, not just 404s, with base `index.html`: https://github.com/vercel/serve/issues/722. This PR removes the flag. 404s will now be rendered with `/404.html`, which Nuxt now outputs, so this should not have any downside downstream on Nuxt - or, I think, in any other project depending on this.

fix(prerender): update preview command to serve matching routes

---

src/rollup/plugins/externals.ts

There are some files in `node_modules` without a parent `package.json` (perisma for example generates `node_modules/.prisma` without `.prisma/package.json`.
This PR supports tracing and copying them using a virtual package

feat(externals): support tracing orphan files in `node_modules`

---

src/rollup/plugins/externals.ts
test/unit/externals.test.ts

resolves #844
Rewrite `package.json` with production condition in exports field before writing to be consistent with the condition of resoluton before. Tested against two linked packages.

feat(externals): apply `production` condition to package.exports

---

docs/content/1.guide/1.introduction/5.cache.md
examples/cached-handler/routes/index.ts
src/runtime/cache.ts

In the spirit of #746, this adds an option to bypass the whole cache logic (so getKey isn't even called), while leaving the existing cache entry untouched. Good for a ?preview param without affecting live, but also certain subpaths you never want cached.
Idk if this needs an issue/discussion, it was easier to implement and test than to start an issue, lol

feat: add `shouldBypassCache` option to cache utils

---

docs/content/2.deploy/providers/netlify.md

docs(netlify): clarify placement of `_redirects` file

---

src/runtime/cache.ts

#875 
Example:
```ts
export default defineCachedEventHandler(async () => {
await new Promise((resolve) => setTimeout(resolve, 1000));
console.log("event called")
return `Response generated at ${new Date().toISOString()} (took 1 second)`;
}, {
maxAge: 600,
getKey: async (e) => {
await new Promise((resolve) => setTimeout(resolve, 500));
console.log("getKey called")
return e.node.req.url
}
});
```
usecase further explained in #875
I am not sure where this could be mentioned in the docs, should be obvious by the typing that promises/async are allowed?

feat(cache): allow async `getKey` option in cache utils

---

src/scan.ts

https://github.com/nuxt/nuxt/issues/18518
- x ] 🐞 Bug fix (a non-breaking change that fixes an issue)
Currently we are deduplicating middleware, which means only one middleware will ever be included in the built app. We should probably only deduplicate routes that have a path.

fix(scan): do not dedup middleware handlers

---

src/nitro.ts

https://github.com/nuxt/nuxt/issues/18587
We are now resolving server assets dirs before this point (#825), when `options` are resolved. We probably still need to resolve server dirs when adding them after this point.

fix: resolve server assets dir relative to `srcDir`

---

src/runtime/utils.ts

https://github.com/unjs/nitro/issues/759
Without having any idea on where to start to debug this, it would be nice if we can ship this temporary work around so that vercel-edge becomes more usable.

fix(vercel-edge): add temporary workaround for process.cwd usage

---

src/dev/server.ts

#894 
Looks at `X-Forwarded` headers in `proxyReq` and doesn't overwrite them if they're present.
Resolves #894

fix(dev): don't overwrite proxy headers if already set

---

src/options.ts
src/utils/index.ts

https://github.com/nuxt/nuxt/pull/18586
This provides fallback values for undefined runtime config: https://github.com/nuxt/nuxt/pull/18586#pullrequestreview-1273476353

fix: provide fallback values for undefined runtime config

---

src/presets/vercel.ts

resolves https://github.com/unjs/nitro/issues/902
Because of how the Vercel Build Output API works, we can't generate a file-only routing solution for a route rule that is `/`; in this very specific case we need to add it to the config as well.

fix(vercel): allow non-glob cache rules to apply to `/`

---

src/rollup/plugins/externals.ts
test/fixture/_/node_modules/nitro-dep-b/node_modules/nitro-lib/package.json
test/fixture/_/node_modules/nitro-dep-b/package.json
test/fixture/_/node_modules/nitro-lib/package.json
test/fixture/routes/modules.ts

- refactor: improve code readability
- implement stable tree
This PR improves Nitropack v2 externals tracker by analyzing dependency tree between packages in multi phases:
- Identify single versioned packages and multi versioned packages with their (versionined) parents
- Wrtie single versioned packages in parallel directly to `node_modules`
- For each multi versioned package
- Sort it's versions based on 1) no parents for hoisting 2) newer to older version
- For each version
- Write it to `node_modules/.nitro/name@version`
- For each multi version parent, link to `node_modules/.nitro/mv_parent}/node_modules/{name}`
- For each single version parent, link to `node_modules/{sv_parent}/node_modules/{name}`
This solves concurrency issue, improves performance and handling hoisting for hoisted …

fix(externals): use stable dependency tree

---

package.json
pnpm-lock.yaml
src/options.ts

Resolves #918
We mount `src/` and `root/` fs mounts during development for convinience and development features however it can be really dangrous to remove project source-code!! Using new unstorage `readOnly` option on both mounts. If it is proven that write operation is useful, we can switch to `noClear` to allow per key update.

fix(dev): mount `src` and `root` as read-only by default

---

docs/content/3.config/index.md
src/options.ts
src/runtime/route-rules.ts
src/types/nitro.ts

#113
Support runtime proxy using route rules and `h3.proxyRequest` (universally works with fetch)
```js
{
routeRules: {
'/proxy/example': { proxy: 'https://example.com' },
"/proxy/api/**": { proxy: '/api/proxied/**' },
}
}
```
Local support is pending https://github.com/unjs/h3/pull/321

feat: support runtime proxy using route rules

---

src/rollup/plugins/public-assets.ts
src/runtime/entries/cloudflare.ts
src/runtime/virtual/public-assets.d.ts

https://github.com/unjs/nitro/discussions/919
For now if you serve website to Cloudflare Workers you exceed free (and even paid) limits very fast because each request serves assets directly from worker and never cache in browser. 
I think that it will be great to get `maxAge` from publicAssetURLOptions, but i didn't touch rollup virtual code to make it work.

feat(cloudflare): `cacheControl` support for public assets with with `maxAge`

---

package.json
pnpm-lock.yaml
src/runtime/app.ts
src/runtime/entries/cloudflare.ts

resolves #391
closes #677
This PR exposes cloudflare [request context](https://developers.cloudflare.com/workers//runtime-apis/request#incomingrequestcfproperties) as `event.context.cf`. 
Implementation is based on new unenv support. Any other platform based on localFetch, can expose the same context by passing `{ context: {} }` to the request init.
A new generic handler is added to nitro. It will be used later for other purposes as well.
Note: For nested `$fetch`, we should explicitly pass the `cf` to be proxied:
```js
await $fetch("/test", { context: { cf: event.context.cf } });
```

feat(cloudflare): expose `event.context.cf`

---

docs/content/2.deploy/providers/firebase.md
src/presets/firebase.ts

Fixes #924
Node 18 is the current LTS version. It is the [recommended cloud function runtime](https://cloud.google.com/functions/docs/concepts/nodejs-runtime) and is a [prerequisite for Nuxt 3](https://nuxt.com/docs/getting-started/installation). This PR changes the default runtime from 14 to 18, and falls back to an older version if it is specified in the `engines` field in `package.json`.

feat(firebase): use nodejs 18 as default runtime

---

src/presets/cloudflare.ts

Reported by @Atinux when `icon.ico` cannot be served on cloudflare deployments.
Investigating this, `mapRequestToAsset` utility from `@cloudflare/kv-asset-handler`, appends `/index.html` always when a mime is not detected based on request extension! We use `mime/lite` and `ico` is not there this will cause cloudflare to fail! 
Best approach is accessing assets meta but as a workaround, this PR uses full mime db (25KB instead of 8KB) for cloudflare.
```
Before 
└─ .output/server/index.mjs (1.3 MB) (367 kB gzip)
Σ Total size: 1.3 MB (367 kB gzip)
1272    .output/server/index.mjs
After:
nitro 21:04:18
└─ .output/server/index.mjs (1.33 MB) (374 kB gzip)
Σ Total size: 1.33 MB (374 kB gzip)
1300    .output/server/index.mjs
```

fix(cloudflare): use full mime db

---

docs/content/3.config/index.md
src/options.ts
test/presets/netlify.test.ts
test/presets/vercel.test.ts
test/tests.ts

resolves https://github.com/nuxt/nuxt/issues/19057
This corrects the CORS header name we were applying

fix: correct `access-control-allow-methods` cors header name

---

src/rollup/config.ts

resolves #947
When externals are disabled (workers like cf), we completely depend on rollup/node-resolve plugin which happens to fail resolving in pnpm monorepos. This PR adds mlly support as fallback which seems to supporting pnpm well and fixing resolving issue + a small fix for node+noExternals

fix(rollup): use mlly as fallback resolver when externals disabled

---

src/runtime/utils.ts

https://github.com/nuxt/nuxt/issues/19093
Although a helpful idea, I think this is too broad a net for rendering an API response. Even routes starting with `/api` might still benefit from an HTML response if requested from a browser.

fix: don't render json response if url contains `/api/`

---

src/cli.ts

This adds the third CLI command to the printed out usage statement

chore(cli): mention `prepare` command in usage

---

docs/content/2.deploy/providers/cloudflare.md

Related: https://github.com/unjs/nitro/issues/272
Give some info regarding CF env variables.

docs(cloudflare): add info regarding `runtimeConfig` and environment variables

---

src/runtime/entries/node-cluster.ts

fix(node-cluster): default number of workers

---

docs/content/2.deploy/providers/lagon.md
src/presets/index.ts
src/presets/lagon.ts
src/runtime/entries/lagon.ts

https://github.com/lagonapp/lagon/issues/258
[Lagon](https://lagon.app/) is a new cloud runtime environment running in Rust. This is a preset for build + deployment.

feat: add lagon preset

---

src/rollup/plugins/externals-legacy.ts
src/rollup/plugins/externals.ts

This reduces change between two builds of the same package. It's quite a minor change but can help ensure reproducible nitro builds.

refactor(externals): sort `bundledDependencies` keys in output `package.json`

---

.gitignore
src/presets/cloudflare.ts
test/presets/cloudflare.test.ts
test/tests.ts

https://github.com/unjs/nitro/issues/497
We can generate a `_routes.json` file to prevent hits on assets directories from hitting the function at all. We might also be able to add individual assets that are outside of these directories to the json but this runs the risk of hitting the 100 rule limit. (Maybe we can allow extending the default config, suggested by @colonelbundy.)

fix(cloudflare-pages): exclude assets from function call

---

docs/components/global/Ellipsis.vue

Ellipsis component can cause unwanted horizontal scroll by overflowing device screen width if there are not enough space. (You can see on "after" screenshot there are no scrollbar at the bottom)
<details>
<summary>Before:</summary>
</details>
<details>
<summary>After:</summary>
</details>

docs(fix): prevent ellipsis overflow on small screens

---

docs/content/2.deploy/2.workers.md

#949 
Added first version of a separate page to document certain limitations and possible incompatible libraries with edge workers.

docs(deploy): add workers page for edge limitations

---

src/runtime/utils.ts

https://github.com/nuxt/nuxt/issues/19093
As `$fetch` is setting `Accept: */*` we can't detect JSON request purely by content-type. I think `sec-fetch-mode` might allow us to make another smart guess - CORS requests should probably also be JSON.

fix: render json errors for CORS requests

---

src/runtime/utils.ts

resolves #951
To avoid breaking changes, this PR uses json response again for routes starting with `/api` 
PS: This is temporary. We might find better solutions to show pretty error pages for API later. Also notes in https://github.com/unjs/nitro/pull/951#issuecomment-1438677976

fix: use json response for  errors in `/api/` routes

---

src/rollup/config.ts

https://github.com/nuxt/nuxt/issues/19236
This moves our mock for `debug` out of default settings and is now only applied in production mode.

fix: only mock `debug` in production

---

docs/content/3.config/index.md
playground/nitro.config.ts
src/rollup/plugins/esbuild.ts
src/types/nitro.ts

https://github.com/nuxt/nuxt/issues/19253
Adds support of more values for `sourceMap` config option. Now additionally `inline` and `hidden` are available in accordance with Rollup: https://rollupjs.org/configuration-options/#output-sourcemap

feat: add support for sourceMap values: hidden, inline

---

src/presets/lagon.ts

https://github.com/unjs/nitro/issues/966
Since `@lagon/cli@0.5.0`, Lagon supports configuration files (https://github.com/lagonapp/lagon/releases/tag/%40lagon%2Fcli%400.5.0)
This PR outputs Lagon's configuration file when the build is complete. It's written inside `${output.dir}/.lagon/config.json` (e.g `.output/.lagon/config.json`) and allows to start the dev server / deploy the function without specifying the function's entry point (`server/index.mjs`) and the public directory (`public`) manually.
Notes:
- Fields are written in snake_case
- All paths are relative to the parent of the `.lagon` folder
- `function_id` & `organization_id` fields are empty, they are used to detect if the function has been deployed or not
- `client` field is a path to a client-side JS script that can be …

feat(lagon): write Lagon config on build

---

examples/auto-imports/nitro.config.ts
examples/auto-imports/package.json
examples/auto-imports/routes/index.ts
examples/auto-imports/tsconfig.json
examples/auto-imports/utils/hello.ts
package.json
pnpm-lock.yaml
src/build.ts

refactor: use unimport built-in type gen for dirs

---

src/scan.ts
src/utils/tree.ts

https://github.com/nuxt/nuxt/issues/19234
While not exactly a bug, I think it makes sense to scan middleware in alphabetical order rather than the reverse, and also print the generated files that way too.

fix: scan middleware and print tree list in ascending alphabetical order

---

src/types/fetch.ts
src/types/serialize.ts
test/fixture/api/serialized/date.ts
test/fixture/api/serialized/function.ts
test/fixture/api/serialized/map.ts
test/fixture/api/serialized/set.ts
test/fixture/api/serialized/tuple.ts
test/fixture/types.ts

resolves #804, resolves https://github.com/unjs/nitro/issues/1000
This PR transforms the output type of $Fetch to better match what JSON.stringify returns (using trpc and remix implementation).
This is potentially a breaking change.

feat(types): type $fetch to match json serialization output

---

docs/content/1.guide/1.introduction/4.storage.md
src/rollup/plugins/storage.ts
src/runtime/virtual/storage.d.ts
test/fixture/api/storage/[...base].get.ts
test/fixture/api/storage/[...base].put.ts
test/tests.ts

Resolves #1008 
Support `useStorage(base)` as well as improving the documentation about storage.

feat: support base in `useStorage(base?: string)` and improve docs

---

docs/content/1.guide/1.introduction/5.cache.md
src/runtime/cache.ts

Improve a lot the documentation for the Cache API as well as:
- Making the default group for `cachedFunction` to `nitro/functions`
- Making the second option optional for `cachedFunction` like `cachedEventHandler`
[Docs preview](https://unjs-nitro-9h1v94h22-nuxt-js.vercel.app/guide/introduction/cache)

docs(cache): improve documentation and `cachedFunction` default options

---

src/rollup/plugins/externals.ts

Fixes https://github.com/nuxt/nuxt/issues/19436.
Fixes a small typo introduced in https://github.com/unjs/nitro/pull/782: according to https://github.com/npm/node-semver#ranges, two different versions are joined by `||` and not only a single `|`.

fix: correctly specify multiple external dependencies in package.json

---

src/build.ts
src/options.ts
src/types/nitro.ts

https://github.com/nuxt/nuxt/issues/13920
This allows customising the `types/tsconfig.json` path in case we want it to be in a different location or file name.

feat: allow customising generated tsconfig path

---

src/build.ts
src/imports.ts
src/options.ts
src/rollup/config.ts
src/rollup/plugins/app-config.ts
src/runtime/app.ts
src/runtime/config.ts
src/runtime/index.ts
src/runtime/virtual/app-config.d.ts
src/types/nitro.ts
src/utils/index.ts
test/fixture/app.config.ts
test/fixture/nitro.config.ts
test/fixture/routes/app-config.ts
test/fixture/server.config.ts
test/tests.ts

#728
App config, is an alternative to runtime config for bundled application wide configuration. It's main distinction from runtime config is that it supports development HMR and any js value time (while runtime config is limited to JSON serializable ones).
By default `app.config.{ext}` is scanned from all layer's srcDir. Additional app configs to be merged, can be specified by `appConfigFiles: []` option and `appConfig` can be used for inlined app config (sharing serialization limitations. Normal file is always better and recommended)

feat: support app config

---

src/rollup/plugins/storage.ts
src/runtime/cache.ts
src/runtime/index.ts
src/runtime/storage.ts
src/runtime/virtual/storage.d.ts

https://github.com/nuxt/nuxt/pull/19148
Expose `useStorage` types with runtime implementation outside of vfs.

fix: expose `useStorage` with types

---

src/prerender.ts

https://github.com/unjs/nitro/issues/1029
Removes the space character from the end group character set in `LINK_REGEX`. Only single/double quotes can end the match now, allowing for `href` paths with spaces in them.
Resolves https://github.com/unjs/nitro/issues/1029

fix(prerender): allow spaces in `href` value regex

---

docs/content/3.config/index.md

Add short description for the `prerender.ignore` option implemented in https://github.com/unjs/nitro/commit/a6cbbbe482243a3d8dc4c3917ec406b74fdb2a8f.

docs: add `prerender.ignore` description

---

src/runtime/cache.ts

**To be properly tested**.
So far, when `swr: true`, we should return the stale data for all incoming request until the cache is updated in background.
Also, I am not sure to understand the `(opts.staleMaxAge || 0) >= 0` condition here.

fix(cache): use stale value by default when `swr` is enabled

---

src/build.ts

We now support a custom tsconfig path, but in that PR I neglected to ensure that the paths were resolved relative to the custom path if it were in a different directory.

fix: resolve types relative to custom tsconfig path

---

src/types/nitro.ts
test/fixture/types.ts

closes #977
We were wrongly typing non-supported cache options (nonserializable functions) for `cache` key in `routeRules`.

fix(types): exclude non serializable options from route rules

---

src/types/fetch.ts
test/fixture/api/param/[id].ts
test/fixture/api/serialized/error.ts
test/fixture/api/serialized/null.ts
test/fixture/api/serialized/void.ts
test/fixture/api/wildcard/[...param].ts
test/fixture/routes/icon.png.ts
test/fixture/types.ts

https://github.com/nuxt/nuxt/pull/19654
We are experiencing issue comparing routes triggered by https://github.com/unjs/nitro/pull/1002. This slightly decreases complexity but we really need to find a solution for this on larger projects. (And ideally to replicate regression locally in type fixture by, as a first step, enabling `strict: true` in nitro and increasing type complexity.)

fix: don't simplify type of serialized return

---

src/dev/error.ts
src/runtime/error.ts
src/runtime/renderer.ts

It will break the response if we set any of these characters by accident (e.g. if a user includes in an error message).
Related: https://github.com/nuxt/nuxt/issues/14688

fix: sanitize `statusMessage` of disallowed chars

---

src/types/presets.ts

This PR adds the missing `crons` and `remotePatterns` to vercel build config types

fix(types): sync vercel build config types

---

src/presets/azure.ts

resolves https://github.com/unjs/nitro/issues/1061
https://github.com/nuxt/nuxt/issues/19385
This adds support for custom baseURLs by nesting the public directory with the correct prefix. (We still have to write our empty `index.html` in the root, though.)

fix(azure): support custom baseURL

---

docs/content/1.guide/3.routing.md

After some confusion trying to identify which command to use to fetch an API using only Nitro, I was not sure if the same command on Nuxt would work here.
To avoid this confusion and to make it clear to anybody that `$fetch` is the command to use I believe this should be in the documentation

docs(routing): update add `$fetch` usage note

---

src/options.ts
src/utils/index.ts

This adds type-safety for auto-detected providers.

refactor: add type safety to auto-detected providers

---

src/presets/vercel.ts

It seems `routeRules` generates invalid routes when using the `vercel-edge` preset.
This is because nitro only creates pretender functions for the `vercel` preset:
https://github.com/unjs/nitro/blob/4585ca856b0fb4d5601e30fc36f9dbde4aef03de/src/presets/vercel.ts#L51-L85
and the `generateEndpoint` function isn't considering the `vercel-edge` preset:
https://github.com/unjs/nitro/blob/4585ca856b0fb4d5601e30fc36f9dbde4aef03de/src/presets/vercel.ts#L226-L234

fix(vercel-edge): fix route generation

---

src/types/nitro.ts

We test if renderer exists, so I think we can safely mark this as an optional type:
https://github.com/unjs/nitro/blob/aa5a2f4120681e00c311607fd4ad981df30be1d7/src/rollup/plugins/handlers.ts#L19-L25

fix: mark renderer as optional

---

src/prerender.ts
src/presets/nitro-prerender.ts

https://github.com/nuxt/nuxt/issues/19883
At the moment we hard code `nitro-prerender` preset command to assume a certain directory structure. This respects the 'host' nitro preset output directories to produce the preview command.

fix(prerender): respect output path from main preset

---

src/options.ts
src/presets/netlify.ts
src/presets/vercel.ts
src/runtime/cache.ts
src/runtime/entries/netlify.ts
src/types/nitro.ts
test/fixture/nitro.config.ts
test/presets/netlify.test.ts
test/presets/vercel.test.ts
test/tests.ts

Resolves #946
We had been experimenting vercel ISR and netlify Builders feature via an implicit cache route rule. 
Introducing a new `isr` flag, unblocks to combine nitro native cache (SWR) with platform native rules and giving the flexibility to use the most effective caching mechanism. (Currently, on these platforms nitro cache/storage cannot be used)
Note: This is a semi-breaking change for this platforms however switching `swr` to built-in behavior still preserves in memory cache so caching keeps working only can be changed to either isr or permanent by mounting `/storage` for production.
This PR also drops (almost unused) `static` cache rule.

feat(vercel, netlify): introduce `isr` route rule

---

src/build.ts
src/options.ts
src/presets/index.ts
src/presets/static.ts
src/types/nitro.ts
test/presets/static.test.ts

resolves https://github.com/unjs/nitro/issues/797
This adds a basic static preset that can be extended to create `vercel-static`, `github-pages` and more.

feat: add `static` preset

---

docs/content/2.deploy/providers/github-pages.md
src/presets/github-pages.ts
src/presets/index.ts
src/presets/static.ts

resolves https://github.com/unjs/nitro/issues/798
https://github.com/nuxt/nuxt/issues/12480
https://github.com/nuxt/nuxt/issues/12570
This adds a basic GitHub Pages preset. It creates a `.nojekyll` file and by default uses https://github.com/tschaub/gh-pages as deploy command.

feat: add `github-pages` preset

---

src/build.ts
src/options.ts
src/types/nitro.ts

This fixes a regression where we were expecting the `tsConfigPath` passed in to be a child of `types`, and therefore produce the wrong paths within a generated `tsconfig.json`.
It also adds a new `forceConsistentCasingInFileNames` option, and allows configuring of the `strict` option (disabled by default to avoid a breaking change, although I would recommend always enabling strict mode, and perhaps this could be made default in a future version).

fix: separate `typesDir` from `tsConfigDir`

---

src/build.ts
src/options.ts
src/presets/netlify.ts
src/presets/static.ts
src/presets/vercel.ts
src/types/nitro.ts

rename `build` option (unreleased) to `static` for better readability of the option purpose.

refactor: rename `build` option to `static`

---

src/runtime/entries/cloudflare-module.ts
src/runtime/entries/cloudflare-pages.ts

Related #1132, #272
Cloudflare's module format only allowed accessing env bindings within the request accessible via `event.context.cloudflare.env`.
This makes it harder to make existing stateless utils such as `useStorage` and `useRuntimeConfig` work with this new format.
We might make it more restricted in the feature of how/where these composables are going to be used to properly address such limitations.
Workaround with this PR assumes `env` is safe to be shared across requests for **only internal usage** and exposing it as `__env__` global to be platform agnostic. User land use cases should **never** reply on this env.

fix(cloudflare): expose env from module context

---

src/runtime/route-rules.ts
test/fixture/api/echo.ts
test/fixture/nitro.config.ts
test/presets/nitro-dev.test.ts
test/tests.ts

When a routeing rule like `/proxy: { proxy: 'to' }` exists, the query params was being ignored. Added fix + tests. (thanks @Atinux for reporting)

fix(proxy): append request query params for single proxy route rules

---

docs/content/1.guide/6.assets.md

The `serverAssets` example for config in the current docs is confusing for first-timers, (it took me 30 minutes to find the problem)
And there is no way to easily find errors from `useStorage().getKeys()` or logs 😅
documentation example `./server/templates`
Look for `{srcDir}/server/templates` in nitro
Look for `{srcDir}/server/server/templates` in nuxt3
I don't think this should fit the vast majority of use cases
I hope that PR can help the next person who uses this function to use this function more easily and correctly.

docs: update serverAssets example

---

src/build.ts
src/rollup/config.ts
src/types/nitro.ts

This allows modifying the resolved rollup config.

feat: pass resolved config to `rollup:before` hook

---

build.config.ts
config.d.ts
docs/content/1.guide/1.configuration.md
docs/content/1.guide/3.routing.md
docs/content/1.guide/4.storage.md
docs/content/1.guide/5.cache.md
docs/content/1.guide/6.assets.md
docs/content/1.guide/7.plugins.md
docs/content/2.deploy/0.index.md
docs/content/3.config.md
examples/api-routes/nitro.config.ts
examples/auto-imports/nitro.config.ts
examples/cached-handler/nitro.config.ts
examples/custom-error-handler/nitro.config.ts
examples/hello-world/nitro.config.ts
examples/middleware/nitro.config.ts
examples/plugins/nitro.config.ts
package.json
playground/nitro.config.ts
playground/tsconfig.json
src/config.ts
src/options.ts
test/fixture/nitro.config.ts
test/fixture/types.ts
tsconfig.json

- perf: export `defineNitroConfig` from `nitropack/config`
- update usages
By importing `defineNuxtConfig` from `nitro/config` subpath, startup time significantly reduces as JITI does not need to load whole nitro and it's deps as CJS

perf: export `defineNitroConfig` from `nitro/config`

---

package.json
playground/nitro.config.ts
pnpm-lock.yaml
src/cli/commands/dev.ts
src/nitro.ts
src/options.ts
src/types/nitro.ts

Using new [c12.watchConfig](https://github.com/unjs/c12#watching-configuration) to watch nitro configuration and auto-reload.
Note: This only enables watch for `nitro dev` and not external frameworks like Nuxt. Nuxt CLI should adopt c12 watcher itself.
Note: This PR also unlocks HMR support for nitro 🚀

feat: config reload support for `nitro dev`

---

src/build.ts
src/cli/commands/dev.ts
src/index.ts
src/nitro.ts
src/options.ts
src/rollup/config.ts
src/types/nitro.ts

This PR supports HMR config updates for `runtimeConfig` and `routeRules` objects for `nitro dev` to rebuild the app without full reload.
A manual hook `nitro.updateConfig()` is also exposed to update this configuration on demand programmatically (useful for integration with other frameworks like Nuxt)

feat: config hmr support for `routeRules` and `rutimeConfig`

---

package.json
pnpm-lock.yaml
src/options.ts
src/rollup/plugins/handlers.ts
src/runtime/routes/openapi.ts
src/runtime/routes/swagger.ts
src/runtime/virtual/server-handlers.d.ts
test/fixture/nitro.config.ts

Resolves #3 
Resolved #4
This PR exposes available routes and an initial meta using [Open API 3 standard](https://www.openapis.org/).
It exposes two endpoints for development:
- `/_nitro/openapi.json`: JSON response that can be integrated with external tools and setups such as Postman and Nuxt devtools to access available routes meta (/cc @antfu)
- `/_nitro/swagger`: A basic UI that makes local debugging easier
This feature opens the next steps in supporting generic and extendable route meta via a well-defined standard.

feat: experimental `/_nitro/openapi.json` and `/_nitro/swagger` endpoints for dev mode

---

src/rollup/config.ts

nuxt/nuxt#15244
We currently use `startsWith` but the chunk on windows has backslashes so this needs to be normalised first to match our internal `buildServerDir`.

fix: apply `chunkFileNames` on windows

---

src/presets/vercel.ts
src/types/presets.ts

This allows specifying the regions for edge functions in Vercel, which can be beneficial to ensure they are running close to a DB (for example).
**More info**: https://vercel.com/docs/concepts/functions/edge-functions#edge-function-regions

feat(vercel): add support for specifying edge regions

---

docs/content/2.deploy/providers/vercel.md

docs(vercel): add vercel kv storage section

---

docs/content/3.config.md
src/options.ts
src/presets/netlify.ts
src/presets/vercel.ts
src/types/nitro.ts

> Uses built-in SWR functionality (using caching layer and storage) for Netlify and Vercel presets instead of falling back to ISR behavior.
New `future` namespace will be used for potentially breaking but stable changes with an opt-in method until next major nitro versions. This way we can better collaborate with consumer frameworks such as Nuxt.

feat: `future.nativeSWR`

---

test/presets/vercel-edge.test.ts
test/tests.ts

Windows CI should skip `vercel-edge` but it is not skipping it with `describe.skipIf(isWindows)(...)` only in CI. (runIf seems broken too)
Failing: https://github.com/unjs/nitro/actions/runs/4989669099/jobs/8933890560#step:8:345
/cc @antfu

chore: workaround for `describe.skipIf` not working

---

src/dev/vfs.ts

Taking advantage of `details` and `summary` with a generated structure, it should finally do a bit cleanup for the VFS.
Preview:
I'm definitely open to feedback and ideas on this if we look to polish it more. 🙂

refactor: show `/_vfs` structure in nested tree

---

src/runtime/config.ts

Resolves #1283 
This PR adds the ability for the user to provide a type hunt configuration to the useRuntimeConfig() call as:
```ts
const { db } = useRuntimeConfig<{
db: LibSQLDatabase
}>()
```
I'd gladly accept help and guidance on how we could infer the types from the nitro.config.ts file ... cc @danielroe

types: support type generic for `useRuntimeConfig`

---

src/runtime/app.ts
src/runtime/config.ts
src/types/nitro.ts
test/fixture/types.ts
vitest.config.ts

This is a follow-up addition for #1284 fixing types and also allows to easily extend (globally) runtime config types:
```ts
declare module 'nuxt/schema' {
interface NitroRuntimeConfig {
apiSecret: string
}
}
```

feat: type `useRuntimeConfig` with `NitroRuntimeConfig`

---

package.json
pnpm-lock.yaml
src/presets/bun.ts
test/tests.ts

Currently bun preset is broken since after https://github.com/unjs/ofetch/pull/246, https://github.com/unjs/node-fetch-native/pull/75 and https://github.com/unjs/uncrypto/commit/abf5508578920a3f0b6edf3f8383fb4f9772b431, new `bun` export condition is used but we still trace the externals of `ofetch`/`node-fetch-native`/`uncrypto` with `node` condition.
This PR uses a workaround to resolve this.

fix(bun): resolve internal dependencies with `bun` export condition

---

src/runtime/app.ts
src/runtime/types.ts

https://github.com/nuxt/nuxt/issues/21593#comment-2542384
This addresses a TODO comment to allow nitroApp hooks to be typed (and extended via module augmentation).

feat: type nitro app runtime hooks

---

src/presets/cloudflare-pages.ts

Add a cloudflare-pages static preset 
References :
https://github.com/unjs/nitro/pull/1073/files
https://github.com/unjs/nitro/pull/1127/files

feat: add cloudflare-pages-static

---

src/prerender.ts

Without this, if we pass `static: true` in initial config we will be unable to prerender anything.

fix(prerenderer): don't inherit `static` config

---

docs/content/3.config.md
docs/pnpm-lock.yaml

Add an example for the `devHandlers` usage. I'm currently learning Nitro and I did not find how to remove the warning ` Implicit event handler conversion is deprecated. Use 'eventHandler()' or 'fromNodeMiddleware()' to define event handlers. ` during an hour.
So I think that this could help people.

docs: add an example for `devHandlers` config

---

src/dev/error.ts
src/runtime/error.ts
src/runtime/renderer.ts
src/runtime/static.ts

Use the new h3 `event.handled` flag (https://github.com/unjs/h3/pull/410) to guard `node.res.end` calls and avoid responding to an already ended request similar to https://github.com/unjs/h3/pull/411

fix: use `event.handled` guard before sending response

---

docs/content/2.deploy/providers/flightcontrol.md

Corrected Flightcontrol spelling

 docs: fix typo in Flightcontrol deployment option #970

---

src/options.ts
src/types/nitro.ts

Currently it's not possible to augment `runtimeConfig.app` whilst also using Nitro types for runtime config.
This PR makes it possible to augment `app`. It also exposes the `nitro` type. (I can also make augmentation disallowed for this if that is desirable.)

types: avoid overriding app runtime config namespace

---

src/types/nitro.ts

This adds a missing type for `runtimeConfig.nitro` - apologies!
(This is not a blocker for Nuxt.)

fix: add `envPrefix` to `runtimeConfig.nitro` types

---

docs/content/2.deploy/providers/azure.md

N/A
I copied the text stating "Install [Azure Functions Core Tools](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local) if you want to test locally." from the Azure Functions Local Preview section of the documentation.
When I was building and previewing locally using the `azure` nitro preset, I found that the server would not run unless I installed Azure Functions Core Tools. However, that documentation was written in the Azure Functions section no in the Azure Static Web Apps section. Therefore I believe it is important to include this message in both sections to reduce issues/confusion from users.

docs: add reference to install azure functions core tools to the swa section

---

src/presets/nitro-prerender.ts

nuxt/nuxt#21722
This allows access to static files whilst prerendering - which I think would be a common use case.

fix(prerender): allow to fetch static files

---

src/options.ts
src/utils/index.ts

https://github.com/nuxt/nuxt/issues/21728
If we have enabled `static` then we should default to `static` preset rather than `node-server`. As we are only using `detectTarget` in these two places, I think we can also slightly simplify the code.

fix(options): default target to `static` when `static` override is set

---

src/rollup/config.ts

fix: https://github.com/unjs/nitro/issues/1346
fix: https://github.com/nuxt/nuxt/issues/21768
see vite PR logic: https://github.com/vitejs/vite/pull/12194
Some packages uses `globalThis.process.env.NODE_ENV` instead of `process.env.NODE_ENV`, which isn't supported by default by rollup. Vite supports this and so does Nuxt, so this changes brings the exact same feature to the rollup config for Nitro.
See issue in [graphql-js](https://github.com/graphql/graphql-js/issues/3918)

fix(rollup): replace `globalThis.process.` with `process.`

---

.gitignore
playground/routes/index.ts
src/options.ts

The storage interface from `useStorage` is by default all in memory. In order to write stateful KV logic, users therefore require to configure `storage` mountpoints.
This PR adds a default `data` mountpoint using fs driver for all node based presets and development mode. (only if not configured by user) This way data will be persisted in `.data/kv` by default only for `data:` .
```ts
export default eventHandler(async (event) => {
const kvStorage = useStorage("data");
const counter = (Number(await kvStorage.getItem("counter")) || 0) + 1;
await kvStorage.setItem("counter", counter);
return {
counter,
};
});
``` 
Next steps:
- Support auto config storage for other worker presets when env/binding exits
- Document this feature + `.data` dir and gitignore
- Use data storage for cache as well …

feat(storage): default data storage for `node` and dev presets

---

docs/content/2.deploy/providers/cloudflare.md
src/presets/cloudflare-module.ts
src/presets/cloudflare.ts

See https://github.com/cloudflare/workers-sdk/issues/3067
Happening already today:

refactor(cloudflare): use `wrangler deploy` instead of `publish`

---

src/build.ts

This enables `allowSyntheticDefaultImports: true` by default.

fix(types): enable `allowSyntheticDefaultImports` option by default

---

src/rollup/plugins/externals-legacy.ts
src/rollup/plugins/externals.ts

I'm hoping to move more inlining from vite server build -> nitro build to avoid duplication of libraries. (e.g. h3 createError, some vue dependencies, anything shared between vite + nitro builds, etc.)
Part of that means being able to respect Nuxt's `build.transpile` which may include RegExps, and the best way would be to be able to pass those options on to nitro externals options.

feat: support regexps in external options

---

docs/content/1.guide/3.routing.md
docs/content/2.deploy/providers/vercel.md

After following the initial project scaffolded via the command `npx giget@latest nitro nitro-app` I found that after deploying to vercel via `vercel` command my routes were not at the expected place of domian.com/api/hello/.
I added this documentation to hopefully help future developers wishing to deploy to vercel not waste time understanding the mapping of routes. 
I found the solution via this GitHub discussion
https://github.com/unjs/nitro/discussions/233

docs(vercel): add note about top level `api/` directory

---

src/runtime/app.ts
src/runtime/entries/cloudflare-module.ts
src/runtime/entries/cloudflare-pages.ts
src/runtime/entries/cloudflare.ts
src/types/h3.ts
test/fixture/routes/wait-until.ts
test/tests.ts

#1420
This PR supports platform-agnostic `event.waitUntil` that keeps promises under `event.context.nitro._waitUntilPromises` (private - unused) and also adds integration with all clodflare presets (https://developers.cloudflare.com/workers/runtime-apis/fetch-event/#waituntil)

feat: `event.waitUntil` with cloudflare integration

---

src/runtime/cache.ts

https://github.com/unjs/nitro/issues/1420
Based on #1421, try to call `event.waitUntil` for the cache update operation if the first parameter in `defineCachedFunction` is an event and always for `defineCachedEventHandler`.
Previously we were using a dangling background promise which was not being ended on Cloudflare workers. 
(this is an experimental fix without introducing new API)

fix(cache): try to call `event.waitUntil`

---

docs/content/2.deploy/3.custom-presets.md

Resolves #1373 
Adds some instructions about custom presets.

docs: add custom preset instructions

---

src/options.ts
src/scan.ts
src/types/nitro.ts
test/fixture/api/_ignored.ts
test/fixture/middleware/_ignored.ts
test/fixture/nitro.config.ts
test/fixture/routes/_ignored.ts
test/tests.ts

Resolves #843
Related: https://github.com/nuxt/nuxt/issues/13427, https://github.com/unjs/nitro/pull/945
This PR supports `ignore: string[]` option in order to specify ignore patterns for scanning `/plugins`, `/middleware`, `/routes` and `/api` from all layers. The `scan.ts` has been almost rewritten to be prepared for this. Supporting public dir ignore in #945 after this.

feat: support `ignore` to ignore scanned files

---

docs/content/1.guide/community/9.contributing.md

The contributing page had a small mistake which misspelled the word discussions.
The Contributing page on the website had a typo where the word 'discussions' was spelled as 'dicussions'. I corrected this small typo.

docs: fixed typo of the word 'discussions'

---

docs/content/1.guide/3.routing.md
docs/content/1.guide/5.cache.md
docs/content/2.deploy/providers/vercel.md
docs/content/3.config.md

Hello, since functions like `defineNitroConfig` and `defineNitroPlugin` start with `define` (and Nuxt use `defineEventHandler`), we could harmonize using `defineEventHandler` everywhere.

docs: use `defineEventHandler` instead of `eventHandler`

---

docs/content/1.guide/1.configuration.md
docs/content/1.guide/3.routing.md
docs/content/1.guide/4.storage.md
docs/content/1.guide/5.cache.md
docs/content/1.guide/6.assets.md
docs/content/1.guide/7.plugins.md
docs/content/2.deploy/0.index.md
docs/content/2.deploy/3.custom-presets.md
docs/content/2.deploy/providers/aws.md
docs/content/2.deploy/providers/vercel.md
docs/content/3.config.md

Since the `defineNitroConfig` is auto-imported, I think that we could safely remove import from examples.

docs: remove auto-imported `defineNitroConfig`

---

src/runtime/static.ts

https://github.com/nuxt/nuxt/issues/22071
In some cases (such as a malformed URL) we might encounter an error when checking whether the URL is a static asset. However, we can be assured it is _not_ a static asset and either throw a 404 if it has the static prefix, or simply early return from the handler and directly progress to the next handler, which can allow the user to correct the URL or throw their own error.

fix(static): safe decode path

---

package.json
pnpm-lock.yaml
src/runtime/app.ts
src/runtime/entries/aws-lambda.ts
src/runtime/entries/azure-functions.ts
src/runtime/entries/azure.ts
src/runtime/entries/bun.ts
src/runtime/entries/cloudflare-module.ts
src/runtime/entries/cloudflare-pages.ts
src/runtime/entries/cloudflare.ts
src/runtime/entries/deno-deploy.ts
src/runtime/entries/deno-server.ts
src/runtime/entries/lagon.ts
src/runtime/entries/netlify-edge.ts
src/runtime/entries/netlify-lambda.ts
src/runtime/entries/service-worker.ts
src/runtime/entries/stormkit.ts
src/runtime/entries/vercel-edge.ts
src/runtime/utils.azure.ts
src/runtime/utils.lambda.ts
src/runtime/utils.ts
test/fixture/api/headers.ts
test/presets/aws-lambda.test.ts
test/presets/netlify.test.ts
test/tests.ts

- feat: handler cookie headers for Response
- chore: flag unhandled cookies
Closes https://github.com/unjs/nitro/pull/989
Fix #988 
Continuing the work done by @oleghalin and applying it more generally to every presets that needs it.
Note that the culprit for this would be `unenv`, but fixing this in Nitro allows us to not add any dependency to `unenv`.

fix: split cookie headers 

---

package.json
pnpm-lock.yaml
src/presets/deno-deploy.ts

https://github.com/unjs/nitro/issues/1432
Rollup 3.26.2 (accidentally?) made a breaking change in the handling of `manualChunks`. This updates rollup to a fixed version, and also changes the config so that all `https://` modules in Deno are treated external.

fix(deno-deploy): treat all `https://` modules as external

---

src/prerender.ts

Fix https://github.com/unjs/nitro/issues/1402
Resolves https://github.com/unjs/nitro/issues/1418
External links that returns 200 or 30x should be treated the same way.
We might need to add an additional check for external links.

fix(prerender): skip redirects

---

src/runtime/app.ts
test/fixture/api/upload.post.ts
test/tests.ts

- add failing test
- fix(app): enable router preemptive mode
Resolves #1503, https://github.com/nuxt/nuxt/issues/22382

fix(app): enable router preemptive mode

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/PULL_REQUEST_TEMPLATE.md

This PR brings some improvements to the github templates for the nitro repository.

chore: update github templates

---

src/presets/vercel.ts
src/types/presets.ts

Related to #1505
When upstream supports a new configuration, we should always allow users to override nitro defaults (and type them or provide better defaults in next releases)

fix(vercel): allow arbitrary  function configuration

---

docs/content/2.deploy/providers/cloudflare.md
src/dev/vfs.ts
src/runtime/app.ts
src/runtime/cache.ts
src/runtime/error.ts
src/runtime/renderer.ts
src/runtime/route-rules.ts
src/runtime/static.ts
test/fixture/api/echo.ts
test/presets/deno-server.test.ts

This PR migrates most of internals to prefer top level or h3 utils instead of depending to `event.node.req`. (https://github.com/unjs/h3/issues/73)
One major remaining part, is cachedEventHandler which currently uses a mock req, res. https://github.com/unjs/h3/issues/472 might cover this!
Note: Deno is broken since installs h3 latest instead of rc (current dep)! Enabling tests after fixing it.

refactor: reduce usage of `event.node.req` 

---

src/dev/error.ts
src/runtime/error.ts
src/runtime/renderer.ts
src/runtime/static.ts

Following up #1511, this reduces dependency on `event.node.res` across nitro codebase. `event.handled` checks are now removed too since send utility is expected to take care of it (in rare cases there might be regressions since `send` is async but we might investigate anything related in h3 `send` util if happens). Main part remaining are `timing` and `cachedEventHandler` to fully decouple from node.

refactor: reduce usage of `event.node.res`

---

src/presets/vercel.ts
src/types/presets.ts

resolves #1505
This PR improve js docs for vercel sls config and also enables `supportsResponseStreaming` flag by default (can be disabled by user).
Now that we are using a h3 version that is compatible with streaming, we can safely enable streaming. I have requested vercel team to verify this.

feat(vercel): enable streaming support out of the box

---

src/build.ts

Without a `baseUrl` we cannot pass in absolute paths in nitro aliases. This ensures that our aliases + includes are relative to the tsconfig file itself.

fix: use relative paths in `tsconfig.json`

---

src/prerender.ts

Resolves #1535
This PR resolves the high memory usage issue when prerendering lots of routes by cleaning up the memory of route contents as soon as being written to the disk.
Since we were already typing the `route.data` and `route.contents` as optional, as a non breaking change they are only available (and can be set) before disk write. We could additionally support reading back contents from disk when accessing `.data` and `.contents` getters using fs sync methods but I think we can do it only if necessary.
Testing on [reproduction in #1535](https://github.com/unjs/nitro/issues/1535) there seems no memory leaks anymore generating all 100k routes.

fix(prerender): free up memory after each route is written to the disk

---

src/prerender.ts

[](https://github.com/unjs/nitro/pull/1536)
With #1536, we are freeing up route contents from memory but this was causing `prender:route` to lose access to the route contents.
This PR fixes this by fixing the ordering and calling the hook directly inside `generateRoute` before freeing up memory and also simplifying the code. (previously we were wrongly catching _unhandled internal errors_ as route errors now it uses simple console log to only avoid hiding edge cases with internal nitro bugs)

fix(prerender): call `prerender:route` before freeing up memory

---

docs/content/1.guide/4.storage.md

https://github.com/unjs/nitro/issues/1161
Document workaround for https://github.com/unjs/nitro/issues/1161

docs(storage): add runtime storage configuration examples

---

src/prerender.ts
test/fixture/routes/500.ts
test/fixture/routes/prerender.ts

resolves https://github.com/unjs/nitro/issues/1527
This restricts `href` regexp to match only ` href` and not `x-link:href` (for example).

fix(prerender): only match `href` attribute after whitespace

---

src/build.ts

This PR uses fully-resolved paths for type declarations

feat: fully resolve type paths for auto-import declarations

---

docs/content/2.deploy/0.index.md
docs/content/2.deploy/2.workers.md
docs/content/2.deploy/providers/aws.md
docs/content/2.deploy/providers/azure.md
docs/content/2.deploy/providers/cloudflare.md
docs/content/2.deploy/providers/deno.md
docs/content/2.deploy/providers/github-pages.md
docs/content/2.deploy/providers/iis.md
docs/content/2.deploy/providers/netlify.md
docs/content/2.deploy/providers/render.md
docs/content/2.deploy/providers/vercel.md

This updates the preset for Cloudflare Pages to be named `cloudflare_pages` instead of `cloudflare-pages`.  This brings the name inline with the one on the https://nitro.unjs.io/deploy page and actually works when deploying to Cloudflare Pages.
I have to set `cloudflare_pages` in my `nuxt.config.ts` in order for this preset to work.  I assume that means that the preset should be underscored and not dashed like `cloudflare-pages`.  If I use `cloudflare-pages` instead of `cloudflare_pages`, the `dist` directory does not get created.

docs: prefer snake_case for preset names

---

src/runtime/routes/openapi.ts
test/fixture/nitro.config.ts

#1350
In the openapi.ts file, the `paths` property is generated by using `Object.fromEntries` on the result of a map operation on `handlersMeta`. However, this causes unwanted behaviour : when there are sub-paths routes that only differ by their method, only the last path is present, as it has overridden the other paths information in the final `paths` property.
To fix this, I am now creating the paths object and merging the sub-paths using `Array.reduce` on `handlersMeta` instead. The operations inside this reduce are still the same as the ones inside the previous map implementation.
What has changed is that now instead of returning an array of the route and its path, I now check if the accumulated value, (the total paths object), has the current route as a property. If it does not, I …

fix(openapi): merge handlers with same route and different method

---

docs/content/1.guide/7.plugins.md
src/runtime/app.ts
src/runtime/types.ts

Support runtime hooks to intercept request lifecycle based on https://github.com/unjs/h3/pull/482
~~Note: For performance, hooks are called in parallel.~~

feat(app): support `request`, `beforeResponse` and `afterResponse` hooks

---

src/rollup/plugins/externals.ts

#1429, https://github.com/nuxt/nuxt/pull/22515
This PR improves the scoring system for include/exclude patterns introduce in #1429 by giving a higher score to package names (nonabsolute paths without).

fix(externals): increase score for npm package name patterns to avoid breaking changes

---

package.json
pnpm-lock.yaml
src/rollup/config.ts
src/rollup/plugins/externals.ts
test/presets/node.test.ts
test/presets/vercel-edge.test.ts
test/tests.ts

Normally when using the `resolutions` field to use an aliased package (say original name is `a` and aliased from `npm:b`), the package manager downloads `b` with and copies all contents into `node_modules/a` (while `node_modules/a/package.json` is package with `name: b`.). We use "directory" name as authentic package name to copy into `.output/server/node_modules`
pnpm also does this but there is a catch! the `node_modules/a` is a symbolic link to `node_modules/.pnpm/b`. When we are running external tracer, we follow the links and assume the real name is `b` which is wrong. To add to the complexity, rollup, mlly and nft also resolve real paths in various places so it is almost impossible to trace aliaces without manually specifying. (We might auto detect from root level `package.json` …

feat(externals): support aliasing traced packages

---

src/options.ts
src/presets/bun.ts
src/rollup/config.ts

resolves #1558
`module` is a non-standard export condition not supported by Node.js or any runtimes which was previously used as a top-level property in order to help bundlers pick the esm-like/browser builds. 
We disabled [top level `module` field long before](https://github.com/unjs/nitro/blob/7fa84084dc2531d8274d0bb035d4f4977428311c/src/rollup/config.ts#L425) because of this externals, new resolution conditions in #1401 added it back and makes issues with packages such as `ts-lib` and `@sanity/client` that are (wrongly!) using AND preferring this export condition over `import.
I also updated Bun conditions. Checking their docs, it seems they recently made same decition.

fix: remove non-standard `module` export condition

---

src/rollup/plugins/externals.ts

resolves https://github.com/unjs/nitro/issues/1558#issuecomment-1673919094
Reproduction: https://stackblitz.com/edit/github-kkcfd3?file=package.json
vercel/nft smartly applies `import` OR `require` conditions based on the parent file. By overriding (giving both import and require conditions) we were allowing nft to resolve as ESM even for CommonJS modules.

fix(externals): trace externals with their commonjs / esm status

---

package.json
pnpm-lock.yaml
scripts/bump-edge.ts

ci: use `h3-nightly@latest` for edge releases

---

docs/content/2.deploy/providers/firebase.md

Fixes #1555 
I tried implementing the new Gen2 preset, and noticed there were a couple of inconsitencies between the code, and the docs. This PR fixes them.

docs(firebase): improve docs 

---

src/build.ts

resolves https://github.com/unjs/nitro/issues/1560
This PR uses relative paths within tsconfig paths properties, normalising whatever is provided in paths/include/exclude.

fix: use relative paths in generated tsconfig

---

src/options.ts

Feels like this might be a good default when debugging.

feat: enable `timing` in debug mode

---

src/build.ts

https://github.com/unjs/nitro/issues/1560
This uses relative path for `#internal/nitro` replacement in `nitro-types.d.ts`

fix: use relative type path to nitro #internal/nitro

---

.github/workflows/ci.yml
package.json
src/rollup/config.ts
test/fixture/routes/error-stack.ts
test/tests.ts

Currently, we were always generating sourcemaps with absolute paths.
This PR makes nitro to follow default rollup behavior (generating relating sourcemap paths). This makes them portable (running in production assuming `.output` is adjustant to the same expected source structure and also in development mode.
It is worth to note that, we need `NODE_OPTIONS=--enable-source-maps` flag to lerage sourcemaps (documentation to be improved).
I have added a small test to make sure sourcemap works.

fix: use relative source map paths and add test 

---

package.json

closes #1583
Node.js 14 is not supported for Nitro build time anymore installations can be broken with ih.

fix(pkg): remove node 14 from supported `engines`

---

src/rollup/config.ts

We add `consola/core` alias to prevent circular dependency from unenv.

fix(rollup): add `consola/core` alias

---

src/presets/netlify.ts
src/presets/vercel.ts

resolves https://github.com/nuxt/nuxt/issues/22699
resolves https://github.com/unjs/nitro/issues/1602
Wrongly we were warning about legacy use of `swr` when `cache: false`.

fix(vercel,netlify): don't deprecate `swr` when `cache: false`

---

src/rollup/plugins/server-assets.ts

Closes https://github.com/oven-sh/bun/issues/3793
Bun does not always return a perfectly accurate string for `Function.prototype.toString`, so `normalizeKey` converted to a string will return:
```ts
function(key) {
...code..
}
```
In Node:
```ts
function normalizeKey(key) {
...code..
}
```
Nitro inlines this specific function into a generated source file, which will causes syntax error when building a Nitro project within the Bun runtime.

fix(build): workaround bun's difference in `function.toString()`

---

src/rollup/plugins/externals.ts

resolves #1598
related to #1367
This PR improves the contents of generated `.output/server/package.json` with using `dependencies` field for written packages information and also a generated name/version based on user's `package.json` and added `type: "module"` field as is our assumption.
Example: (with disabled `experimental.bundleRuntimeDependencies` flag)
```json
{
"name": "nitropack-prod",
"version": "2.5.2",
"type": "module",
"private": true,
"dependencies": {
"cookie-es": "1.0.0",
"defu": "6.1.2",
"destr": "2.0.1",
"h3-nightly": "1.8.1-1692089733.8af0474",
"hookable": "5.5.3",
"iron-webcrypto": "0.8.0",
"klona": "2.0.6",
"node-fetch-native": "1.2.0",
"ofetch": "1.1.1",
"ohash": "1.1.3",
"pathe": "1.1.1",
"radix3": "1.0.1",
"scule": "1.0.0",
"ufo": "1.2.0",
"uncrypto": "0.1.3", …
```

feat(externals): improved output `package.json`

---

src/presets/firebase.ts
src/rollup/plugins/externals.ts

- wip
- update
Since the Nitro externals plugin is already fully aware of written dependencies, and with improvements in #1607, we can simply try to read the already written `package.json` and try to update it. (however, we might not the updates either in the future by adding `main` and `engines` fields by default to the generated `package.json`

refactor(firebase): update generated `package.json` 

---

src/runtime/route-rules.ts

closes #1605
Currently we were using an additional layer of ofetch for handling proxy route rules (mainly to enable local fetch functionality). Using nitro app's fetch we can by pass this step.

perf: use local fetch for proxy route rules

---

src/runtime/app.ts
src/runtime/route-rules.ts

Fix regression with #1609 and netlify

fix: directly pass `localFetch` to route rules handler

---

docs/content/2.deploy/providers/firebase.md
src/presets/firebase.ts
src/runtime/entries/firebase-gen-1.ts
src/runtime/entries/firebase-gen-2.ts
src/runtime/entries/firebase-gen-default.ts
src/types/presets.ts

#266  
Adds a new option to nitro config that allows giving a custom name to deployed firebase functions.
This is done using rollup replace. I changed the exported name for the server in the firebase entry to `__firebaseServerFunctionName__` to ensure it is unique to the firebase server export. The placeholder name is then replaced with `firebase.serverFunctionName` in the config, which is given a default value of `"server"`.
This change gives an intuitive way to deploy multiple servers to the same firebase project without having them be overwritten. The workaround given in #266 is not very intuitive, and could potentially break other deployments in the future.
I would also recommend adding the same option to V2 functions in #1142, since there doesn't appear to be a way to change the …

feat(firebase): support renaming exported server function

---

src/runtime/entries/stormkit.ts

Stormkit requires buffer responses to be stringified AND be sent via `buffer` field instead of `body`.
This PR also updates types to match the underlying struct and normalized header.
Happy deployment: https://nuxt-image-remote-ipx.stormkit.dev/

fix(stormkit): properly send buffer responses

---

src/runtime/entries/aws-lambda.ts
src/runtime/entries/netlify-lambda.ts
src/runtime/entries/stormkit.ts
src/runtime/utils.lambda.ts
test/fixture/routes/stream.ts
test/presets/cloudflare-module.test.ts
test/presets/cloudflare-pages.test.ts
test/presets/cloudflare.test.ts
test/tests.ts

For lambda presets, we need to normalize `Uint8Array` to a Buffer (base64) and also read full streams since streaming (in general) is not supported.

feat: handle stream and Uint8Array for lambda presets

---

src/build.ts
test/fixture/nitro.config.ts

We now support ignoring public assets (https://github.com/unjs/nitro/pull/945) but at the moment we do not resolve/relativise paths, so an ignore pattern of `public/test.txt` would not match `test.txt` when scanning the `public/` directory. The issue is that it then becomes impossible to specify ignore patterns that _only_ apply in public directories, for example.
This is a **change in behaviour** but I think more intuitive.

fix: pass relative ignore paths when scanning public assets

---

src/runtime/cache.ts
test/fixture/types.ts

When updating h3 we missed out updating the generic types for `defineCachedEventHandler`. This PR implements it although note that this is not backwards compatible. (Happy to add an overload as we did in `h3` if we need to support previous generic pattern.)

fix: use new h3 generics for `defineCachedEventHandler`

---

src/runtime/entries/aws-lambda.ts
src/runtime/entries/netlify-lambda.ts

[#1274 PR](https://github.com/unjs/nitro/pull/1274)
[#22832 Nuxt](https://github.com/nuxt/nuxt/issues/22832)
[#852](https://github.com/unjs/nitro/issues/852)
I added the `isBase64Encoded` option to allow Lambda to understand that the request is a base64 encoded document.
I complete the PR [#1274](https://github.com/unjs/nitro/pull/1274) to solve this problem.

fix(aws-lambda, netlify): add `isBase64Encoded` response field

---

src/runtime/cache.ts
test/fixture/types.ts

https://github.com/unjs/nitro/pull/1640#issuecomment-1694230209
closes #1646
Quick improvement iterating on https://github.com/unjs/nitro/pull/1640. This will need to be improved when we add validator inference to `h3`'s event handler, and in future when headers might be added.

fix: exclude typed body from `cachedEventHandler`

---

src/runtime/static.ts

#1638 
It just changes `send(event, "")` to `return ""` in `304`。
It seems to be a problem with [h3](https://github.com/unjs/h3), if it returns undefined it will automatically jump to the next middleware

fix(static): send immediate empty responses for 304 handling

---

src/runtime/entries/firebase-gen-2.ts

Fixes #1655
Resolves #1655
firebase functions gen2 with region specified can be deployed.
Since there is no integrated test code that includes firebase deploy, I manually performed the following three tests.
1. have region and deploy to firebase.
```
export default defineNitroConfig({
firebase: {
gen: 2,
nodeVersion: "18",
httpsOptions: {
region: "asia-northeast1",
maxInstances: 3,
},
},
});
```
2. have no httpsOptions configuration and deploy to firebase.
```
export default defineNitroConfig({
firebase: {
gen: 2,
nodeVersion: "18",
},
});
```
3. have no region configuration and deploy to firebase.
```
export default defineNitroConfig({
firebase: {
gen: 2,
nodeVersion: "18",
httpsOptions: {
maxInstances: 3,
},
},
});
```
These three tests passed.

fix(firebase): apply region for gen2 deployments

---

src/options.ts

resolves https://github.com/nuxt/nuxt/issues/22038
Debugging another issue (https://github.com/nuxt/nuxt/issues/22038) noticed that output dirs were being resolved relative to `srcDir` in the absence of an explicit base.

fix: resolve output dirs relative to `rootDir`

---

test/tests.ts

Resolves #1461 
I was able to run the header tests locally for bun 0.8.1. However the same tests appear to be failing with the CI.
Investigating, I'm able to make the tests fail locally by downgrading my node version to 16, which match the CI behaviour.
I'm not sure why this is happening, but we can handle this the same way we handle deno

test: update test for bun headers

---

docs/content/2.deploy/providers/render.md

render.com uses node v14.17.0 by default and latest nuxt dependencies have a conflict with that. So the proposed change mentions how we can resolve the issue by adding a NODE_VERSION environment variable.
Issue #1692 
Resolves #1692

docs(render-com): add note about node version

---

docs/content/1.guide/0.getting-started.md

While attempting to test the latest Nitro edge release, I couldn't get Nuxt to build using the edge version, despite the console telling me that I was on the edge release. [See #1663](https://github.com/unjs/nitro/pull/1663#issuecomment-1703908120). @pi0 suggested to use the Nuxt edge release as it includes the Nitro edge release.
This PR adds a code example and a link to the relevant Nuxt docs.

docs: add instructions for using nuxt edge release channel

---

src/dev/error.ts
src/runtime/error.ts
src/runtime/renderer.ts

If not chaining send calls, h3 app may wrongly show 404 pages while response is being sent in next tick.

fix: await on `send()` calls

---

src/runtime/entries/aws-lambda.ts
src/runtime/entries/netlify-lambda.ts
src/runtime/entries/stormkit.ts
src/runtime/utils.lambda.ts
test/presets/aws-lambda.test.ts
test/tests.ts

Fix https://github.com/unjs/nitro/issues/852
The aws-lambda preset works with apigw v1 and v2. 
This PR fix the body type for apigw v2, and the cookies for apigw v1

fix(aws-lambda,netlify-lambda):  binary body v2 and cookies v1

---

src/presets/firebase.ts
src/rollup/plugins/externals.ts

It is critical to keep `package.json` consistent on each building. Some CI/CD, like Docker, shines when caching layer is defined to prevent a heavy-low compilation time. The problem is at each building, `package.json` is inconsistent (version 2.6.3).
In the generation, `sort` and `localeCompare` are called, but the comparison is evaluated only for the first char of each key.
This PR solve the problem, to compare each string instead of each char.
Thank you

fix: sort dependencies in `.output/package.json`

---

.github/workflows/autofix.yml
.github/workflows/ci.yml

Node.js 16 is almost EOL. We don't plan to "force upgrade" users by deliberately breaking Node.js 16 but also not guarantee supporting things working in EOL versions of Node.

ci: run tests against node 18

---

src/options.ts
src/types/nitro.ts

Node.js 16 is EOL and by disabling the polyfill from `node-fetch-native` package, we can save almost **%41** of the default bundle size!
This PR smartly enables `experimental.nodeFetchCompact` when Node.js 16 is being used with a warning to guide about an upgrade.
```
Node.js (current)
Σ Total size: 268 kB (69.9 kB gzip)
Node.js (native fetch)
Σ Total size: 158 kB (38.8 kB gzip)
```
We were also wrongly bundling polyfill for Bun which is not needed and it even saves more on bun (because of crypto export conditions mainly)
```
Bun (current)
Σ Total size: 255 kB (66.7 kB gzip)
Bun (native fetch)
Σ Total size: 146 kB (35.9 kB gzip)
```

perf: use native fetch for `node >= 18` to reduce `%40` of bundle size

---

docs/content/1.guide/7.plugins.md

See https://github.com/unjs/nitro/issues/1736#issuecomment-1724519928

docs: register error handler using hook instead of `hookOnce`

---

src/runtime/renderer.ts

This updates the handling of render response to allow directly returning a stream as well as a string.
Feedback welcome on concept. We could alternatively create a new helper that could handle other common stream-related issues.

fix(renderer): allow all h3 handled body types

---

docs/content/2.deploy/3.custom-presets.md

entry point `preset/index.ts` is not valid. According to the source code and [this ](https://github.com/unjs/nitro-preset-starter/tree/main/preset) example, I fixed `index.ts` -> `nitro.config.ts`.

docs: fix configuration file name of the custom preset

---

docs/content/2.deploy/providers/cloudflare.md

Added a build step to wrangler.toml example
Previously:
Any code changes would require a new `nitropack build` followed by restarting `wrangler dev`
Now:
`wrangler` watches the routes dir and `nitro.config.ts`. On change, `wrangler` dev rebuilds `nitro` Local dev experience when using `wrangler dev` now matches `nitropack dev`

docs(cloudflare): add local dev section

---

package.json
pnpm-lock.yaml
test/tests.ts

https://github.com/vitest-dev/vitest/releases/tag/v1.0.0-beta.0

chore: test with vitest `1.0.0-beta`

---

src/runtime/cache.ts

After the introduction of `captureError` API and integrating it with cache API, we removed explicit `console.error` logs when an issue happens for updating cache storage or evaluating SWR handler in the background.
This PR adds them back. As a future improvement, we might smartly show errors only if there is no error handler but it might also cause DX issues if all handlers are system handlers. So something to explore more later.

fix(cache): write swr and update errors to console

---

src/runtime/cache.ts

This PR makes sure any custom `validate` function is passing before sending stale cache value and revalidating in background

fix(cache): only return validated stale value

---

src/runtime/cache.ts

Unless a custom validator function returns `false`, it should be considered as valid to avoid implicit returns being considered invalid.

fix(cache): only invalidate if `validate` returns `false`

---

docs/content/3.config.md
src/options.ts
src/prerender.ts
src/types/nitro.ts
src/utils/index.ts

Resolves https://github.com/unjs/nitro/issues/1469
The prerender by default will fail if a page fails to render. This PR changes the default behaviour to 3 attempts before failure. 
This also adds 2 configuration options `nitro.options.prerender.tries` and `nitro.options.prerender.retryDelay` to change the behaviour. `tries` can be set to`Inifinity`if someones wants the pre-render to try endlessly.
For the default values, I've arbitrarily chose 2 retries and a 250ms retry delay.
We could nest the options: `nitro.options.prerender.retry.attempts` and `nitro.options.prerender.retry.delay`.

feat(prerender): support `retry` and `retryDelay`

---

src/runtime/cache.ts

#1837
cookie headers can be repeated, adapted from 
https://github.com/unjs/h3/blob/b7aca9614e7e8e8921fd54804463ce78fdb034f1/src/utils/response.ts#L341
I tried writing a test case for this but stuff didnt work as expected (doesnt help that my work PC is kinda locked down and on windows...), but I tested via playground and in my original nuxt project

fix(cache): allow setting multiple `set-cookie` headers (bad practice)

---

.github/workflows/ci.yml
test/tests.ts

Node.js introduced a breaking behavior change by renaming `Response` constrocutor name to `_Response`. Seems undici code is intact and a build tool chain issue! (~> https://github.com/nodejs/node/issues/50257)

test: update reponse type check

---

.github/workflows/ci.yml
docs/content/1.guide/0.getting-started.md
scripts/bump-nightly.ts
scripts/release-nightly.sh

- chore: switch to `nitropack-nightly` from `nitropack-edge`
- allow testing ci directly

chore: use `nitropack-nightly` for nightly release channel

---

src/types/serialize.ts
test/fixture/types.ts

resolves https://github.com/unjs/nitro/issues/1845#issuecomment-1773873726
This is largely a DX improvement, but we should check that it doesn't have a significant performance cost when used.

fix: recursively simplify returned objects

---

src/runtime/cache.ts

#1850
A regression from [v2.7.0](https://github.com/unjs/nitro/releases/tag/v2.7.0) cached the `etag` and `last-modified` headers of cached handler entities to become `undefined`. 
#1855 fixes the issue but if any production deployment used faulty behavior of 2.7.0, they could keep invalid entities in the cache until maxAge reaches.
This PR adds a core hotfix for this unfortunate incident and will be reverted after a while.

fix(cache): invalidate wrongly cached  handler entities

---

src/presets/cloudflare-pages.ts

resolves https://github.com/unjs/nitro/issues/1844
Cloudflare doesn't expect to have overlapping public assets dirs. This prevents using overlapping dirs, preferring instead the top level dir if it overlaps a child dir.

fix(cloudflare-pages): filter out overlapping public assets dirs

---

src/rollup/plugins/public-assets.ts
src/runtime/virtual/public-assets.d.ts
src/types/nitro.ts

Extracted from #1863.
This new mode allows for edge conditions that it is only possible to serve static assets using their inline value. 
Also makes refactors for future improvements in public asset plugin.

feat: support `inline` mode for `serveStatic`

---

src/options.ts

Resolves #1860
This allows setting nitro preset using `SERVER_PRESET` instead of `NITRO_PRESET`.

feat: allow setting preset using `SERVER_PRESET` environment variable

---

docs/content/1.guide/3.routing.md

Better describe middleware and how returning within it behaves
This improves on documentation. Before it stated that **they should not return anything**, which is untrue - returning from middleware returns the value as a response.

docs(routing): add note about middleware returns

---

src/scan.ts
test/fixture/api/methods/foo.get.get.ts
test/fixture/api/methods/get.ts
test/tests.ts

Partial fix for #1378
This change allows having an extra method as part of the file name. The last segment will be still removed as extension so `routes/foo.get.get.ts` will be mapped to `/foo.get` but `routes/foo.get.ts` to `/foo` (GET) as before.

fix(scanner): allow having http method as part of the route name

---

src/build.ts

Resolves #1378
We were not resolving event handler paths for generating types and also removing any last `.*` segment. So if input is `~/foo.get`, generated type would be something like `../~/foo`.
This PR both resolves paths and strips only known extension from last (it is unnecessary but as another safety measure)

fix: generate route typed with resolve path and stripped extension

---

docs/content/2.deploy/20.providers/cloudflare.md
src/presets/cloudflare-module.ts
src/presets/cloudflare-pages.ts
test/presets/cloudflare-pages.test.ts

remove the NITRO_EXP_CLOUDFLARE_DYNAMIC_IMPORTS flag (added in https://github.com/unjs/nitro/pull/1172) used to enable code splitting with lazy loading for the cloudflare-pages and cloudflare_module presets and enable such behavior by default since that is not stable and working with up-to-date versions of wrangler
For the stability of this feature please have a look at these reproductions: https://github.com/dario-piotrowicz/nitro-nuxt-lazy-loading-test/tree/main
They show that things do work fine (both locally and in production) when using lazy loading :muscle:

feat(cloudflare-pages, cloudflare-module): enable code splitting by default

---

docs/content/2.deploy/0.index.md
docs/content/2.deploy/20.providers/aws-amplify.md
src/presets/aws-amplify.ts
src/runtime/entries/aws-amplify.ts
src/types/presets/aws-amplify.ts
src/types/presets/index.ts

Resolves #80
Note: AWS Amplify support is still in progress with amplify team collaboration 🚀 (special thanks to @Narrator)

feat: add aws amplify hosting preset

---

src/prerender.ts

resolves https://github.com/nuxt/nuxt/issues/22660
closes https://github.com/nuxt/nuxt/pull/24320
When a link is rendered in HTML (e.g. by vue router) with URI components, Nitro currently does not decode these when requesting the URL, which can cause double encoding and a 404 from vue-router.
Instead we should likely decode the link at source, just as we do with headers.

fix(prerender): decode generated routes

---

package.json
pnpm-lock.yaml
src/rollup/config.ts
src/rollup/plugins/externals-legacy.ts
src/rollup/plugins/externals.ts
src/rollup/plugins/wasm.ts

resolves #1794 
Upgrade to [rollup v4](https://github.com/rollup/rollup/releases/tag/v4.0.0)
- Almost a month passed enough for ecosystem adoption (1)
- Vite v5 is out powered by roll-up v4 (https://vitejs.dev/blog/announcing-vite5)
- Additional ecosystem tests via Nuxt are pending for nightly
- This makes the minimum Node.js version for (building) Nitro to v18
- 
(1) Dependency issues: Only `rollup-plugin-visualizer` seems behind now:
```
 WARN  Issues with peer dependencies found
.
└─┬ rollup-plugin-visualizer 5.9.2
└── ✕ unmet peer rollup@"2.x || 3.x": found 4.5.0
```

feat: upgrade to rollup v4

---

src/build.ts
src/dev/server.ts
src/types/nitro.ts

This PR improves usability of build info file (`nitro.json`) by adding nitro version, new framework info and also writing it for development mode with worker info (particularly usable for #1929 CLI integration). Also new `NitroBuildInfo` type is exposed

feat: improve `nitro.json` build info

---

src/prerender.ts

https://github.com/unjs/nitro/pull/1914
https://github.com/nuxt/nuxt/actions/runs/6923600748/job/18832536383?pr=24370#step:13:66
Because we are using the scanned links to create a new URL we need to ensure they are decoded first:
https://github.com/unjs/nitro/blob/df7091dc9593b19977b6183497746e0e97a8b44f/src/prerender.ts#L396-L404

fix(prerender): decode uris in headers

---

src/runtime/utils.ts

Requests made with the Fetch API cause `sec-fetch-mode` to be set, leading to these requests to be identified as JSON requests. The default error handler uses isJsonRequest to render errors. If a request were to set the Accept header to "text/html" the response should be HTML as well.
#1919 
`isJsonRequest` is modified, its only usage (within nitro) is by the default event handler to determine when to serialize errors as HTML or JSON.
This change is needed because requests made with the Fetch API automatically get the `sec-fetch-mode=cors` header. This header is one of the conditions by which `isJsonRequest` function identifies JSON, but the header has no such meaning as far as the standard is concerned.
More importantly, the function does not provide any means to enforce an HTML response …

fix(error): respect `accept: text/html` request header

---

docs/content/1.guide/5.cache.md

docs(cache): make default value `swr: true` more clear

---

src/runtime/entries/netlify-lambda.ts

#1719
This PR corrects encoding on `netlify-lambda` when posting base64 encoded body. It's similar to #1779.

fix(netlify-lambda): handle base64 encoded body

---

docs/content/3.config.md
src/prerender.ts
src/types/nitro.ts

This supports `prerender.ignore` as regular expressions or functions that accept a path and return a boolean.

feat: support function/RegExp for `prerender.ignore`

---

.github/workflows/ci.yml

I figured I would try https://github.com/unjs/nitro/pull/1831 by using the nightly release, but the job did not get triggered as one of the squashed commits in the merge message contains `'chore'`. 
We used to have the same issue for `@nuxtjs/i18n`, this changes the conditional to only check start of the commit message instead of including the squashed commits. I'll check other repositories and open a PR to add this.

ci: fix nightly release job conditional

---

docs/content/1.guide/3.routing.md

Due to getRequestURL returning a URL, the example of request filtering might be misleading for newcomers. This PR fixes the documentation to comply with its return type.

docs(routing): update request filtering to match the type of getRequestURL

---

package.json
pnpm-lock.yaml
src/rollup/plugins/wasm.ts

#1952
When annotating wasm (virtual) chunk dependencies with `external: true`, roll-up sometimes reverts them to the original external package as external in the bundle.
This PR uses a virtual module (non-externalized) + post-build transform to convert it to relative import to avoid rollup interfering.
**Note:** when option is enabled for iife/umd targets (cloudflare preset) the experimental module is still unsupported now with more explicit check.

fix(wasm): directly generate chunk exports

---

src/presets/cloudflare-module.ts
src/presets/cloudflare.ts

`wrangler dev` doesn't require `--local` anymore (and it will be removed in a future major version) so it should be removed from the cloudflare preview commands
See:

refactor(cloudflare): remove `--local` from perview commands

---

src/presets/cloudflare-module.ts

I just spotted an unused import in the `cloudflare-module.ts` file and figured I could remove it :stuck_out_tongue:

refactor(cloudflare): remove unused import

---

src/rollup/config.ts
src/rollup/plugins/wasm.ts

Generated chunk names went out of maintenance over the time. This PR is mainly an initial attempt to organize chunk names generated in `.output/server/chunks` into categorized directories.

refactor(rollup): improve generated chunk names

---

src/presets/iis.ts

https://github.com/nuxt/nuxt/issues/22961
Uses a more general fix than #1783 based on #1697

fix(iisnode): correctly escape backslashes for port fix

---

docs/content/3.config.md

none
https://github.com/unjs/h3/blob/53703dc860f1ff6fe7ce71d543deff1cfa810b11/src/utils/response.ts#L120
cause error
```
[nitro] [unhandledRejection] TypeError: Cannot read properties of undefined (reading 'res')
at setResponseHeader (file:///data/workspace/node_modules/.pnpm/h3@1.9.0/node_modules/h3/dist/index.mjs:730:14)
at file:///data/workspace/.nitro/dev/index.mjs:512:3
at Object.onError (file:///data/workspace/.nitro/dev/index.mjs:552:14)
at Server.toNodeHandle (file:///data/workspace/node_modules/.pnpm/h3@1.9.0/node_modules/h3/dist/index.mjs:1892:27)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

docs(config): fix `setResponseHeader` example params

---

docs/content/2.deploy/20.providers/netlify.md

fix #2032
Update the documentation to warn users to update the publish directory to `dist` when using Netlify.
By default, Netlify will use `.nuxt/dist` which is not correct and this will break the deployment.

docs(netlify): add note to make sure publish dist is set to `dist`

---

docs/content/2.deploy/20.providers/cloudflare.md

In the cloudflare docs page I've found outdated/incorrect details which I am amending here.
Besides that I am also updating and improving some other few bits.
To see the what the various changes are please look at the commit messages.

docs(cloudflare): various updates, cleanups and fixes

---

src/runtime/routes/openapi.ts

I just found it and fixed it directly
The `servers` property of the generated openAPI spec doesnt taske the baseURL property in the nitro config into account.
This change fixes that.

fix: add `baseURL` to openapi generated url

---

src/presets/azure.ts

resolves #1872
- Support `16`, `18` and `20` for node versions
- Default to `18`
- Drop legacy 18

fix(azure): add `18` and `20` to supported node versions

---

src/runtime/entries/azure.ts

resolves #100
When sending a binary/Buffer response, azure natively handles it and we don't need to stringify it. (Note: h3 stringifies objects and alike already)
PS: I locally confirmed working based on tests in #2076

fix(azure): pass body to the context as-is

---

docs/content/1.guide/4.storage.md

I know there is already a PR with storage docs changes (#2086), but I could see that it did not contain fixes for the "dead" links to unstorage, so I went ahead and fixes them in this PR.

docs(storage): fix unstorage links

---

src/rollup/config.ts

#1991
Resolves #1991 
This change uses the full build consola in development mode. It might be confusing if the behavior in development mode and production mode is different, maybe it would be worth writing about this in the documentation?

fix: only mock consola in production

---

docs/content/1.guide/6.assets.md

docs: update the assets page

---

docs/content/2.deploy/0.index.md
docs/content/2.deploy/20.providers/cloudflare.md

This PR updates the Cloudflare deployment docs by:
- making the `cloudflare_pages` preset the recommended one
- making the worker presets deprecated
- giving more information regarding Bindings
- applying other cleanups
Besides the Cloudflare docs update this PR also includes small changes to the deployment overview doc to hopefully slightly clarify things

docs(cloudflare): update deployment guide

---

src/build.ts

This mirrors the Nuxt update in https://github.com/nuxt/nuxt/pull/24837 to default to bundler module resolution.

fix: default to `bundler` module resolution

---

docs/content/1.guide/1.configuration.md
docs/content/1.guide/3.routing.md

Links to /auto-imports now correctly guide to /guide/auto-imports

docs: fix links to /guide/auto-imports

---

src/presets/github-pages.ts

Without `--dotfiles` `gh-pages` does not deploy `.nojekyl`
Ref: https://www.npmjs.com/package/gh-pages#optionsdotfiles

refactor(github-pages): add `--dotfiles` to deploy command hint

---

src/runtime/cache.ts

#2177 
It seems that there is nothing particularly noteworthy (no breaking change) 🤣

feat(cache): support async `shouldBypassCache` and `shouldInvalidateCache`

---

src/dev/server.ts

fix(dev):`remoteAddress` might be undefined for `x-forwarded-for`

---

src/runtime/task.ts

This is a rather lazy fix for the (experimental) scheduled tasks that if run in the testing environment, can cause tests to hang. 
Later we might think of utils to emulate scheduled tasks within testing environment without making side-effects.

fix: disable scheduled tasks in testing environment

---

docs/2.deploy/20.providers/cloudflare.md
docs/2.deploy/20.providers/stormkit.md

Only the [Cloudflare](https://nitro.unjs.io/deploy/providers/cloudflare) page did not have a link to the [Zero-Config Providers](https://nitro.unjs.io/deploy#zero-config-providers).
( Confirmed that AWS Amplify, Azure, Netlify, Vercel and Zeabur are fine. 🙆 )

docs(deploy): add link to zero config providers

---

src/rollup/plugins/database.ts

When using:
```ts
export default defineNitroConfig({
experimental: {
database: true
},
database: {
default: {
connector: "cloudflare-d1",
options: {
bindingName: "TEST"
}
}
}
});
```
We had this error:
```bash
[nitro 6:40:47 PM]  ERROR  RollupError: Expected ',', got '-' (Note that you need plugins to import files that are not JavaScript)
1: 
2: import cloudflare-d1Connector from "db0/connectors/cloudflare-d1";
^
3: 
4: export const connectionConfigs = {
```
Using `camelCase` from `scule` make sure to ovoid this error :)
Also add a PR to `db0` to improve the error message too: https://github.com/unjs/db0/pull/60

fix(database): camelCase the connector name

---

src/rollup/plugins/raw.ts

Resolves https://github.com/unjs/nitro/issues/2217
This PR adds more extensions which are definitely not binary files.

fix(server-assets): mark `yaml`, `json`, `json5` and `csv` as text

---

src/build.ts
test/fixture/nitro.config.ts
test/fixture/public/_unignored.txt
test/presets/cloudflare-pages.test.ts
test/tests.ts

Discovered while triaging issue with https://github.com/nuxt/nuxt/pull/26203, we basically weren't handling ignore patterns beginning with `!` if they did not also start with `!*`. (They would end up as part of a directory name.)

fix: handle path negations when scanning public assets

---

docs/1.guide/8.assets.md

In current docs, there is a bad example path for server assets ([here](https://nitro.unjs.io/guide/assets#server-assets))
the path `/assets/server/...` is not correct

docs: fix server assets example path

---

docs/1.guide/6.cache.md

docs: remove duplicate `integrity` key

---

docs/1.guide/10.tasks.md

—
Provide a more detailed example regarding the payload usage, and what should the JSON payload look like.

docs(tasks): update dev server usage

---

docs/1.guide/6.cache.md

The `cache.varies` option for `routeRules` needs to be better documented to help understand the cache behavior and discarded headers, especially related to multi-tenant implementations.
The explanation is not currently obvious when reading through the docs; however, was better explained in https://github.com/nuxt/nuxt/issues/26102#issuecomment-1980625833 by @pi0. This PR surfaces the explanation and provides docs visitors a keyword of "tenant" they can search for as a hint. (It took me 3 days to figure out why my `host` headers were returning `localhost` 😅 )
I also created a corresponding PR for the Nuxt docs: https://github.com/nuxt/nuxt/pull/26197

docs(cache): add example usage for `cache.varies`

---

src/runtime/routes/openapi.ts

#2215 
Currently, openapi is only available in dev, so there is no runtime difference to be determined here 🥰

fix(openapi): use dynamic host + port

---

docs/1.guide/2.routing.md

I think that the example doesn't give clarity to basic user regarding middleware execution, have added 0 in from of the numbers, and an info message for clarities sake.
Here is a basic repro
https://stackblitz.com/edit/github-ph5sly?file=server%2Froutes%2Findex.ts

docs: add note about middleware execution order 

---

docs/1.guide/2.routing.md

#2280
This just fixes the dead link for `Object Syntax Event Handler` and now points to the h3 documentation.

docs(routing): fx link to h3 object syntax handler

---

src/nitro.ts
src/options.ts

Fixes #2283, related to https://github.com/nuxt/devtools/pull/626
Nitro config types indicate that `nitro.options.scheduledTasks` should always be an object, empty or not.  This PR makes the property an empty object as default as opposed to `undefined` which is not assignable to
```ts
scheduledTasks: { [cron: string]: string | string[] }
```

fix(options): set `scheduledTasks` to an empty object by default

---

src/prerender.ts
src/runtime/entries/nitro-prerenderer.ts

Discovered while investigating original reproduction in nuxt/cli#193.
Nitro prerenderer was never calling nitro 'close' hook which meant there was no way for runtime code to clean up after itself.
resolves nuxt/cli#193

fix(prerender): call `nitroApp` close hook when done prerendering

---

src/types/serialize.ts
test/fixture/types.ts

resolves https://github.com/unjs/nitro/issues/1762
resolves https://github.com/nuxt/nuxt/issues/26411
Currently, `Serialize<undefined>` resolves to `never` (matching `T extends NonJsonPrimitive`). This PR returns `T` from `Serialize` when it extends `undefined`.

fix(types): return `T` from `Serialize` when it extends `undefined`

---

src/rollup/plugins/raw.ts

* https://github.com/nuxt-modules/i18n/issues/2835
* Related https://github.com/unjs/nitro/pull/2229
* Related https://github.com/unjs/nitro/pull/2239
Nuxt I18n is running into issues specifically with `yaml` files since nitro `2.9.2+`, I think because we're trying to parse and transform the file ourselves but it's already been handled as a raw file? 
Let me know if this is not the correct way to resolve this or if there is a way for us to exclude specific files from being handled, I'm following this PR https://github.com/unjs/nitro/pull/2239 as an example (it looks like it added checks for yaml as well anyway).

fix(raw): exclude `yaml` from raw plugin

---

src/presets/cloudflare-pages.ts

(context: reported in solid discord channel)
This PR enables writing `_headers` and `_redirects` file for cloudflare pages (non static). This resolves respecting header rules but also allows leveraging more CDN native primitives.
Example `_headers`:
```
/rules/headers
cache-control: s-maxage=60
/rules/cors
access-control-allow-origin: *
access-control-allow-methods: GET
access-control-allow-headers: *
access-control-max-age: 0
/rules/nested/*
x-test: test
/build/*
cache-control: public, max-age=3600, immutable
```
Example `_redirects`
```
/rules/nested/override	/other	307
/rules/redirect/wildcard/*	https://nitro.unjs.io/**	307
/rules/redirect/obj	https://nitro.unjs.io/	308
/rules/nested/*	/base	307
/rules/redirect	/base	307
```

fix(cloudflare-pages): write `_headers` and `_redirects` 

---

src/runtime/routes/openapi.ts

–
1) The OpenAPI file we’re generating is set to be OpenAPI 3.0, which is fine. But we can safely make it 3.1, as this just has additions to the 3.0 specification. In other words: What works in 3.0, works in 3.1, too.
2) ~~I’ve also removed the URL description from the OpenAPI file. Currently, the OpenAPI stuff is only rendered in local development, but we’d probably want to enable a production-use of it, too and the request URL is already dynamic.~~
3) The `schemes` property came from Swagger 2.0 and we can safely remove it here.
Looking forward to get your feedback!

refactor(openapi): upgrade to openapi 3.1 

---

src/build.ts

context: https://github.com/un/inbox/pull/175
This adds missing types for `~`, `~~`, `@` and `@@` aliases when nitro is used on its own (without nuxt, for example).

fix: generate root/src directory aliases

---

src/types/fetch.ts

https://github.com/nuxt/nuxt/issues/26411
This is a continuation of https://github.com/unjs/nitro/pull/2286 which will fix not inferring `undefined` from server routes (checked this locally and works great).
The origin of the `Exclude` wrapper:
https://github.com/unjs/nitro/blame/adb6c5d1c7820feef63ed0851d7850f04d98ebb1/src/types/fetch.ts#L13
Confirmed with @danielroe whether there was any specific reason for excluding `Error | void` and he's not aware (hence it might be redundant but worth double checking).

fix(types): account for `undefined` value for `$fetch` return type

---

src/presets/github-pages.ts

fixes #2333 
resolves #2333 . adds "/" to the list of prerendered routes for `github-pages` preset

fix(github-pages): prerender `/` by default

---

src/runtime/routes/swagger.ts

#2297 upgraded OpenAPI to version 3.1, requiring adjustments here as well.

refactor(openapi): update swagger-ui version to v5 for OpenAPI v3.1 support

---

docs/1.guide/6.cache.md

The `base` cache option was documented twice.

docs(cache): remove duplicate option definition

---

src/presets/cloudflare-pages.ts

Continuation of https://github.com/unjs/nitro/pull/2353 and related to https://github.com/cloudflare/workers-sdk/issues/5579.
This PR updates generated `wrangler.toml` path to top-level dir in case of CI and build dir in case of local builds to allow extending.

refactor(cloudflare-pages): update root `wrangler.toml` in CI

---

src/presets/cloudflare-pages.ts

We should not create an empty `wrangler.toml` to keep CF CI uses the dashboard bindings.

chore(cf-pages): only create wrangler.toml if config is not empty

---

src/presets/deno-server.ts

fix 1/2
It seems with latest 1.x version of Deno, a regression requires it strictly and global polyfill is not effective.
This PR also moves to use explicit `node:` specificier prefix.

fix(deno-server): always inject `process` from `node:process`

---

src/presets/deno-server.ts
src/runtime/entries/deno-server.ts

continuation of https://github.com/unjs/nitro/pull/2372 (reverting other fix for now to investigate more)
Seems a regression behavior after https://github.com/denoland/deno/pull/23289 internal `hasTlsKeyPairOptions` fails if propers `cert` and `key` exist in options even if undefined.

fix(deno-server): explicitly remove cert/key from options if either is not set

---

docs/2.deploy/10.runtimes/1.node.md

#2376 
This PR updates the documentation about the `NITRO_SHUTDOWN` env variable. Indeed, in the codebase, `NITRO_SHUTDOWN_DISABLED` is used.
Resolves #2376

docs: correct env variable to `NITRO_SHUTDOWN_DISABLED`

---

.github/ISSUE_TEMPLATE/bug-report.yml
CHANGELOG.md
SECURITY.md
docs/1.guide/0.index.md
docs/1.guide/2.routing.md
docs/2.deploy/20.providers/edgio.md
docs/2.deploy/20.providers/github-pages.md
docs/3.config/0.index.md
scripts/release-nightly.sh
src/cli/commands/build.ts
src/compress.ts
src/presets/firebase.ts
src/rollup/plugins/externals.ts
src/runtime/cache.ts
src/scan.ts
src/types/presets/aws-amplify.ts
test/tests.ts

chore: fix typos

---

src/rollup/config.ts

Noticed when trying out https://github.com/pi0/nitro-cloudflare-dev/blob/main/src/index.ts that multiple copies of the same plugin were injected; this caused the following error:
```
[nitro 14:30:29]  ERROR  RollupError: virtual:#internal/nitro/virtual/plugins (6:7): Identifier "_BsBwid0Z5r" has already been declared
4: import _3SMM7tZjad from '/Users/daniel/code/danielroe/carpenter/node_modules/.pnpm/@nuxthub+core@0.5.11_ioredis@5.4.1...
5: import _BsBwid0Z5r from '/Users/daniel/code/danielroe/carpenter/node_modules/.pnpm/nitro-cloudflare-dev@0.1.4/node_mo...
6: import _BsBwid0Z5r from '/Users/daniel/code/danielroe/carpenter/node_modules/.pnpm/nitro-cloudflare-dev@0.1.4/node_mo...
^
7: 
8: export const plugins = [
```
The issue was user error - I was also using `@nuxthub/core` - but …

fix: deduplicate plugins

---

src/runtime/types.ts

hi :wave: this PR converts `CapturedErrorContext` to an interface to allow users and module authors to augment this type .

refactor: convert `CapturedErrorContext` to interface to allow type augmentation

---

src/rollup/config.ts

Discussion: https://github.com/unjs/nitro/discussions/2392
Adds TSX/JSX to `@rollup/plugin-node-resolve` to allow import in routes/api files.
Here a [StackBlitz](https://stackblitz.com/edit/unjs-nitro-jsx-resolve-issue?file=server%2Froutes%2Findex.tsx) reproduction based in the [nano-jsx](https://github.com/unjs/nitro/blob/main/examples/nano-jsx/routes/%5B...path%5D.tsx) example.
When run the app, shows up `RollupError: Could not resolve "../components/Hello" from "server/routes/index.tsx"`
But if add the `.jsx` and `.tsx` to `node-resolve` it works

fix: add `.tsx` and `.jsx` to `node-resolve` extensions

---

src/runtime/utils.azure.ts

#2399
In the utils that sets cookies for Azure, it is lowercasing the cookie keys at line 24, so `Max-Age` becomes `max-age`:
const setCookieOptions = Object.fromEntries(
_setCookieOptions.map(([k, v]) => [k.toLowerCase(), v])
);
But uses another undefined key a few lines later:
maxAge: parseNumber(setCookieOptions.maxAge),

fix(azure): correctly handle maxAge cookie option

---

docs/1.guide/0.index.md

Fixes incorrectly singularized directory name in documentation

docs: correct directory name

---

docs/2.deploy/20.providers/gitlab-pages.md
src/presets/gitlab-pages.ts
src/presets/index.ts

resolves https://github.com/unjs/nitro/issues/2344
This adds a new `gitlab-pages` provider.

feat(providers): add `gitlab-pages` static provider

---

docs/2.deploy/20.providers/github-pages.md
docs/2.deploy/20.providers/gitlab-pages.md
docs/2.deploy/20.providers/render.md

https://github.com/unjs/nitro/pull/2420#discussion_r1592501347
This simplifies some of the docs by using `nypm` 🚀

docs: use `npx nypm install` in instead of `npm install`

---

src/runtime/entries/aws-lambda-streaming.ts

quick fix for aws-lambda-streaming global import being incorrect

fix(aws-lambda-streaming): fix global lambda import pointing to wrong

---

src/presets/iis/utils.ts

for test script
```js
const { defu } = require("defu");
const { Builder, Parser } = require("xml2js");
const originalString = /* xml */ `<?xml version="1.0" encoding="utf-8"?>
<configuration>
<system.webServer>
<webSocket enabled="false" />
<handlers>
<add name="iisnode" path="index.js" verb="*" modules="iisnode" />
</handlers>
<rewrite>
<rules>
<rule name="NodeInspector" patternSyntax="ECMAScript" stopProcessing="true">
<match url="^index.js/debug[/]?" />
</rule>
<rule name="StaticContent">
<action type="Rewrite" url="public{PATH_INFO}" />
</rule>
<rule name="DynamicContent">
<conditions>
<add input="{REQUEST_FILENAME}" matchType="IsFile" negate="True" />
</conditions>
<action type="Rewrite" url="index.js" />
</rule>
</rules>
</rewrite>
<security>
<requestFiltering>
<hiddenSegments> …
```

fix(preset-iis): parse without  `explicitArray` to allow merging `web.config` 

---

src/prerender.ts
src/presets/_nitro/nitro-prerender.ts

Closes #2444
This allows the `rollupConfig.options.output.entryFileNames` to be passed to the nitro prerenderer if its a string, with the fallback to `index.mjs`. This fixes an issue where prerendering fails if a custom entry filename is used.

fix: pass custom entry filename when resolving prerenderer

---

src/presets/vercel/preset.ts
src/presets/vercel/utils.ts

resolves https://github.com/nuxt/nuxt/issues/26886
resolves https://github.com/nuxt/nuxt/issues/21780
resolves https://github.com/unjs/nitro/issues/1348
It's possible to deploy sites to Vercel with a custom `baseURL` and the renderer will correctly handle 404 on `/` and correct responses from `/<baseURL>/` but the public assets aren't configured to respect the `baseURL`.
Published minimal reproduction & patch to https://github.com/danielroe/nuxt-3-vercel-baseurl-test - you can see deployed at https://nuxt-3-vercel-baseurl-test-tan.vercel.app/subdir.
You can confirm that correct headers are added to a request like:
```sh
http --headers https://nuxt-3-vercel-baseurl-test-tan.vercel.app/subdir/_nuxt/C7CLbNSw.js
> HTTP/1.1 200 OK
> Access-Control-Allow-Origin: *
> Age: 88
> Cache-Control: …
```

fix(vercel): support custom `baseURL`

---

src/build.ts

https://github.com/nuxt/nuxt/issues/24869
By emitting relative paths in `nitro-config.d.ts`, we ensure that the types still work when developing in a Docker container where the absolute path does not match the path the IDE is running in.

fix: use relative paths in `nitro-config.d.ts`

---

docs/1.guide/97.configuration.md

From my testing, I need to prefix `NITRO_` in .env file to make it work

docs: prefix `NITRO_` in `.env` file

---

src/core/build/types.ts
src/rollup/config.ts
src/runtime/_compat/app.ts
src/runtime/_compat/error.ts
src/runtime/_compat/index.ts
src/runtime/_compat/utils.ts
src/runtime/app.ts
src/runtime/cache.ts
src/runtime/config.ts
src/runtime/context.ts
src/runtime/database.ts
src/runtime/error.ts
src/runtime/plugin.ts
src/runtime/storage.ts
src/runtime/task.ts
src/runtime/utils.ts
tsconfig.json

With #2473 refactors, all runtime imports should be from `nitropack/runtime`.
This PR resolves #2499 (for `nitropack/runtime/plugin`) and possible cases alike that users used `nitropack/runtime/*` and `#internal/nitro/*` paths:
- `nitropack/runtime/app`
- `nitropack/runtime/cache`
- `nitropack/runtime/config`
- `nitropack/runtime/context`
- `nitropack/runtime/database`
- `nitropack/runtime/error`
- `nitropack/runtime/plugin`
- `nitropack/runtime/strorage`
- `nitropack/runtime/task`
- `nitropack/runtime/utils`

fix: more compatibility for import from `nitropack/runtime/*`

---

src/core/build/dev.ts

Nitro supports customizing `apiDir` and `routesDir`, but continues to watch the creation/deletion of files *only* in the default `"api"` and `"routes"` folders.
This PR simply configures the watcher to use the configured ones if provided 🙂

fix(build): correctly watch custom `apiDir` and `routesDir`

---

src/rollup/plugins/public-assets.ts

Encountered this as a side effect of replicating another bug.
Registering public asset dir with a base URL of, say, `/custom` will lead to paths like `/custom-thing` also being handled by the same handler (and returning a hard 404 if fallthrough is disabled). This is because we do not test if the path begins with `/custom/` but with `/custom`.
Let me know if you need me to provide a reproduction. I think the problem and fix are straightforward to see, but happy to do so!

fix(public-assets): do not shadow paths that share prefix

---

src/core/module.ts

https://github.com/unjs/nitro/issues/2512
This enables `esmResolve` for loading modules, so that subpaths are correctly imported.

fix(core): resolve modules with esm compatibility

---

src/core/prerender/prerender.ts
test/fixture/nitro.config.ts
test/fixture/routes/prerender-custom.html.ts
test/fixture/routes/prerender.ts
test/presets/azure.test.ts
test/presets/cloudflare-pages.test.ts

Discovered while triaging https://github.com/nuxt/nuxt/issues/27490 (which is a bug in Nuxt). We are not crawling paths that are prerendered with an explicit `.html` suffix.
It feels like this might be an oversight, and we could benefit from this in Nuxt (adding prerender headers when rendering `200.html`) but if you think it might pose any issues, feel free to close.

fix(prerender): extract links from explicit html routes

---

src/runtime/internal/cache.ts
src/types/h3.ts
test/fixture/api/cached.ts
test/tests.ts

This allow the frontend framework connected to Nitro to be aware that the page is cached, useful for handling a flag in the payload to handle a different logic on client-side (e.g: fetch the auth state after hydration)

feat(defineCachedEventHandler): add `event.context.cache`

---

src/core/config/resolvers/fetch.ts
src/types/config.ts

this PR drops `nodeFetchCompat` flag, always defaulting `node-fetch-native` to the platform `fetch` and disable from build since Node 16 is not supported anymore. 
Escape hatch: Using `alias` config, node-fetch-native can still be overriden

refactor!: always use native fetch in builds

---

src/core/build/types.ts

This is a remake of https://github.com/unjs/nitro/pull/2532, but for main branch... (Just close whichever PR is not relevant.)
This increases strictness for the generated `tsconfig.json`. The most significant change, I think, is `noUncheckedIndexedAccess` - feel free to remove if you think this is too much! (But of course it can always be disabled by end user.

feat!: increase generated `tsconfig.json` strictness

---

src/core/config/resolvers/runtime-config.ts

https://github.com/nuxt/nuxt/pull/21466
https://github.com/nuxt/nuxt/issues/13992
Users may be under the impression they can set anything on runtimeConfig, e.g. Set(), Map(), functions, etc. This tries to check if it's a valid JSON object and if not - warn.

feat(core): warn if runtime config is not serializable

---

src/presets/node/runtime/cli.ts

Part of implementing #2466 
The generated `server/index.mjs` is no longer dependent on the `require`.
Also, it uses `Object.entries` for result headers.

fix: upate `cli` preset with esm module format

---

src/core/index.ts
src/core/nitro.ts

This runs `scanHandlers`, which is required to run before `writeTypes` to ensure the return types for the handlers are present + correctly generated:
https://github.com/unjs/nitro/blob/7e0b49ef63f1404657d875543bcbbec6c2a4d6b9/src/core/build/types.ts#L25
I've placed it after running modules so that they could update the directories to be scanned, if required. If that's not necessary we could move it up to these lines - or even include within `scanAndSyncOptions`:
https://github.com/unjs/nitro/blob/86b48239d0a38d08854d4caa49cdc3febca8fe18/src/core/nitro.ts#L40-L42
Alternatively, we could export `scanHandlers` to allow frameworks to do this automatically.

fix(core): scan handlers when initialising nitro

---

src/presets/_types.gen.ts
src/rollup/config.ts

(context: Reported by @Atinux testing nitropack nightly against nuxt content module which has top level imports from `#imports` + nuxt renderer from `#internal/nitro`)
Nitro runtime can be imported with different ways `#nitropack/runtime`, `#internal/nitro`, `#nitriopack/runtime/*`. This makes rollup warning about manual chunks.

fix: make sure nitro runtime goes to one chunk

---

package.json
pnpm-lock.yaml

looking into dependencies, saw we have one we don't use anywhere.

chore: remove unused dependency `is-primitive`

---

src/presets/netlify/legacy/preset.ts
src/presets/netlify/preset.ts

resolves https://github.com/nuxt/nuxt/issues/24015
You can also reproduce locally - the issue is that relative paths are resolved relative to `output.dir` which is not overridden in these netlify presets. And in fact no `static` directory is produced.

fix(netlify): ensure preview command is correct

---

src/rollup/plugins/handlers-meta.ts
test/fixture/api/meta/test.ts

https://github.com/unjs/nitro/issues/2564
Checks ObjectExpression keys and attemptes to use the value property as the key if name indefined, allowing for number or number-like keys.

fix(handler-meta): check for `.name` with `undefined`  value in `ObjectExpression`

---

src/presets/netlify/runtime/netlify.ts
test/presets/netlify.test.ts

N/A - discussed on Discord
This is a follow-up to https://github.com/unjs/nitro/pull/2406.
See https://docs.netlify.com/platform/caching/#durable-directive. (This link should go live a bit later today!)
With this change, responses from `isr` routes will be propagated to the global edge network rather than be local to the CDN node that rendered and served it. This will improve performance and reduce serverless function invocations, in various scenarios.
This won't immediately have any effect since we're gradually rolling out the feature on the platform, but by the time nitro v3 (and frameworks that use it, like nuxt v4) are released it should be fully rolled out.

feat(netlify): use new `durable` cache-control directive for `isr` rule

---

docs/1.guide/8.assets.md

Async function always returns a promise. There is no need to explicitly write await unless it is within try/catch. I think here await is kind of redundant.  
https://eslint.org/docs/latest/rules/no-return-await
https://dev.to/danielbellmas/return-await-in-a-trycatch-4oh

docs: move `await` to explicit line for clarity

---

docs/1.guide/4.storage.md

docs(storage): add await before `setItem`

---

src/runtime/internal/error.ts
src/runtime/internal/utils.ts

We should hide error messages (to client) in case of unhandled errors because they can include internal server state.
Thanks for @galactichypernova for discovering this! (issue was if a chunk is missing, we were showing full path but it can be extended to other causes)
Note: This might be a minor behavior change but since we only hide unhandled errors, (`new Error` not `createError`) i guess should be safe for v2 as patch.

fix: hide unhandled error messages in prod

---

docs/1.guide/10.tasks.md
docs/2.deploy/10.runtimes/1.node.md
docs/2.deploy/10.runtimes/deno.md
docs/2.deploy/20.providers/cloudflare.md
docs/2.deploy/20.providers/digitalocean.md
docs/3.config/0.index.md

Followup of https://github.com/unjs/nitro/pull/2576#issuecomment-2212480843
Changes docs to use `_` preset names

docs: convert to underscore preset names

---

docs/3.config/0.index.md

There are around 46 items in `compressPublicAssets`. All are showing blur in the website (https://nitro.unjs.io/config#compresspublicassets). I think it is formatting issue in markdown file. I have given the same format as nitro utils (https://nitro.unjs.io/guide/utils#nitro-utils).

docs(compressPublicAssets): adjust formatting

---

src/core/prerender/prerender.ts

We currently allow skipping route generation in `prerender:generate`, but it's not possible to granularly ignore errors on a per-route basis. Instead we either turn off `failOnError` for the entire build or not.
This change allows the user (or integration) to ignore _particular_ errors based on their own criteria, without disabling `failOnError` protection entirely.
You might also consider this an enhancement - feel free to amend 🙏 
> **background**: was debugging some strange errors prerendering `/_ipx` routes that only occured in Vercel on my personal site - I am happy ignoring these but would like any _other_ errors to be build-breaking ones.

fix(prerender): allow ignoring errors in `prerender:generate` hook

---

src/runtime/internal/utils.ts

Fix regression of https://github.com/unjs/nitro/pull/2591 that hides messages of `fatal: true` errors. 
Context: As pointed out in https://github.com/nuxt/nuxt/pull/28156#discussion_r1679720615, the current assumption was that `fatal` can be also used by user-thrown errors. 
In the future, we might introduce a new `internal` flag to h3 errors to clearly separate internal and user errors from each other and keep (internal) fatal also private.

fix: only hide message of unhandled errors in prod

---

docs/1.guide/2.routing.md

#2415 
Nesting routes with file based routing and using `index` files might be missing from an user's perspective.
Id adds a more complete example of a structure.

docs(routing): add nested example

---

src/core/prerender/utils.ts

resolves https://github.com/nuxt/nuxt/issues/28525
Came across this reported in nuxt. If a protocol relative URL is present in the HTML, for example:
```html
<script>window.__NUXT__={};window.__NUXT__.config={public:{},app:{baseURL:"/",buildId:"714a6c13-10f0-427c-9610-0084561693b4",buildAssetsDir:"/_nuxt/",cdnURL:"//xxx.cqyx.vip/static/"}}</script>
```
Then `/static` will be crawled. We check for protocol but not for protocol relative URLs. I think checking for `host` should be sufficient as `/static` would not have a defined host but let me know if you have a better idea.

fix(prerender): skip protocol relative links

---

docs/2.deploy/20.providers/firebase.md
src/presets/firebase/types.ts

N/A
Google Cloud have added preview support for Node 22. This PR makes Nitro aware that 22 is a valid option now.
See: https://cloud.google.com/functions/docs/runtime-support#node.js

types(firebase): support `22` for `nodeVersion`

---

src/presets/deno/preset.ts

Nitro generates `.output/server/node_moduels` for used dependencies, however deno does not use this directory (and instead tries to download all dependencies again on first run!).
This PR removed old `--unstable` and adds new `--unstable-byonm` flag by default to the start task. (this also speeds up our internal CI tests for deno-server by ~2x)

feat(deno-server): use output `node_modules` for `start` task

---

src/core/dev-server/server.ts

resolves https://github.com/nuxt/cli/issues/469
This is a quality-of-life improvement rather than a bugfix per se.
If a `baseURL` is provided, this means that we can redirect user to it if they access a different URL.

feat(dev-server): redirect requsts without base url

---

src/core/index.ts
src/types/config.ts

Context: https://github.com/nuxt/nuxt/pull/28924, https://github.com/nuxt/ecosystem-ci/actions/runs/10799722624.
Currently changes to `NitroRuntimeConfig` and  `NitroRuntimeConfigApp` are breaking for users/modules consuming `nitropack`.
This ensures types imported from `nitropack` aren't breaking.

fix: ensure legacy runtime config types are populated

---

src/core/index.ts
src/types/runtime/nitro.ts

follow on from https://github.com/unjs/nitro/pull/2724

fix: ensure legacy hook types are populated

---

src/core/config/loader.ts

https://github.com/nuxt/nuxt/pull/28924
This changes the default for `typescript.generateRuntimeConfigTypes` to false in the presence of an external framework, which should prevent this new feature from accidentally breaking downstream types.

fix: do not generate runtime config types with external framework

---

src/runtime/internal/cache.ts

(reported by @danielroe reproduced on nuxt ecosystem CI for storybook docs but issue is generic and hard to reproduce)
Rollup can make `.output/server/chunks/nitro.mjs` with wrong ordering of top-level `const` definitions based on different ways of importing utils/aliases. 
Only way to avoid this with bug, is using function declarations since runtime will **hoist** them up regardless of order (which is issue of rollup)

fix(cache): use top level `function` to avoid rollup chunk ordering issues

---

src/runtime/internal/cache.ts

This changes removes the duplicated `?? opts.maxAge`.

refactor(cache): remove unnecessary nullish coalescing operator

---

src/core/dev-server/server.ts

Improve the error message to include more details on where the error happens.
Before
```
[worker reload] Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'
at throwIfUnsupportedURLScheme (node:internal/modules/esm/load:228:11)
at defaultLoad (node:internal/modules/esm/load:110:3)
at ModuleLoader.load (node:internal/modules/esm/loader:567:13)
at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:442:56)
at new ModuleJob (node:internal/modules/esm/module_job:76:27)
at #createModuleJob (node:internal/modules/esm/loader:455:17)
at ModuleLoader.getJobFromResolveResult (node:internal/modules/esm/loader:266:34)
at …
```

refactor(dev): attach worker reload error as `cause`

---

src/rollup/plugins/raw.ts

#2666 [useStorage] getItem and getItemRaw -> Inconsistent behaviour between dev and preview/production
The change adds the `.sql` extension and the `application/sql` mime type (that is what the `mime` library assigns to .sql files) to the list of file types that are stored as string and not as Uint8Array.
That makes the process to use the server:assets storage for .sql files straightforward and intuitive.
Resolves partly #2666
The change does not solve the issue that useStorage acts differently in dev and production environment, but it solves the problem that .sql files are not stored as string.

feat(raw): add `.sql` to raw file extensions

---

src/presets/cloudflare/runtime/cloudflare-module.ts
src/presets/cloudflare/types.ts

Original issue: https://github.com/unjs/nitro/issues/2480
https://github.com/unjs/nitro/pull/2487 introduced custom types for these events and hooks that contain typos. (for example: `adk()` instead of `ack()`)
There is an open PR: https://github.com/unjs/nitro/pull/2626 but it's still not correct.
There are native types provided by `@cloudflare/workers-types` that we can use for these. 
I updated the exported handler and the hooks accordingly.

fix(cloudflare-module): use correct types for email and queue events/hooks

---

docs/1.guide/0.index.md
docs/1.guide/2.routing.md

While migrating some servers to Nitro (in Nuxt), I came across an odd behaviour that took some time to unveil. For some of the routes errors were handled correctly, while for others the client could not determine the error type. With some trial and error I figured out, that there is a difference between how an error is sent back to the client depening on which route directory the route is placed.
The `routes/` dir uses a Content-Type of `text/html`, while the `api/` dir `application/json` by default. In this PR I tried to clarify this in the docs, wich previously stated that the *only* difference is the `/api/` prefix.
As a side note I would be very interested, in the reasoning behind this behaviour. I feel like it is quite footgun-y, while I don't see the benefits.

docs(routing): add error handling section

---

src/presets/azure/utils.ts

The archiver instance was not configured to follow symlinks.
Fixes #2114

fix(azure-functions): follow symlinks in zip bundle

---

src/core/index.ts
src/runtime/internal/renderer.ts
src/types/runtime/nitro.ts

(context: Discussion with @atinux regarding how to set cache callback options to the renderer handler. This PR, adds a primitive to allow it with advanced usage)
---
This PR adds a new `render:before` runtime hook support for renderer handlers (like Nuxt SSR). This hook allows to customize rendering behavior by intercepting the context:
- Render function can be overridden or wrapped by setting `context.render`
- A response can be directly generated/handled by setting `context.response`
Usage is not restricted to caching only and it allows more general customization of renderer behavior but for particularly caching purposes here is an example:
```js
import { defineNitroPlugin, defineCachedFunction } from "nitro/runtime";
export default defineNitroPlugin((nitro) => {
const cachedRender = …
```

feat(renderer): add `render:before` hook

---

examples/api-routes/api/test.post.ts

Actually It is my personal opinion. It is a POST method and it works well. But for the POST method almost all time `body` is required which items the user is providing. So I think for the POST method example if we provide `readBody` things then it would be slightly more nicer to understand. It will also stay different from GET method which is in `test.get.ts`.

chore(examples): clarify post handler

---

docs/1.guide/1.utils.md

`auto-imported` and `auto-generated` are compound adjective here. The correct form is that it would be used with hyphen(`-`).

docs(server-utils): fix typos

---

src/presets/cloudflare/runtime/_module-handler.ts
src/presets/cloudflare/runtime/cloudflare-module.ts

In the next steps, I am creating new presets for cloudflare-module format (durable and new static asset handling for #2764)
Many of the logic could be reused this is the initial prep refactor.

refactor(cloudflare-module): extract reusable logic

---

examples/websocket/package.json

There are many examples in our Nitro project inside `examples` folder. For example, in the `api-routes` folder, the name of the project is `example-api-routes` in the `name` field in package.json file. In the same way, in the `auto-imports` folder, the `name` in package.json is `example-auto-imports`. In the `cached-handler` folder, the `name` field in package.json is `example-cached-handler`. But in the `websocket` folder, the project name was given `example-hello-world`. I think it would be better to change it to `example-websocket` for maintaining the naming consistency like all other the projects in package.json.

chore(examples): change name in package.json

---

src/runtime/internal/cache.ts

#2609 
This change catches possible errors on getting the cache item, following the same pattern used on setting cache items. With this change, an error when reading the cache (e.g. redis disconnect) will not cause the request to fail but will instead execute the cached function.

fix(cache): catch error when getting cache entry (#2609)

---

src/runtime/internal/cache.ts

#2657
This follows the same approach as https://github.com/unjs/nitro/pull/1459, replacing the `decodeURI` with `decodePath` from `ufo`. This means that an invalid path will no longer throw an error but instead use the undecoded text.

fix(cache): try decode path

---

src/core/config/loader.ts
src/presets/_resolve.ts
src/presets/cloudflare/preset.ts

When using presets with incompatible compatibility dates, this PR adds a new functionality for the resolver to explicitly detect it and throw an error.
Other relavant fixes:
- respect presetOverride (env or args) over auto detection for defaults
- remove extra compat date for `cloudflare-module-legacy` and instead set it for `cloudflare-durable` preset

fix: handle incompatible compatibility date for presets

---

src/core/config/resolvers/database.ts
src/core/config/resolvers/imports.ts

Resolves #2832
Using explicit import paths for generated `#imports`, helps rollup to sort order of dependencies properly.
This PR fixes `useDatabase` issue.
(we might have similar ordering issues for other auto imports)

fix(imports): use explicit import for `useDatabase`

---

src/rollup/plugins/raw.ts

Resolves #2836
Raw plugin tries to guess type of raw asset imports based on known extensions (like `.sql` and `.pdf`)
There was an issue where we are checking the extension before full resolution. If there is a ts import like `../foo.sql` (which actually resolves to `../foo.sql.ts`) we were wrongly picking it as raw asset.

fix(rollup): check raw extensions against resolved id

---

src/core/config/resolvers/imports.ts
test/fixture/.env
test/tests.ts

Resolves #2833 
Similar fix of #2837 for all built-in nitro auto imports. Using explicit entries, rollup can better sort the chunks order.
--- 
Tests for cloudflare had been updated since now with explicit behavior, we have cloudflare limitation that `useRuntimeConfig()` in ambient context (and before first request) does not have access to the environment variable bindings.

fix(imports): use explicit imports

---

src/rollup/config.ts
src/rollup/plugins/externals-legacy.ts
src/rollup/plugins/handlers-meta.ts
src/rollup/plugins/raw.ts

Resolves #2841
Rollup expects resolve options from `resolveId` to be passed through.
`skipSelf: true` override removed for static since it is now default behavior in rollup.

fix(rollup): pass options to `resolve`

---

src/runtime/internal/cache.ts

ref: https://github.com/nitrojs/nitro/discussions/2829#discussioncomment-11145036 resolves #2847
Resolved cache functions always have `.value`. This PR fixes types (which got stricter in 2.10+)

types(cache): resolved value is not nullable

---

src/presets/netlify/legacy/runtime/netlify-builder.ts
src/presets/netlify/legacy/runtime/netlify-lambda.ts
src/presets/netlify/legacy/runtime/netlify.ts
src/presets/netlify/runtime/netlify-edge.ts
src/presets/netlify/runtime/netlify.ts

Discussed on Discord. Possibly also related to https://discord.com/channels/473401852243869706/1303374973465006102/1303374973465006102.
https://github.com/nitrojs/nitro/commit/93d002b72f772fd15153edf01d26298796d7f924 introduced a regression by importing the Deno env polyfill in _all_ Netlify presets rather than just the Netlify Edge preset(s). This fixes that.

fix(netlify): only include env polyfill in `netlify-edge`

---

src/core/config/loader.ts
test/fixture/api/storage/src.dev.ts
test/presets/nitro-dev.test.ts
test/tests.ts

(reported by `@mrk` through @atinux on discord)
With nitro 2.10 refactors, we were missing default storage mounts by mistake.

fix(config): add back default storage mounts

---

test/fixture/api/cached.ts
test/presets/nitro-dev.test.ts
test/tests.ts

`nitro-dev` tests were previously disabled on CI due to instability. trying to reenble.

test: enable dev tests on ci

---

src/core/config/loader.ts

resolves #1568 
Infer using `static` preset (for default) if `static: true` config is set.

fix(config): use static preset if `static` flag is set

---

src/core/scan.ts
test/fixture/api/param/[test-id].ts

resolves #2868
radix3 matcher allows wider matches per segment (as long as starts or in newer version contains `:`).
This PR relaxes `/[param]/` to `/:param/` normalization regex.

fix: scan route files with other chars in param name

---

src/presets/node/preset.ts

resolves #2892
as a side effect of fixes in #2547 (nitro 2.10) we were forcing all nitro-relevant stuff into one big chunk. 
This PR makes sure for node-cluster we create a dedicated external chunk for server-entrypoint.

fix(node-cluster): create dedicated chunk for worker

---

src/runtime/internal/error.ts
test/tests.ts

#2591 prevented possible security issues when user input could be included in the stack trace. 
This PR increases the security of the error page by using secure headers making sure no js code can be executed (specially for production), it cannot have mixed mimes, being iframed or report referer to external resources in case anything goes invalidated in "error message".

fix(error): strict security headers

---

src/types/h3.ts

https://github.com/nitrojs/nitro/issues/1420
`waitUntil` is no longer experimental and we can unflag this.
Could follow up with adding some more info in the docs?

chore: remove experimental comment for `event.waitUntil`

---

src/runtime/internal/app.ts
src/runtime/internal/cache.ts
src/types/fetch/fetch.ts
src/types/h3.ts

https://github.com/nuxt/nuxt/issues/30091
currently the types are incorrect (they include `.raw` and `.create`). This refactors the base '$fetch' type into `Base$Fetch` so this can be used to type `event.$fetch` without needing workarounds.

types: fix type for `event.$fetch`

---

src/rollup/plugins/dynamic-require.ts

discovered in https://github.com/nuxt/nuxt/pull/30279
related in https://github.com/nuxt/nuxt/pull/30278
It seems webpack chunk format changes in the latest minor update. This is a backwards-compatible change, which resolves the issue.

fix(dynamic-require): update to match new webpack chunk format

---

src/presets/netlify/preset.ts
src/presets/netlify/utils.ts
test/presets/netlify.test.ts

followup on #1484 / #2966
(discovered via nitro-deploys as netlify-edge with baseURL is still broken)
This PR adds global `baseURL` prefix to `excludedPath` and `functions[].path`

fix(netlify, netlify-edge): prefix build output paths with `baseURL`

---

src/presets/cloudflare/preset.ts

resolves #2628
There are some valid `cloudflare:` vendor-specific imports we should allow in cloudflare builds.
I couldn't find any official docs that lists them, relying on available types and random docs.

fix(cloudflare): add known `cloudflare:` externals

---

src/core/utils/storage.ts

resolves #2174
Nitro mounts unstorage drivers with same config object that is going to be bundled for prod during build to expose `nitro.storage`.
Due to https://github.com/unjs/unstorage/issues/566, unstorage drivers apply their runtime normalization (such as resolving paths to absolute path) that causes side-effect to be carried to bundled options.

fix(storage): make sure serialized options are not modified

---

src/core/config/resolvers/route-rules.ts
test/fixture/nitro.config.ts
test/presets/netlify-legacy.test.ts
test/presets/netlify.test.ts
test/presets/vercel.test.ts

Fixes: #2463 
Vercel deployment is failing because with this configuration :point_down:  the `.vercel/output/config.json` is wrong.
```
//https://nitro.unjs.io/config
export default defineNitroConfig({
compatibilityDate: "2025-01-07",
srcDir: "server",
routeRules: { "**": { headers: { "x-foo": "bar" } } },
preset: 'vercel'
});
```
Forcing the initial `/` will solve the issue.
FILE: `.vercel/output/config.json`
```
{
"version": 3,
"overrides": {},
"routes": [
{
"headers": {
"x-foo": "bar"
},
"src": "**"
},
{
"handle": "filesystem"
},
{
"src": "/(.*)",
"dest": "/__nitro"
}
]
}
```
FILE: `.vercel/output/config.json`
```
{
"version": 3,
"overrides": {},
"routes": [
{
"headers": {
"x-foo": "bar"
},
"src": "/(.*)"
},
{
"handle": "filesystem"
},
{
"src": "/(.*)",
"dest": "/__nitro"
}
]
}
```

fix(config): normalize route rules with leading slash

---

src/core/config/loader.ts

https://github.com/nuxt/test-utils/issues/537
https://github.com/nuxt/test-utils/issues/1043
Hi :wave:
This PR fix an issue with presets and will allow multiple Nuxt to be ran within the same process (like for vitest workspaces or its vscode extension)
Linked issues above are trying to run multiple nuxt at the same time. It means we need also to be able to start multiple nitro.
Here's the race condition. 
Presets are objects and https://github.com/nitrojs/nitro/blob/e8d609908e9758094d3639b83fe2956ddf872fa8/src/core/config/loader.ts#L141
returns directly the reference of the preset.
If we load 2 nitro at the same time, C12 can delete _layers on the preset object
https://github.com/unjs/c12/blob/67cf916ca727e584390196ce3d3bfb76aa102ec1/src/loader.ts#L267
and the other other may need _layer …

fix(loader): clone preset object

---

src/rollup/plugins/server-assets.ts
src/types/config.ts

resolves #2993
Include files without extension to the bundled server assets + adds an option to customize behavior.

fix(server-assets): include files without ext by default

---

src/core/dev-server/server.ts

resolves #1454
When the dev worker goes under multiple reloads, an annoying `Worker not ready` might be shown, requiring a manual reload.
This PR improves the handling of the situation by retrying the address check with any new `reloadPromise` or up to few seconds.

fix(dev): wait for worker to be ready

---

src/core/build/types.ts

Type stripping works with most versions of TypeScript but we recommend version 5.7 or newer with the following tsconfig.json settings: [nodejs docs](https://nodejs.org/api/typescript.html#type-stripping)

feat: enable `allowImportingTsExtensions` by default

---

package.json
pnpm-lock.yaml

This PR updates unimport dependency to v4 which includes (https://github.com/unjs/unimport/commit/c8c2c97aaad422af7081cc1f6f7433b479f5537d) /cc @antfu 
> upgrade unplugin to v2, requires Node.js >=18.12.0

chore: update unimport to v4

---

src/presets/netlify/utils.ts
test/presets/netlify.test.ts

Context: Found while investigating https://github.com/nuxt/nuxt/issues/30789#issuecomment-2622552133
Netlify functions (both user and framework internals) are bundled by default via a last esbuild step. ([netlify docs](https://docs.netlify.com/frameworks-api/#bundling-2)) this is an unnecessary step for Nitro as nitro already makes an optimized bundle output.
In the legacy netify v1 preset, we were using `nodeModuleFormat: "esm"` to preserve ESM compatibility however it is broken currently with v2 format (https://github.com/nitrojs/nitro/pull/2406) in 2.10.0
With this PR, ESM compat of output remains as-is

fix(netlify): avoid second bundling

---

playground/wrangler.toml
src/presets/cloudflare/runtime/_module-handler.ts
src/presets/cloudflare/runtime/cloudflare-durable.ts

This PR updates the experimental cloudflare_durable preset (#2801) with new context util `durableFetch()` allowing redirecting fetches to durable instance for handling.
This is useful for running code in a durable instance handler, such as access to the storage or connected WebSocket peers.
```ts
export default eventHandler(async (event) => {
const { durable, durableFetch } = event.context.cloudflare;
if (durableFetch) {
return durableFetch(); // Redirect to durable object
}
// This runs inside durable object
console.log("Durable object:", durable);
console.log("context:", event.context.cloudflare.context); // DurableObjectState
return "check console logs";
});
```
Notes:
- `new_classes` in `wrangler` config should be changed to `new_sqlite_classes` to allow storage access
- Durable …

feat(cloudflare-durable): allow redirect fetch to durable object

---

src/runtime/internal/routes/openapi.ts
src/types/handler.ts
test/fixture/api/meta/test.ts
test/presets/nitro-dev.test.ts

Fixes https://github.com/nitrojs/nitro/issues/2920
Add `components` support for OpenAPI module. 
```typescript
defineRouteMeta({
openAPI: {
tags: ["test"],
description: "Test route description",
parameters: [{ in: "query", name: "test", required: true }],
responses: {
200: {
description: "default",
content: {
"application/json": { schema: { $ref: "#/components/schemas/Test" } },
},
},
},
$global: {
components: {
schemas: {
Test: {
type: "object",
properties: {
status: {
type: "string",
enum: ["OK", "ERROR"],
},
},
},
},
},
},
},
});
```
```json
{
"openapi": "3.1.0",
"paths": {
"/api/meta/test": {
"get": {
"tags": [
"test"
],
"parameters": [
{
"in": "query",
"name": "test",
"required": true
}
],
"responses": {
"200": {
"description": "default",
"content": {
"application/json": {
"schema": …
```

feat(openapi): allow `$global.components` in `defineRouteMeta`

---

docs/1.guide/0.index.md

With the addition of Deno commands to the documentation, Deno is likely considered to be supported like any other runtime. As such, it should be mentioned in the recommended setup alongside Node.js and Bun. This pull request also fixes an introductory sentence in the `Getting Started/Directory structure` section that appears to be incomplete.

docs: add deno to installation methods

---

src/core/build/types.ts

export has been deprecated and a new version has been added.

refactor: use `toExports` util from `unimport`

---

src/presets/cloudflare/utils.ts
test/fixture/wrangler.toml

Followup on #2949 and #3064 /cc @@petebacondarwin
This PR improves merging logic for generating `wrangler.json`:
- `pages_build_output_dir`, `main` and `assets` are always overridden + nitro shows warn when it does (this is because, relative paths in generated config are different than user ones
- nodejs_compat related flags are added with more care:
- If user sets both `nodejs_compat_v2` and `no_nodejs_compat_v2`, we warn + remove `nodejs_compat_v2`
- If user sets only `nodejs_compat_v2`, we warn about incompatibility and avoid adding any defaults
- otherwise we add `nodejs_compat` + `no_nodejs_compat_v2`

refactor(cloudflare): improve wrangler merge

---

src/presets/cloudflare/unenv/preset.ts
test/fixture/routes/node-compat.ts
test/presets/cloudflare-module-legacy.test.ts
test/tests.ts

Followup on #3064
This PR:
- Adds support for `globalThis.Buffer`
- Adds basic tests for node compatibility (buffer, crypto, async_hooks)

refactor(cloudflare): improve node compat + add tests

---

package.json
pnpm-lock.yaml
src/runtime/internal/app.ts
src/types/runtime/nitro.ts
test/fixture/routes/fetch.ts

This PR migrates direct fetch implementation from unenv v1 to [node-mock-http](https://github.com/unjs/node-mock-http).
This unblocks nitro v2 to migrate to unenv v2 which has breaking changes for HTTP (https://github.com/unjs/unenv/issues/364).
One other benefit of `node-mock-http` is that it leverages Node.js `node:buffer` and `node:events` (downside is temporary polyfill duplicate in environments without native Buffer/Events support -- cloudflare does support now) 
Complementry h3 (v1) PR: https://github.com/unjs/h3/pull/970

refactor: use `node-mock-http` instead of `unenv` v1 for local fetch

---

package.json
pnpm-lock.yaml
src/presets/cloudflare/unenv/preset.ts
src/rollup/config.ts

Use new `defineEnv` util from unenv to resolve polyfill paths from nitro-specified dependency to avoid conflicting with globals.

fix(rollup): resolve unenv paths with expected version

---

src/runtime/internal/cache.ts

https://github.com/nitrojs/nitro/issues/3063
This change attaches the `waitUntil` function to the cloned event from the incoming event so that it can be used within cached event handlers.

fix(cache): polyfill `event.waitUntil` for `cachedEventHandler`

---

src/core/config/resolvers/error.ts
src/rollup/config.ts
src/rollup/plugins/error-handler.ts
src/types/config.ts
test/fixture/error.ts
test/fixture/nitro.config.ts
test/tests.ts

This PR allows stacking multiple `errorHandler`s with fallback to Nitro default error handler.
With this, frameworks (and users) can add overlay error handlers and fallback to nitro default handlers by not handling response (note) conditionally which allows the leverage new built-in error handler DX introduced in #3002
(note): With h3 v2 / nitro v3, it should be by explicitly not returning a value, generic change in error handlers.

feat: allow stacking error handlers

---

docs/1.guide/6.cache.md

- [ x ] 📖 Documentation (updates to the documentation, readme, or JSdoc annotations)
Cached functions are serialised as JSON regardless of the caching store. This excludes limits the return values of cached functions.
I added a warning to specify this (same way it is specified in the Nuxt docs regarding useState). It's IMO really important to mention it as I spent a good hour trying to understand why my function wasn't behaving as expected, trying to cache a JS Map.
- [ x ] I have updated the documentation accordingly.

docs(cache): add return type constraint for cached functions

---

src/core/build/types.ts

context: https://github.com/nuxt/nuxt/issues/27161
Nuxt is setting paths to match its aliases. We can likely remove this code as it's now implemented in Nitro. But Nitro probably can safely deduplicate the paths too.

fix(types): deduplicate aliases

---

package.json
pnpm-lock.yaml
src/core/build/types.ts
src/core/config/resolvers/paths.ts
src/presets/node/preset.ts
src/rollup/config.ts
src/rollup/plugins/externals-legacy.ts
src/rollup/plugins/externals.ts

This PR uses resolve utils from [exsolve](https://github.com/unjs/exsolve) which have improved performances.
Additional extensions and suffixes have to be kept to avoid breaking behavior change but still perf should be better.
`modulesDir` option is also normalized with trailing slashes to allow search path fast-path (could be better with `file://` URL but nothing significant for now)

perf: use exsolve for module resolution

---

.github/workflows/autofix.yml
.github/workflows/ci.yml
docs/1.guide/5.database.md
examples/database/package.json
package.json
pnpm-lock.yaml

Upgrade db0 to 0.3 with native `node:sqlite` supported in Node.js >= 22.5 (experimental) and Deno >= [2.2](https://deno.com/blog/v2.2) (used as default - `better-sqlite3` driver can be used for node 20 support)

feat: upgrade to db0 0.3 with native `node:sqlite` support

---

package.json
pnpm-lock.yaml
src/presets/deno/preset.ts
src/presets/netlify/preset.ts

Enable Node.js compat for `deno-deploy` and `netlify-edge` presets (based on data from #3128)
There are minor [missing exports](https://github.com/nitrojs/nitro/blob/45c95786538c497508fcfe77b97f5259475e80e1/src/presets/deno/unenv/node-compat.ts) which hopefully deno will add in the future. Also this PR does not injects any globals.
Result is enabling Node.js natives such as AsyncLocalStorage + ~60kB bundle reduction
/cc @serhalp

feat(deno-deploy, netlify-edge): enable node compat

---

src/core/build/dev.ts
src/core/dev-server/proxy.ts
src/core/dev-server/server.ts
src/core/dev-server/worker.ts
src/presets/_nitro/runtime/nitro-dev.ts
src/types/hooks.ts
src/types/nitro.ts

Followup on previous work to improve dev server stability (#2997, #3001, #3003)
This PR changes the internal dev server into 2 components (server, and worker) with much better state control ability for the server.
- Server is responsible for creating the h3 dev instance, listener, and managing workers.
- Worker is responsible for controlling its lifecycle and keeping correct state flags 
- Instead of using (singleton) promise chains like before, the server keeps track of all created workers and picks the latest+active worker to handle the next request. 
Other notable changes:
- The `accessSync` on the socket has been completely removed which should improve Windows stability. 
- Error handling is unified with a single `onError` hook on h3 .
- Using virtual unix sockets in the Linux …

refactor(dev): rewrite internal dev server

---

src/core/config/defaults.ts
src/core/config/loader.ts
src/core/config/resolvers/unenv.ts
src/rollup/config.ts
src/types/config.ts

Cases like #3140 require dynamic unenv preset injection. (without this, we need to manually handle merging logic before unenv)
This PR makes `options.unenv` to be an array of presets.

feat(config): support `unenv` array

---

src/core/build/build.ts
src/types/hooks.ts

Add a `build:before` hook that gets called before rollup config being prepared to allow customizing nitro options. requirement for #3140

feat: add `build:before` hook

---

playground/routes/index.ts
src/core/prerender/prerender.ts
src/presets/cloudflare/utils.ts
src/presets/deno/runtime/deno-server.ts
src/presets/netlify/legacy/utils.ts
src/presets/node/runtime/node-cluster.ts
src/presets/vercel/utils.ts
src/rollup/plugins/handlers-meta.ts
src/runtime/error.ts
src/runtime/internal/cache.ts
src/runtime/internal/error/dev.ts
src/runtime/internal/error/prod.ts
src/runtime/internal/task.ts
src/runtime/internal/utils.ts

Remove extra `[nitro]` tags in various places and prefer `nitro.logger` or no tag (`[nitro] [request error]` can be confusing for source)

refactor: remove extra tag

---

src/presets/cloudflare/types.ts
src/presets/cloudflare/utils.ts
test/fixture/wrangler.toml

followup on #3064 .. #3065 .. #3067 .. #3140
Enabling native Node.js compatibility support for Cloudflare workers requires a very simple `nodejs_compat` flag to be declared for [workerd](https://github.com/cloudflare/workerd) runtime.
However with a long chain of wrangler and cloudflare API/CI/Dashboard in between, even if Nitro attempts to auto-enable this feature not only cloudflare dashboard features will be disabled and forcing users to use a `wrangler.{toml,json}` instead of the dashboard for anything else, but also causes **all environment variables from the dashboard to be immediately discarded**. 
The latter makes it a very dangerous thing to enable even using compatibility dates (we might enable by default for Nitro v3 only).
With this PR two options are exposed from Nitro:
- …

refactor(cloudflare): strictly enable `nodeCompat` and`deployConfig` under flags

---

src/rollup/config.ts
src/runtime/internal/error/dev.ts
src/runtime/internal/error/prod.ts
src/types/global.ts

#2980
This PR is a rework of #2713 to enable auto-redirect requests made outside of nitro configured `baseURL`, for both dev and prod but on final error handler 404 so any other custom hook or route rule could intercept if needed.
This PR also adds (build-time static) `import.meta.baseURL` so the code in error handler remains fully standalone from runtime logic.

feat: auto redirect to base url

---

src/core/config/resolvers/paths.ts

currently it seems impossible to pass/configure a `workspaceDir`

fix: respect configured `workspaceDir`

---

docs/3.config/0.index.md

Adds an internal anchor to the route meta to help users understand how to define the open API meta for their route

docs: link route meta to openAPI

---

src/presets/_nitro/runtime/nitro-dev.ts

If running multiple instances of Nitro dev server (programmatically, in tests) in the same process id, socket names can conflict in Linux and Windows that use abstract Sockets.
This PR uses the same full path as part of the socket name to avoid this.

fix(dev): use full socket path for windows and linux

---

src/presets/_nitro/runtime/nitro-dev.ts

This PR tries to fix (rare) conditions that dev server socket names can be shared or conflicting by adding random part

fix(dev): add random number to socket name

---

src/core/dev-server/vfs.ts

Nitro dev server has a default `/_vfs` endpoint for debugging virtual templates, however, it can leak some limited information when using `nitro dev --host`.
This PR limits this feature to only when incoming request IP is strictly `::1` or `127.*`.
> [!NOTE]
> this change, limits some valid cases too, like using external IP of same computer to access the endpoint, but considering it is just a debugging feature I think worth doing it and minimizing exposure changes.
Alternative option was validating incoming host but it can be also forged. 
/cc @danielroe @antfu

fix(dev): limit `/_vfs` to local ips only

---

src/presets/_nitro/runtime/nitro-dev.ts

For hardly reproducing issues (found from nuxt CIs), listening to the socket can fail. This PR adds a auto fallback to dev worker listener to use port if first socket try failed.
Also refactoring general order in logic for dev worker entry

fix(dev): auto fallback to port if socket listening failed

---

src/presets/_nitro/runtime/nitro-dev.ts

Node.js <= 18 does not have `globalThis.crypto`. Nitro 2.x supports Node.js 18 and as ecosystem is shifting to 20+, we might face more issues (Youch needs it and crossWS will likely need it too)

fix(dev): polyfill `globalThis.crypto` for Node.js 18

---

.github/workflows/ci.yml
build.config.ts
package.json
playground/routes/index.ts
pnpm-lock.yaml
src/runtime/internal/error/dev.ts

Because youch 4.x requires Node.js 18 (by engines field), having it as dependency makes ecosystem issues and requiring requires `--no-engine-checks` for Node.js 18 support (even tough we add required runtime polyfill #3168)
(Note: This is only for Nitro v2 backward compact. Nitro v3 will be back to normal dep)

build: inline youch dependency

---

.github/workflows/ci.yml
build.config.ts
package.json
pnpm-lock.yaml
src/runtime/internal/error/dev.ts

rework of #3169 with the diffrence of using external/temporary [youch-redist](https://github.com/pi0/youch-redist)
The reason is that Nuxt has a bug when it fails nitro builds when nitro tries to import another of it's internal. fixed by https://github.com/nuxt/nuxt/pull/31246 but older nuxt versions have problem so...

build: use `youch-redist`

---

src/types/handler.ts

https://github.com/nitrojs/nitro/issues/3173
Make $global optional for openAPI route meta so apps upgrading from niro 2.10 to 2.11 don't get typecheck to fail.

types: mark `$global` optional for `NitroRouteMeta`

---

src/presets/_nitro/runtime/nitro-dev.ts

Since 2.11 we have switched to abstract linux sockets to avoid filesystem related issues.
After (dozens of) trial and error, it seems a major behavior in Node.js between 18, 20 and 22 (first line filled with `@` (zero) is 18 which is completely broken, 20 slightly different and 22 working well)
This PR:
- Uses short abstract socket names in linux all the time to remove need of truncate in any level
- Only leverages abstract Socket for Node.js >= 20
before:
after:
windows pipes (while don't have limit like linux) are also simplified to be consistent:

fix(dev): use abstract sockets on linux with node.js >=20

---

src/core/dev-server/worker.ts
src/presets/_nitro/runtime/nitro-dev.ts

This PR essentially reverts #2997 fix for 2.11
issue was that, if one linux user stating a nitro server, it was creating `/tmp/nitro/` with permissions for that specific user and any other user would be blocked.
By moving socket to local build dir, we solved this issue but also introduced more possibilities that if permissions of build dir is bad, it causes more issues.
Since after iterations in 2.11, we are now generating an almost reliable unique socket name, we can use `/tmp/nitro-{name}.sock` instead.

fix(dev): use os tmp dir for unix sockets

---

src/presets/_nitro/runtime/nitro-dev.ts

resolves https://github.com/nuxt/nuxt/issues/31293
Bun added support for socket listeners, however seems buggy on windows only.

fix(dev):  use port for bun on windows

---

package.json

Node.js 18 is EOL in lass than 1 month and for long-term support for Nitro v3, it makes sense to require minimum Node.js 20 (if _runtime_ polyfills will be needed for ecosystem adoption, it will be provided, engines is a precaution)

build!: minimum Node.js 20

---

src/runtime/internal/app.ts

resolves #3225
If user code is not imported last, nitro app entry can partially import it's internals that will be added first to the rollup entry but won't be available until after user code. 
This can cause issues like `Error: Cannot access ... before initialization`

fix(app): import user code last to avoid initialization order issues

---

src/dev/proxy.ts
src/dev/worker.ts

Nitro dev server can cause browser tabs to be stuck in case there is a proxy on top of it (docker or nuxt dev wrapper for example)
This PR fixes this problem by always propagation errors to upper layers instead of silently ignoring `ECONNRESET` into a pending state.
Also small fix that server is fully closed before destroying socket (could not find any diff just additional fix in case)

fix(dev): always throw proxy errors

---

src/config/resolvers/paths.ts

issue revealed in playground after #2775
`srcDir` needs to be resolved relative to `rootDir`, we were previously wrongly resolving it from CWD which is most of the times same as rootDir unless running nitro commands from another dir.

fix(config): resolve `srcDir` relative to `rootDir`

---

src/presets/aws-lambda/runtime/aws-lambda-streaming.ts

#3228 
The `aws-lambda` preset with `awsLamba.streaming` option in `nitro.config.js` used a different handler from `aws-lambda` without streaming enabled. This other handler stripped cookies from the response headers, and did not add them back like the non-streaming handler did.
This PR fixes that behavior, such that aws-lambda-streaming builds will properly set cookies, which is very important for web frameworks like SolidStart and Tanstack Start who use nitro to support authentication in stream-enabled lambdas.
Resolves #3228

fix(aws-lambda): aws-lambda-streaming set-cookie headers

---

package.json
pnpm-lock.yaml
src/runtime/internal/routes/openapi.ts
src/types/handler.ts
src/types/openapi-ts.ts
src/types/virtual/server-handlers-meta.d.ts
test/fixture/tsconfig.json
test/presets/nitro-dev.test.ts
tsconfig.json

Working on #3251, i noticed `openapi-typescript` (which we only need for types for experimental openapi support) takes a huge chunk of install size and deps. [graph](https://npmgraph.js.org/?q=openapi-typescript), [packagephobia](https://packagephobia.com/result?p=openapi-typescript) (local test adds `42M` / `1996` files!)

build: inline openapi-typescript types

---

src/core/config/loader.ts
src/types/config.ts

this allows configuring the location of the `.env` file, which is needed (for example) with nuxt's `--dotenv` argument. Otherwise, while Nuxt can load from `.env.production` (or similar), nitro will always load in the values from `.env` into `process.env`.
alternatively, it would be just as good to disable Nitro loading a `.env` file.
related: https://github.com/nuxt/cli/pull/381

refactor: allow setting `dotenv` config for `loadOptions`

---

package.json
pnpm-lock.yaml
src/presets/cloudflare/preset.ts

detect cloudflare workers build CI (https://developers.cloudflare.com/workers/ci-cd/builds/) to use `cloudflare_module` format with zero config.
(will be testing on nightly before release)
https://github.com/unjs/std-env/pull/156

refactor(cloudflare): detect workers build ci

---

src/dev/worker.ts

resolves #3087
This PR:
- Changes the default value of `NITRO_SHUTDOWN_TIMEOUT` in dev to `30_000`, matching prod. This prevents confusion between environments.
- Fixes the `NITRO_SHUTDOWN_TIMEOUT` time unit to milliseconds in dev.

fix(dev)!: `NITRO_SHUTDOWN_TIMEOUT` with ms value

---

src/presets/cloudflare/preset.ts

Assets generated to `.output/public` need to be prefixed with `baseURL`  for working deployment.

fix(cludflare-module): respect `baseURL` for public output assets

---

src/presets/cloudflare/utils.ts

followup on #3280
We generate `.output/public/{baseURL}` but deploy config should point to `.output/public` itself to allow serving assets under baseURL

fix(cludflare-module): remove baseURL prefix from deploy config dir

---

playground/nitro.config.ts
src/core/config/resolvers/compatibility.ts
test/fixture/nitro.config.ts
test/fixture/types.ts

Prompt for compatibility date can be bothersome in some cases.
This PR replaces the current (force) prompt to update with a simple warning about guiding users for adding the compatibility date + new docs (#3292)
Additionally, `compatibilityDate: "latest"` is a possible value in latest compatx (0.2) for cases like examples or playgrounds where this date does not matter (intentionally not widely documented ;however, auto-complete exists)
Also, silenting warning for test environments.

refactor: soft warning for compatibility date

---

src/presets/cloudflare/runtime/cloudflare-durable.ts

This PR exposes `publish` to the experimental `cloudflare-durable` preset to allow publishing to all peers globally.
> [!NOTE]
> As this is an experimental preset, API changes can happen!
**Example:**
```ts
export default eventHandler(async (event) => {
const { durableFetch, durable } = event.context.cloudflare;
if (durableFetch) {
return durableFetch();
}
durable.publish("topic", { message: "Hello, world!" });
return "message sent";
});
```
<details>
<summary>nitro config</summary>
```ts
import { defineNitroConfig } from "nitropack/config";
export default defineNitroConfig({
compatibilityDate: "latest",
srcDir: "server",
experimental: {
websocket: true
},
cloudflare: {
nodeCompat: true,
deployConfig: true,
wrangler: {
migrations: [
{
tag: "v1",
new_sqlite_classes: ["$DurableObject"],
}, …
```

refactor(cloudflare-durable): expose `publish` from durable object

---

docs/1.guide/8.assets.md

Resolves https://github.com/nitrojs/nitro/issues/3272
https://github.com/nitrojs/nitro/pull/2775 changed the `dir` paths in these examples by mistake.
I reverted these changes and tried to make it more clear what paths should be used.

docs: correct example paths for  `serverAssets` option

---

src/rollup/plugins/handlers-meta.ts

this addresses an issue found by @atinux in https://github.com/nuxt-ui-pro/chat/pull/10.
minimal reproduction: https://stackblitz.com/edit/github-eddeyrez?file=nitro.config.ts
the issue is that the handlersMeta plugin always tries to load files from disk, but in some cases this is impossible. We bail out if a null byte is detected, which will cover nitro virtual files as well as any virtual files present from other plugins.

fix(open-api): load virtual files from rollup rather than fs

---

src/build/plugins/raw.ts

https://github.com/nitrojs/nitro/pull/3211#issuecomment-2820298178
Resolves the issue that `.json` files are not "handled correctly" by setting the [module type](https://rolldown.rs/guide/in-depth/module-types#how-module-types-affect-users) of all non-binary raw files to `js` while keeping the transform code.
Another option would be setting the `moduleType` to `json` (which is the default for `.json` files) and keep the file as is, removing the need for transforms. In my test, that clashed with other types of files though.

fix: explicitly set moduleType to `js` for raw loader

---

src/build/rolldown/config.ts

Related Issue/PR: https://github.com/nitrojs/nitro/pull/3211
This PR resorts back to the rollup replace plugin for now. After https://github.com/rolldown/rolldown/issues/4257 is resolved, switching to the rolldown one should be drop-in.
I'd still consider using `define` for most scenarios as it is less brittle (AST replacement instead of direct one). It does *not* support functions though.

fix(rolldown): use rollup replace plugin for now

---

src/presets/netlify/preset.ts

Currently, netlify is ignoring any cache directives because caching is not enabled via the integration manifest.
A config like the following would have no effect:
```
routeRules: {
'/hello-cache': {
cache: {
maxAge: 38400,
},
},
}
```
See: https://docs.netlify.com/edge-functions/optional-configuration/#response-caching
#3256 
This PR contributes to getting the netlify preset to properly support caching (see #3256). It should be backwards compatible in the sense that the preset change has no effect for existing deployments.
Follow up work would still be needed as, after the patch, the only way to control edge function caching is through additional header config in `routeRules`:
```
'/hello-cache-headers': {
headers: {
'Cache-Control': 'public, max-age=3600, must-revalidate', …
```

fix(netlify-edge): enable function caching

---

src/runtime/internal/app.ts

resolves #3335
In direct fetch scenarios (like an SSR route that fetches an API), we need to inherit `_platform` context to make context like `event.context.cloudflare` inherited.

fix: inherit `context._platform` for direct fetch

---

lib/config.d.mts
src/types/config.ts
src/types/global.ts

resolves #3337
This PR removes the `rootDir` from `defineNitroConfig` as this option should ony be used in programmatic usage, as discussed in https://github.com/nitrojs/nitro/pull/3344#discussion_r2073348863.
Note that only the top-level `rootDir` type is removed, while the nested `rootDir` within `C12InputConfig` and `NitroPreset` is kept for simplicity. Because `NitroConfig` is a bit complicated, we'd otherwise have to redeclare a new type (e.g., `NitroConfigInput`) to replicate `NitroConfig`'s definition to fully remove `rootDir`. WDYT 🤔

types: omit `rootDir` in `defineNitroConfig()`

---

src/core/scan.ts

#3248 
`scanDir` now handles `ENOTDIR` system errors, logging a simple warning, any other error still gets thrown.

refactor: better error for scanned dirs being a file

---

src/rollup/config.ts

https://github.com/nuxt/nuxt/pull/32130
Some libraries use `global.` instead of `globalThis.`. `global.` is a **Node.js specific** API.
Nitro used a build-time replace plugin to update usage. But it introduces (smaller) issues like when `global.` being used in a string constant.
Since unenv v2 migration, we always inject a runtime polyfill for `globalThis.global.` (effectively same as `global.`) ([preset](https://github.com/nitrojs/nitro/blob/32e1850760fa19466ab69d31636ead05a856dc6c/src/config/resolvers/unenv.ts#L36)).
This PR removed unnecessary build-time replace workaround.

fix: depend on unenv `global.` polyfill

---

src/core/build/types.ts

https://github.com/nuxt/nuxt/issues/24314
This change allows for type imports to be resolved from an absolute to a relative path. The same was done for Nuxt here:
- https://github.com/nuxt/nuxt/pull/24413

fix(types): resolve absolute paths for type imports

---

src/rollup/plugins/externals.ts
src/types/rollup.ts

#3418
When Nitro uses a read-only `node_modules`, the Rollup `externals` plugins copies files and preserves the read-only permissions.
This results in a failure because the plugin needs to modify those files later in the build.
This PR applies `chmod 644` to all copied external files in the `.output/server/node_modules/*` folder.

fix: add an option to change output `node_modules` permission

---

src/presets/cloudflare/preset.ts
src/presets/cloudflare/utils.ts

https://github.com/nitrojs/nitro/issues/3441
For the `cloudflare-module` preset, Cloudflare now supports `_headers` ([docs](https://developers.cloudflare.com/workers/static-assets/headers/)).
The `cloudflare-module` preset is updated here to support defining custom headers for static js/build assets via `routeRules`, similar to the `cloudflare_pages` preset ([source](https://github.com/nitrojs/nitro/blob/b2276b479784a52b62b66030cff7a38838cb5787/src/presets/cloudflare/utils.ts#L108C23-L108C42)).
I renamed the internal `writeCFPagesHeaders` method to `writeCFHeaders` since it is no longer Cloudflare Pages specific.
Resolves https://github.com/nitrojs/nitro/issues/3441
> [!Important]
> I can verify the `_headers` file is generated, but it would be nice to verify in a deployment before merge. …

fix(cloudflare-module): generate `_headers` in dist

---

playground/vite.config.mjs
src/build/vite/plugin.ts
src/build/vite/prod.ts

#3461
Working on [vite-examples](https://github.com/nitrojs/vite-examples) it is more convinient for custom services to have a simple `server` entry (provided for vite's default `ssr` env)
With this feature, only if users don't already explicitly define `ssr` service or `ssr` environment, and if a `server.{ext}` exists in project root (similar to `index.html`) will be used as entrypoint for SSR.
In case of metaframework integrations, they usually most implement `ssr` service themeselves so this future is mainly for direct nitro plugin users.

feat(vite): detect server entry

---

docs/1.guide/6.cache.md

This update adds detailed documentation on how Nitro v2 automatically normalizes cache keys to improve compatibility and security.
- Explanation of the automatic normalization process that removes non-alphanumeric characters such as `/` and `-` from cache keys.
- Examples illustrating how raw keys like `/api/products/sale-items` are transformed into normalized keys such as `api/productssaleitems.json`.
- Introduction of the new `escapeKey(key: string): string` utility function exported by Nitro.
- Guidance on how to use `escapeKey()` to manually reproduce Nitro’s normalized cache key format, especially useful when manually invalidating cache entries.
- Code samples demonstrating both the normalization and manual invalidation processes.
This helps developers better understand cache key …

docs(cache): add note about normalizing keys

---

package.json
pnpm-lock.yaml
scripts/gen-presets.ts
src/cli/commands/dev.ts
src/core/config/loader.ts
src/presets/_nitro/nitro-dev.ts
src/presets/_resolve.ts
src/types/preset.ts

This PR adds support for built-in dev presets to be implemented, emulating closer to production environment and adding any additional primitives.
```js
export const presetDev = defineNitroPreset(
{
extends: "nitro-dev",
// hooks and extended config for env emulation
},
{
name: "preset",
dev: true,
url: import.meta.url,
}
);
```
---
This change is a little bit risky, especially for wrapper frameworks but should work well.
Checklist for meta frameworks:
- For dev, `preset: "nitro-dev"` should not be hardcoded
- `typescript.generateRuntimeConfigTypes` should be disabled as before if `framework.name` is set

feat: dev presets

---

package.json
pnpm-lock.yaml
src/core/config/loader.ts
src/presets/cloudflare/dev.ts
src/presets/cloudflare/preset.ts
src/presets/cloudflare/runtime/plugin.dev.ts
src/presets/cloudflare/types.ts

This PR merges [nitro-cloudflare-dev](https://www.npmjs.com/package/nitro-cloudflare-dev) into the main nitro CF presets (based on #3467)
Type augmentations are specifically not ported. 
Requirements to opt in:
- Use the latest version of Nitro v2 (or, in case of meta-frameworks, recreate lockfile)
- Compatibility date `latest` or >= `2025-07-13`
- Set `preset` config to `cloudflare-module`, `cloudflare-pages` or `cloudflare-durable` (experimental)

feat: add cloudflare dev preset

---

src/core/prerender/prerender.ts

/cc @kricsleo
Temporarily reverts nitrojs/nitro#3394 as running tests locally fails (need to properly investigate)
```
[request error] [unhandled] [GET] http://localhost/_swagger
H3Error: ENOENT: no such file or directory, open '/private/Users/pooya/Code/nitro-v2/test/fixture/.output/public/_swagger/index.html'
at open (node:internal/fs/promises:638:25)
... 8 lines matching cause stack trace ...
at async Promise.all (index 0) {
cause: Error: ENOENT: no such file or directory, open '/private/Users/pooya/Code/nitro-v2/test/fixture/.output/public/_swagger/index.html'
at open (node:internal/fs/promises:638:25)
at Object.readFile (node:internal/fs/promises:1242:14)
at file:///Users/pooya/Code/nitro-v2/node_modules/.pnpm/h3@1.15.3/node_modules/h3/dist/index.mjs:2003:19
at Object.callAsync …
```

revert #3394

---

src/core/build/prod.ts
src/presets/cloudflare/preset.ts
src/presets/deno/preset-legacy.ts
src/presets/deno/preset.ts
src/presets/edgio/preset.ts
src/presets/netlify/legacy/preset.ts
src/presets/netlify/preset.ts
src/presets/vercel/preset.ts

Resolves #3480
With #3388, we have introduced a fix to properly resolve deploy/preview hint commands; however, in the generated `nitro.json`, frameworks need to support this, which might not be straightforward immediately.
This PR:
- Resolves commands inside `nitro.json`
- Updates the deploy/deploy command in missing places
- Uses consistent resolution from rootDir instead of cwd also for CLI output (slight behavior change)

fix(build): resolve `deploy` and `preview` commands

---

src/build/vite/plugin.ts
src/build/vite/prod.ts
src/build/vite/types.ts

use `buildApp` hook from vite 7 instead of configuring a builder
this ensures compatibility with frameworks that configure a builder themselves

fix(vite): use buildApp hook and construct manifest from bundle

---

src/presets/vercel/utils.ts
test/presets/vercel.test.ts

Reported in https://github.com/nuxt/nuxt/issues/32718
We have introduced o11y route hints in 2.12 (https://github.com/nitrojs/nitro/pull/3474), it should make sure to generate PCRE-compliant named capture groups (404 in case of reported issue is invalid since it shouldn't start with a digit)
This PR also uses a less conflicting anonymous group for `/**` routes.

fix(vercel): valid regex for o11y routes

---

src/presets/vercel/utils.ts
test/presets/vercel.test.ts

Nice idea by @tobiaslins ❤️ 
Fallback routes in Vercel o11y panel (that match `/**` or 404 handler) are displayed as `__nitro` which is not much undrestandable. This PR renames it to `__fallback`

refactor(vercel): rename `__nitro` function to `__fallback`

---

src/build/config.ts
src/build/types.ts
src/config/resolvers/paths.ts
test/fixture/nitro.config.ts

> (@pi0) 
> We are removing default `~/` and `@/` aliases to make the default Nitro behavior less opinionated and less chance to conflict with user custom aliases.
> We might add them back later, either via a flag or as the lowest priority in resolution. 
> This PR in meanwhile, unblocks vite plugin adoption

refactor!: remove default `~` and `@` aliases

---

package.json

Node.js 16, 17 and 18 are EOL (18 last updated on Mar 27, 2025)
https://nodejs.org/en/eol
This PR makes engine to warn about old, and probably partially working runtimes.

build: update node engine to `^20.19.0 || >=22.12.0`

---

src/presets/vercel/utils.ts

This is a hotfix to address an unintended regression from https://github.com/nitrojs/nitro/pull/3562 - when re-enabling observability on a route ending in `/index.func`, we get 404s - this needs further investigation.

fix(vercel): skip o11y routes matching `isr` route rule

---

src/presets/aws-amplify/types.ts
src/presets/azure/utils.ts
src/presets/vercel/utils.ts

Actually there are some runtime versions which are changed. For example, in aws-amplify now only supported node.js runtime is 20 and 22. (https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtimes-supported). 
In azure, 18, 20, 22 (https://learn.microsoft.com/en-us/azure/azure-functions/functions-reference-node?tabs=typescript%2Cwindows%2Cazure-cli&pivots=nodejs-model-v4#supported-versions). We can go below 18 but it requires specific file structure. 
In vercel, 20, 22. (https://vercel.com/docs/functions/runtimes/node-js/node-js-versions#default-and-available-versions)
That is why I thought may be we can update something in the codebase as well.

refactor(aws-amplify, azure, vercel): update node to 20, 22

---

src/build/config.ts

This PR removes legacy `#build` alias which was pointing to build dir. 
This is mainly to avoid conflicting with user defined `#build` alias but also this feature should really not be used by end-users to depend on intermediate build dirs (unless they explicitly need to!)

refactor!: remove `#build` alias

---

playground/package.json
src/build/info.ts
src/build/rolldown/prod.ts
src/build/rollup/prod.ts
src/build/vite/plugin.ts
src/build/vite/preview.ts
src/build/vite/prod.ts

This PR adds basic `vite preview` integration by spawning the preview command.
As another improvement, we symlink output dir to known path of `<root>/node_modules/.nitro/last-build` this helps to discover real path of build dir.

feat(vite): basic `vite preview` support

---

src/config/resolvers/paths.ts

Dirs explicitly ending with `/` improve exsolve resolution perf since it knows it is a dir without needing to stat

refactor(config): make sure dirs end with `/`

---

src/build/vite/plugin.ts

Improve conssitency with vite [ssr docs](https://vite.dev/guide/ssr) by scaning ssr entry from:
- `entry-server.ext`
- `app/entry-server.ext`
- `src/entry-server.ext`

refactor(vite): default ssr entry to `entry-server`

---

package.json
pnpm-lock.yaml
src/build/rollup/config.ts
src/build/vite/rollup.ts
src/config/defaults.ts
src/types/config.ts

rollup-plugin-visualizer has a really big [dependency graph](https://npmgraph.js.org/?q=rollup-plugin-visualizer) and is incompatible with both vite and traced node modules. /cc @43081j
This PR for now removes `analyze` feature from nitro v3 but it can be fairly easily added back by users. 
---
Ideally i want to adopot [vite-bundle-analyzer](https://github.com/nonzzz/vite-bundle-analyzer) which  as rollup/rolldown/vite support and zero dep 🚀 but couldn't work it with rollup/rolldown (does nothing) and with vite, env api seems not supported (ssr and nitro envs are not displayed) -- once fixed we might add this as official integration. /cc @nonzzz @kricsleo

refactor!: remove `rollup-plugin-visualizer` (for now)

---

src/build/vite/plugin.ts
src/build/vite/types.ts

Makes passing nitro config easier also allows other vite plugins to (pre) inject some nitro init config if they want to.
```js
import { defineConfig } from "vite";
import { nitro } from "nitro/vite";
import tailwindcss from "@tailwindcss/vite";
export default defineConfig({
plugins: [nitro(), tailwindcss()],
nitro: {
renderer: {
entry: "app.html",
},
},
});
```

feat(vite): support top level `nitro` config in `vite.config`
